In [ ]:
!pip install sentence-transformers==5.6 transformers==5.16.1 torch python-Levenshtein scipy scikit-learn pandas tqdm

Collecting sentence-transformers==5.6
  Downloading sentence_transformers-5.6.0-py3-none-any.whl.metadata (18 kB)
Collecting transformers==5.16.1
  Downloading transformers-5.16.1-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.13/dist-packages (2.11.0+cu130)
Collecting python-Levenshtein
  Downloading python_levenshtein-0.27.5-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (4.67.3)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers==5.6) (1.33.0)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers==5.6) (2.1.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers==5.6) (4.16.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from transformers==5.16.1) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from transformers==5.16.1) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers==5.16.1) (2025.11.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/lib/python3.13/dist-packages (from transformers==5.16.1) (0.23.2)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers==5.16.1) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers==5.16.1) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch) (4.0.7)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch) (2025.12.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.85)
Collecting Levenshtein==0.27.5 (from python-Levenshtein)
  Downloading levenshtein-0.27.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting rapidfuzz<4.0.0,>=3.9.0 (from Levenshtein==0.27.5->python-Levenshtein)
  Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch) (1.8.2)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers==5.6) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers==5.6) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers==5.6) (0.28.1)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers==5.16.1) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers==5.16.1) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers==5.16.1) (0.0.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers==5.6) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers==5.6) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers==5.6) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers==5.6) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers==5.6) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers==5.16.1) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers==5.16.1) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers==5.16.1) (0.1.2)
Downloading sentence_transformers-5.6.0-py3-none-any.whl (596 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 596.4/596.4 kB 20.2 MB/s eta 0:00:00
Downloading transformers-5.16.1-py3-none-any.whl (12.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 138.6 MB/s eta 0:00:00
Downloading python_levenshtein-0.27.5-py3-none-any.whl (9.5 kB)
Downloading levenshtein-0.27.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (157 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.4/157.4 kB 17.3 MB/s eta 0:00:00
Downloading rapidfuzz-3.14.6-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 113.8 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, Levenshtein, python-Levenshtein, transformers, sentence-transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.18.0
    Uninstalling transformers-5.18.0:
      Successfully uninstalled transformers-5.18.0
  Attempting uninstall: sentence-transformers
    Found existing installation: sentence-transformers 5.7.0
    Uninstalling sentence-transformers-5.7.0:
      Successfully uninstalled sentence-transformers-5.7.0
Successfully installed Levenshtein-0.27.5 python-Levenshtein-0.27.5 rapidfuzz-3.14.6 sentence-transformers-5.6.0 transformers-5.16.1

In [ ]:
import os
import torch
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.allow_tf32 = False
os.environ["HF_HUB_DOWNLOAD_TIMEOUT"] = "60"   # default is 10s; raise it
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"   # faster, more robust downloads

In [ ]:
# Hugging Face login - required for gated models (e.g. google/embeddinggemma-300m)
from huggingface_hub import login
login()  # paste your HF token when prompted

/usr/local/lib/python3.13/dist-packages/huggingface_hub/constants.py:302: FutureWarning: The `HF_HUB_ENABLE_HF_TRANSFER` environment variable is deprecated as 'hf_transfer' is not used anymore. Please use `HF_XET_HIGH_PERFORMANCE` instead to enable high performance transfer with Xet. Visit https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfxethighperformance for more details.
  warnings.warn(

# Exam 1 - Measurement geometry

**Definitions** (functions, ranges, units, plotting).

Changes vs. the previous version:

* symmetric similarity matrices are drawn as the upper triangle only
  (`plot_matrix(..., triangle=True)`); the asymmetric *Digits <-> Words*
  column is still drawn in full;
* the conversion line plots get headroom above 1.0 so the legend cannot
  overlap the curves;
* `range_texts` / `range_labels` factored out, so Exam 3 builds exactly the
  same strings;
* the overview figure is saved once instead of once per row, and the
  per-pair debug prints in `alignment_curve` are gone.

* **the ranking metric (Tables 1 and 2) is now computed over all anchors.**
  Previously only the first item of each range served as anchor, which only
  tests monotonicity from the range start. Now every item serves once as
  anchor, is excluded from its own candidates, and candidates are ranked
  against their true distance to it. `log_1_100k` and `scientific` use log10
  distance (`LOG_RANGES`), the other ranges linear distance. Pairs with equal
  true distance are skipped in pairwise accuracy; Kendall's tau is tau-b.
  **Every number in Tables 1 and 2 changes.** No extra embedding inference is
  needed, the metric reuses the similarity matrix.

Apart from the ranking metric, nothing that touches a reported number was changed.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import gc
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from scipy.ndimage import gaussian_filter1d
from scipy.stats import kendalltau
import pandas as pd
import os

# Output directories
RESULTS_DIR = "produced_results"
CSV_DIR = os.path.join(RESULTS_DIR, "csv")
PDF_DIR = os.path.join(RESULTS_DIR, "pdf")
TEX_DIR = os.path.join(RESULTS_DIR, "tex")
os.makedirs(CSV_DIR, exist_ok=True)
os.makedirs(PDF_DIR, exist_ok=True)
os.makedirs(TEX_DIR, exist_ok=True)


# --------------------------------------------------------------------
# NUMERIC RANGES
# --------------------------------------------------------------------

RANGES = {
    "local_0_10": np.arange(0, 10.5, 0.5),
    "medium_0_1000": np.arange(0, 1001, 50),
    "log_1_100k": np.unique(np.round(np.logspace(0, 5, 25))).astype(int),

    # NEW (2) sign / unit confusion baseline
    "sign_split": np.arange(-100, 101, 10),

    # NEW (3) scientific notation scale test
    "scientific": np.logspace(-6, 6, 25),
}


# --------------------------------------------------------------------
# UNIT GROUPS (SOURCE OF TRUTH)
# --------------------------------------------------------------------

UNIT_GROUPS = {
    "length": [
        ("meter", "centimeter", lambda v: v * 100),
        ("meter", "millimeter", lambda v: v * 1000),
        ("meter", "kilometer", lambda v: v / 1000),
    ],
    "mass": [
        ("kilogram", "gram", lambda v: v * 1000),
        ("gram", "milligram", lambda v: v * 1000),
        ("kilogram", "ton", lambda v: v / 1000),
    ],
    "volume": [
        ("liter", "milliliter", lambda v: v * 1000),
        ("liter", "gallon", lambda v: v / 3.785),
    ],
    "time": [
        ("second", "millisecond", lambda v: v * 1000),
        ("minute", "second", lambda v: v * 60),
        ("hour", "minute", lambda v: v * 60),
    ],
}


# --------------------------------------------------------------------
# FORMATTING
# --------------------------------------------------------------------

def format_unit(v, unit):
    unit_form = unit if abs(v) == 1 else unit + "s"
    return f"{v:g} {unit_form}"


def range_texts(unit, range_name, values):
    """Strings fed to the embedding model for one (unit, range) cell."""
    if range_name == "scientific":
        return [f"{v:.0e} {unit}" for v in values]
    return [format_unit(v, unit) for v in values]


def range_labels(range_name, values):
    """Tick labels for one range."""
    if range_name == "scientific":
        return [f"{v:.0e}" for v in values]
    return [f"{v:g}" for v in values]


# --------------------------------------------------------------------
# BASIC SIMILARITIES
# --------------------------------------------------------------------

def numeric_similarity(unit, values, model):
    texts = [format_unit(v, unit) for v in values]
    emb = model.encode(texts, normalize_embeddings=True)
    return cosine_similarity(emb)


def digit_word_similarity(unit, digits, words, model):
    emb_digits = model.encode([f"{d} {unit}" for d in digits], normalize_embeddings=True)
    emb_words = model.encode([f"{w} {unit}" for w in words], normalize_embeddings=True)
    return cosine_similarity(emb_words, emb_digits)


# --------------------------------------------------------------------
# ALIGNMENT CURVE (CORRECT + CONSISTENT)
# --------------------------------------------------------------------

def alignment_curve(unit_a, unit_b, converter, model):

    values = np.logspace(-2, 3, 40)

    texts_a = [format_unit(v, unit_a) for v in values]
    texts_b = [format_unit(converter(v), unit_b) for v in values]

    emb_a = model.encode(texts_a, normalize_embeddings=True).astype(np.float32)
    emb_b = model.encode(texts_b, normalize_embeddings=True).astype(np.float32)

    # explicit normalization safety (IMPORTANT FIX)
    emb_a = emb_a / np.linalg.norm(emb_a, axis=1, keepdims=True)
    emb_b = emb_b / np.linalg.norm(emb_b, axis=1, keepdims=True)

    # cosine similarity per aligned pair
    curve = np.sum(emb_a * emb_b, axis=1)

    curve_plot = gaussian_filter1d(curve, sigma=0.8)

    return values, curve_plot


# Ranges with logarithmically spaced values: compared by log10 distance.
LOG_RANGES = {"log_1_100k", "scientific"}


def physical_distances(values, range_name):
    """Matrix of true distances |v_i - v_j| (in log10 space for LOG_RANGES)."""
    v = np.asarray(values, dtype=float)
    if range_name in LOG_RANGES:
        v = np.log10(v)
    # rounding lets float noise count as an exact tie
    return np.round(np.abs(v[:, None] - v[None, :]), 9)


def pairwise_accuracy(true_dist, score):
    """
    Share of candidate pairs ordered correctly (higher score = closer).
    Pairs with equal true distance are skipped.
    """
    true_dist = np.asarray(true_dist, dtype=float)
    score = np.asarray(score, dtype=float)

    i, j = np.triu_indices(len(true_dist), k=1)
    keep = true_dist[i] != true_dist[j]
    if not keep.any():
        return np.nan

    i_closer = true_dist[i] < true_dist[j]
    correct = np.where(i_closer, score[i] > score[j], score[i] < score[j])
    return float(np.mean(correct[keep]))


def ranking_metrics(sim, dist):
    """
    Measures whether embedding similarity preserves the ordering of true
    physical distances, from every item's point of view.

    Each item serves once as anchor and is excluded from its own candidates.
    Returns the mean Kendall tau-b and mean pairwise accuracy over anchors.
    """
    taus, accs = [], []

    for a in range(len(dist)):
        others = np.delete(np.arange(len(dist)), a)
        d, s = dist[a, others], sim[a, others]
        taus.append(kendalltau(d, -s).statistic)
        accs.append(pairwise_accuracy(d, s))

    return float(np.nanmean(taus)), float(np.nanmean(accs))


# --------------------------------------------------------------------
# PLOT HELPERS
# --------------------------------------------------------------------

def mask_lower(sim):
    """Blank the strictly lower triangle of a symmetric similarity matrix."""
    data = np.asarray(sim, dtype=float)
    if data.ndim != 2 or data.shape[0] != data.shape[1]:
        return data
    data = data.copy()
    data[np.tril_indices_from(data, k=-1)] = np.nan
    return data


def _triangle_cmap():
    cmap = plt.get_cmap("viridis").copy()
    cmap.set_bad(color="white", alpha=0.0)
    return cmap


def plot_matrix(sim, xt, yt, title, ax, ticks=None, triangle=False):

    data = mask_lower(sim) if triangle else np.asarray(sim, dtype=float)

    im = ax.imshow(
        data,
        origin="lower",
        cmap=_triangle_cmap(),
        vmin=0,
        vmax=1,
        interpolation="nearest",
        aspect="equal",
    )

    if title:
        ax.set_title(title, fontsize=9)

    if ticks is None:
        ticks = np.arange(len(xt))

    ax.set_xticks(ticks)
    ax.set_xticklabels(
        [xt[i] for i in ticks],
        rotation=90,
        fontsize=10,
    )

    ax.set_yticks(ticks)
    ax.set_yticklabels(
        [yt[i] for i in ticks],
        fontsize=10,
    )

    ax.tick_params(
        axis="both",
        which="both",
        length=2,
        width=0.5,
        pad=1,
    )

    return im


# --------------------------------------------------------------------
# SETUP
# --------------------------------------------------------------------

digits = [str(i) for i in range(11)] + ["100"]

words = [
    "zero","one","two","three","four",
    "five","six","seven","eight","nine","ten", "one-hundred"
]

units = ["meter", "kilogram", "liter", "second"]


# --------------------------------------------------------------------
# COMPUTE RESULTS
# --------------------------------------------------------------------
def run_benchmark(model_name, results):

    model_id = model_name.split("/")[-1]
    model_id = model_id.replace("-", "_")
    print("=" * 80)
    print(model_name)
    print("=" * 80)

    model = SentenceTransformer(
        model_name,
        trust_remote_code=True,
    ).float()

    numeric_results = {}
    digit_results = {}
    alignment_results = {}

    for unit in units:

        numeric_results[unit] = {}

        for name, values in RANGES.items():
            texts = range_texts(unit, name, values)
            emb = model.encode(texts, normalize_embeddings=True)

            # similarity matrix (your existing visualization stays unchanged)
            sim = cosine_similarity(emb)

            # ranking metrics: every item serves once as anchor
            dist = physical_distances(values, name)
            tau, pair_acc = ranking_metrics(sim, dist)

            numeric_results[unit][name] = (sim, values, tau, pair_acc)

        digit_results[unit] = digit_word_similarity(unit, digits, words, model)


    # alignment curves (ONLY ONE SOURCE OF TRUTH)
    alignment_results = {}

    for group, pairs in UNIT_GROUPS.items():

        alignment_results[group] = []

        for ua, ub, conv in pairs:

            vals, curve = alignment_curve(ua, ub, conv, model)

            alignment_results[group].append(
                (ua, ub, vals, curve)
            )
    fig, axes = plt.subplots(
        2,
        2,
        figsize=(7.5, 6),
    )

    titles = {
        "length": "Length",
        "mass": "Mass",
        "volume": "Volume",
        "time": "Time",
    }

    axis_map = {
        "length": axes[0,0],
        "mass": axes[0,1],
        "volume": axes[1,0],
        "time": axes[1,1],
    }

    styles = ["-", "--", "-.", ":"]

# Figure 3: conversion plots
    FS = 14  # font size for all text in the conversion plots

    for group, curves in alignment_results.items():

        ax = axis_map[group]

        for i, (ua, ub, values, curve) in enumerate(curves):

            ax.plot(
                values,
                curve,
                linewidth=2,
                linestyle=styles[i],
                label=f"{ua} \u2194 {ub}",
            )

        ax.set_xscale("log")

        # headroom above 1.0 so the legend never overlaps the curves
        ax.set_ylim(0.4, 1.25)
        ax.set_yticks(np.arange(0.4, 1.01, 0.1))

        ax.set_title(titles[group], fontsize=FS, fontweight="bold")

        ax.set_xlabel("Physical value", fontsize=FS)
        ax.set_ylabel("Cosine similarity", fontsize=FS)

        ax.tick_params(axis="both", which="both", labelsize=FS)

        ax.grid(alpha=0.25)

        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)

        ax.legend(
            frameon=False,
            fontsize=FS,
            loc="upper right",
            handlelength=1.6,
            labelspacing=0.25,
            borderaxespad=0.2,
        )

    plt.tight_layout()

    plt.savefig(
        os.path.join(PDF_DIR, f"{model_id}_alignment_overview.pdf"),
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()

    # --------------------------------------------------------------------
    # INDIVIDUAL PDFs
    # --------------------------------------------------------------------

    for unit in units:

        for name, (sim, values, _, _) in numeric_results[unit].items():

            plt.figure(figsize=(6,5))
            plt.imshow(
                mask_lower(sim),
                origin="lower",
                cmap=_triangle_cmap(),
                vmin=0,
                vmax=1,
            )

            labels = range_labels(name, values)
            ticks = np.arange(len(values))

            plt.xticks(ticks, labels, rotation=90, fontsize=6)
            plt.yticks(ticks, labels, fontsize=6)

            plt.title(f"{unit} ({name})")
            plt.colorbar()

            plt.tight_layout()
            plt.savefig(
            os.path.join(PDF_DIR, f"{model_id}_{unit}_{name}.pdf"),
            bbox_inches="tight",
            )
            plt.close()

        plt.figure(figsize=(6,5))
        plt.imshow(digit_results[unit], origin="lower", cmap="viridis", vmin=0, vmax=1)

        plt.xticks(range(len(digits)), digits, rotation=90, fontsize=6)
        plt.yticks(range(len(words)), words, fontsize=6)

        plt.title(f"{unit} digits vs words")
        plt.colorbar()

        plt.tight_layout()
        plt.savefig(
        os.path.join(PDF_DIR, f"{model_id}_{unit}_digits_words.pdf"),
        bbox_inches="tight",
            )
        plt.close()


    # --------------------------------------------------------------------
    # OVERVIEW FIGURE
    # --------------------------------------------------------------------

    cols = len(RANGES) + 1
    range_names = [
    "local_0_10",
    "medium_0_1000",
    "log_1_100k",
    "sign_split",
    "scientific",
    ]


    column_titles = [
    "Local",
    "Medium",
    "Log",
    "Sign",
    "Scientific",
    "Digits \u2194 Words",
    ]

    import matplotlib.gridspec as gridspec

    fig = plt.figure(figsize=(2.2 * cols, 2.0 * len(units)))

    gs = gridspec.GridSpec(
        nrows=len(units),
        ncols=cols,
        figure=fig,
        width_ratios=[1, 1, 1, 1, 1.0, 2.0],  # <-- IMPORTANT CHANGE
        wspace=0.02,
        hspace=0.12,
    )

    axes = np.empty((len(units), cols), dtype=object)

    for r in range(len(units)):
        for c in range(cols):
            axes[r, c] = fig.add_subplot(gs[r, c])

    fig.subplots_adjust(
        left=0.11,
        right=0.995,
        top=0.92,
        bottom=0.08,
        wspace=0.02,
        hspace=0.08,
    )

    # --------------------------------------------------------
    # Column headers
    # --------------------------------------------------------

    for c, title in enumerate(column_titles):
        axes[0, c].set_title(
            title,
            fontsize=11,
            fontweight="bold",
            pad=6,
        )

    # --------------------------------------------------------
    # Rows
    # --------------------------------------------------------
    row_labels = {
    "meter": "meter",
    "kilogram": "kilogram",
    "liter": "liter",
    "second": "second",
    }
    for r, unit in enumerate(units):

        # row label
        axes[r, 0].set_ylabel(
            row_labels[unit],
            fontsize=11,
            fontweight="bold",
            rotation=0,
            labelpad=35,
            va="center",
        )

        # numeric benchmarks
        for c, name in enumerate(range_names):

            sim, values, _, _ = numeric_results[unit][name]
            if len(values) == 21:
                ticks = [0, 5, 10, 15, 20]
            elif len(values) == 25:
                ticks = [0, 6, 12, 18, 24]
            else:
                ticks = np.arange(len(values))

            labels = range_labels(name, values)

            plot_matrix(
                sim,
                labels,
                labels,
                "",
                axes[r, c],
                ticks=ticks,
                triangle=True,   # symmetric -> upper triangle only
            )

        # digits <-> words (asymmetric -> full matrix)
        plot_matrix(
            digit_results[unit],
            [str(d) for d in digits],
            words,
            "",
            axes[r, len(range_names)],
        )

    # --------------------------------------------------------
    # Remove redundant tick labels
    # --------------------------------------------------------

    for r in range(len(units)):
        for c in range(cols):

            ax = axes[r, c]

            # digits column: keep labels
            if c == len(range_names):
                continue

            # only bottom row keeps x labels
            if r != len(units) - 1:
                ax.set_xticklabels([])

            # only first column keeps y labels
            #if c != 0:
            ax.set_yticklabels([])

    plt.savefig(
        os.path.join(PDF_DIR, f"{model_id}_embedding_overview.pdf"),
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()

    print(f"\n=== {model_id} ===")

    for unit in units:
        print(f"\n[{unit}]")

        for name in RANGES.keys():
            _, _, tau, acc = numeric_results[unit][name]
            print(f"{name:15s}  \u03c4={tau:.3f}   pairwise={acc:.3f}")

            results.append({
                "model": model_id,
                "unit": unit,
                "range": name,
                "kendall": tau,
                "pairwise": acc,
            })

    df = pd.DataFrame(results)
    summary = df.groupby("model").agg(
    kendall_mean=("kendall", "mean"),
    pairwise_mean=("pairwise", "mean"),
    kendall_std=("kendall", "std"),
    pairwise_std=("pairwise", "std"),
    ).reset_index()
    df.to_csv(os.path.join(CSV_DIR, f"{model_id}_benchmark_full.csv"), index=False)
    summary.to_csv(os.path.join(CSV_DIR, f"{model_id}_benchmark_summary.csv"), index=False)
    del model
    gc.collect()
    torch.cuda.empty_cache()

def run_measurement(models):
    """Run the measurement benchmark over a list of model names."""
    results = []
    for model_name in models:
        run_benchmark(model_name, results)
    return results

### Run: baseline models

In [ ]:
# Baseline models (the original paper set + Qwen3 4B / 8B)
MODELS = [
    "sentence-transformers/all-MiniLM-L6-v2",
    "sentence-transformers/all-mpnet-base-v2",
    "intfloat/e5-large-v2",
    "BAAI/bge-large-en-v1.5",
    "nomic-ai/nomic-embed-text-v1.5",
    "Qwen/Qwen3-Embedding-0.6B",
    "Qwen/Qwen3-Embedding-4B",
    "Qwen/Qwen3-Embedding-8B",
]

run_measurement(MODELS)

================================================================================
sentence-transformers/all-MiniLM-L6-v2
================================================================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

=== all_MiniLM_L6_v2 ===

[meter]
local_0_10       τ=0.436   pairwise=0.721
medium_0_1000    τ=0.474   pairwise=0.740
log_1_100k       τ=0.357   pairwise=0.678
sign_split       τ=0.433   pairwise=0.719
scientific       τ=0.292   pairwise=0.647

[kilogram]
local_0_10       τ=0.398   pairwise=0.701
medium_0_1000    τ=0.419   pairwise=0.712
log_1_100k       τ=0.236   pairwise=0.618
sign_split       τ=0.444   pairwise=0.725
scientific       τ=0.244   pairwise=0.624

[liter]
local_0_10       τ=0.444   pairwise=0.725
medium_0_1000    τ=0.489   pairwise=0.748
log_1_100k       τ=0.309   pairwise=0.654
sign_split       τ=0.435   pairwise=0.720
scientific       τ=0.253   pairwise=0.628

[second]
local_0_10       τ=0.360   pairwise=0.683
medium_0_1000    τ=0.488   pairwise=0.747
log_1_100k       τ=0.445   pairwise=0.723
sign_split       τ=0.472   pairwise=0.738
scientific       τ=0.380   pairwise=0.692
================================================================================
sentence-transformers/all-mpnet-base-v2
================================================================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/11.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

=== all_mpnet_base_v2 ===

[meter]
local_0_10       τ=0.353   pairwise=0.679
medium_0_1000    τ=0.408   pairwise=0.707
log_1_100k       τ=0.564   pairwise=0.782
sign_split       τ=0.569   pairwise=0.788
scientific       τ=0.242   pairwise=0.622

[kilogram]
local_0_10       τ=0.276   pairwise=0.640
medium_0_1000    τ=0.506   pairwise=0.757
log_1_100k       τ=0.430   pairwise=0.715
sign_split       τ=0.583   pairwise=0.796
scientific       τ=0.298   pairwise=0.651

[liter]
local_0_10       τ=0.431   pairwise=0.718
medium_0_1000    τ=0.505   pairwise=0.756
log_1_100k       τ=0.555   pairwise=0.778
sign_split       τ=0.553   pairwise=0.780
scientific       τ=0.237   pairwise=0.620

[second]
local_0_10       τ=0.291   pairwise=0.647
medium_0_1000    τ=0.504   pairwise=0.756
log_1_100k       τ=0.594   pairwise=0.797
sign_split       τ=0.502   pairwise=0.754
scientific       τ=0.247   pairwise=0.625
================================================================================
intfloat/e5-large-v2
================================================================================

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/67.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/616 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.34GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/201 [00:00<?, ?B/s]

=== e5_large_v2 ===

[meter]
local_0_10       τ=0.285   pairwise=0.644
medium_0_1000    τ=0.470   pairwise=0.738
log_1_100k       τ=0.581   pairwise=0.791
sign_split       τ=0.456   pairwise=0.731
scientific       τ=0.337   pairwise=0.671

[kilogram]
local_0_10       τ=0.300   pairwise=0.652
medium_0_1000    τ=0.469   pairwise=0.738
log_1_100k       τ=0.553   pairwise=0.776
sign_split       τ=0.419   pairwise=0.712
scientific       τ=0.305   pairwise=0.655

[liter]
local_0_10       τ=0.274   pairwise=0.639
medium_0_1000    τ=0.446   pairwise=0.726
log_1_100k       τ=0.490   pairwise=0.745
sign_split       τ=0.343   pairwise=0.674
scientific       τ=0.312   pairwise=0.658

[second]
local_0_10       τ=0.230   pairwise=0.617
medium_0_1000    τ=0.493   pairwise=0.749
log_1_100k       τ=0.582   pairwise=0.791
sign_split       τ=0.397   pairwise=0.701
scientific       τ=0.347   pairwise=0.675
================================================================================
BAAI/bge-large-en-v1.5
================================================================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/94.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/779 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.34GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

=== bge_large_en_v1.5 ===

[meter]
local_0_10       τ=0.285   pairwise=0.645
medium_0_1000    τ=0.435   pairwise=0.720
log_1_100k       τ=0.368   pairwise=0.684
sign_split       τ=0.223   pairwise=0.613
scientific       τ=0.353   pairwise=0.679

[kilogram]
local_0_10       τ=0.284   pairwise=0.644
medium_0_1000    τ=0.342   pairwise=0.673
log_1_100k       τ=0.317   pairwise=0.659
sign_split       τ=0.226   pairwise=0.615
scientific       τ=0.393   pairwise=0.699

[liter]
local_0_10       τ=0.363   pairwise=0.684
medium_0_1000    τ=0.450   pairwise=0.728
log_1_100k       τ=0.304   pairwise=0.652
sign_split       τ=0.198   pairwise=0.600
scientific       τ=0.333   pairwise=0.669

[second]
local_0_10       τ=0.290   pairwise=0.647
medium_0_1000    τ=0.479   pairwise=0.743
log_1_100k       τ=0.516   pairwise=0.758
sign_split       τ=0.415   pairwise=0.711
scientific       τ=0.461   pairwise=0.733
================================================================================
nomic-ai/nomic-embed-text-v1.5
================================================================================

modules.json:   0%|          | 0.00/255 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/140 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/71.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/58.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

configuration_hf_nomic_bert.py:   0%|          | 0.00/1.96k [00:00<?, ?B/s]

[transformers] A new version of the following files was downloaded from https://huggingface.co/nomic-ai/nomic-bert-2048:
- configuration_hf_nomic_bert.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

modeling_hf_nomic_bert.py:   0%|          | 0.00/104k [00:00<?, ?B/s]

[transformers] A new version of the following files was downloaded from https://huggingface.co/nomic-ai/nomic-bert-2048:
- modeling_hf_nomic_bert.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors: reconstructing file:   0%|          |  0.00B /  547MB

model.safetensors: downloading bytes:           |  0.00B

WARNING:transformers_modules.nomic_hyphen_ai.nomic_hyphen_bert_hyphen_2048.7710840340a098cfb869c4f65e87cf2b1b70caca.modeling_hf_nomic_bert:<All keys matched successfully>

tokenizer_config.json:   0%|          | 0.00/1.19k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/695 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/286 [00:00<?, ?B/s]

[transformers] Detected the usage of `get_extended_attention_mask`: This function is deprecated and will be removed in v5.12.0. Please use the new API in `transformers.masking_utils`

=== nomic_embed_text_v1.5 ===

[meter]
local_0_10       τ=0.429   pairwise=0.717
medium_0_1000    τ=0.394   pairwise=0.699
log_1_100k       τ=0.267   pairwise=0.634
sign_split       τ=0.162   pairwise=0.583
scientific       τ=0.135   pairwise=0.568

[kilogram]
local_0_10       τ=0.385   pairwise=0.695
medium_0_1000    τ=0.409   pairwise=0.708
log_1_100k       τ=0.206   pairwise=0.603
sign_split       τ=0.203   pairwise=0.603
scientific       τ=0.121   pairwise=0.561

[liter]
local_0_10       τ=0.454   pairwise=0.730
medium_0_1000    τ=0.432   pairwise=0.719
log_1_100k       τ=0.227   pairwise=0.614
sign_split       τ=0.169   pairwise=0.586
scientific       τ=0.131   pairwise=0.566

[second]
local_0_10       τ=0.329   pairwise=0.667
medium_0_1000    τ=0.421   pairwise=0.713
log_1_100k       τ=0.243   pairwise=0.622
sign_split       τ=0.115   pairwise=0.559
scientific       τ=0.163   pairwise=0.582
================================================================================
Qwen/Qwen3-Embedding-0.6B
================================================================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/17.2k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/727 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.19GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/310 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/9.71k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

config.json:   0%|          | 0.00/313 [00:00<?, ?B/s]

=== Qwen3_Embedding_0.6B ===

[meter]
local_0_10       τ=0.260   pairwise=0.632
medium_0_1000    τ=0.190   pairwise=0.597
log_1_100k       τ=0.507   pairwise=0.754
sign_split       τ=0.494   pairwise=0.750
scientific       τ=0.520   pairwise=0.763

[kilogram]
local_0_10       τ=0.190   pairwise=0.597
medium_0_1000    τ=0.213   pairwise=0.608
log_1_100k       τ=0.478   pairwise=0.739
sign_split       τ=0.420   pairwise=0.712
scientific       τ=0.512   pairwise=0.758

[liter]
local_0_10       τ=0.098   pairwise=0.550
medium_0_1000    τ=0.171   pairwise=0.587
log_1_100k       τ=0.445   pairwise=0.722
sign_split       τ=0.448   pairwise=0.727
scientific       τ=0.534   pairwise=0.770

[second]
local_0_10       τ=0.169   pairwise=0.586
medium_0_1000    τ=0.385   pairwise=0.695
log_1_100k       τ=0.658   pairwise=0.829
sign_split       τ=0.460   pairwise=0.733
scientific       τ=0.535   pairwise=0.771
================================================================================
Qwen/Qwen3-Embedding-4B
================================================================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/17.3k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/727 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/30.4k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/7.26k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

config.json:   0%|          | 0.00/313 [00:00<?, ?B/s]

=== Qwen3_Embedding_4B ===

[meter]
local_0_10       τ=0.370   pairwise=0.688
medium_0_1000    τ=0.218   pairwise=0.610
log_1_100k       τ=0.629   pairwise=0.815
sign_split       τ=0.455   pairwise=0.731
scientific       τ=0.422   pairwise=0.713

[kilogram]
local_0_10       τ=0.206   pairwise=0.605
medium_0_1000    τ=0.201   pairwise=0.602
log_1_100k       τ=0.363   pairwise=0.682
sign_split       τ=0.356   pairwise=0.681
scientific       τ=0.433   pairwise=0.719

[liter]
local_0_10       τ=0.305   pairwise=0.655
medium_0_1000    τ=0.230   pairwise=0.617
log_1_100k       τ=0.526   pairwise=0.763
sign_split       τ=0.386   pairwise=0.696
scientific       τ=0.498   pairwise=0.752

[second]
local_0_10       τ=0.352   pairwise=0.678
medium_0_1000    τ=0.313   pairwise=0.659
log_1_100k       τ=0.678   pairwise=0.839
sign_split       τ=0.372   pairwise=0.689
scientific       τ=0.589   pairwise=0.797
================================================================================
Qwen/Qwen3-Embedding-8B
================================================================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/17.3k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/729 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/30.4k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/7.26k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/313 [00:00<?, ?B/s]

=== Qwen3_Embedding_8B ===

[meter]
local_0_10       τ=0.371   pairwise=0.688
medium_0_1000    τ=0.284   pairwise=0.644
log_1_100k       τ=0.460   pairwise=0.730
sign_split       τ=0.419   pairwise=0.712
scientific       τ=0.344   pairwise=0.674

[kilogram]
local_0_10       τ=0.320   pairwise=0.662
medium_0_1000    τ=0.264   pairwise=0.634
log_1_100k       τ=0.243   pairwise=0.622
sign_split       τ=0.419   pairwise=0.712
scientific       τ=0.335   pairwise=0.669

[liter]
local_0_10       τ=0.276   pairwise=0.640
medium_0_1000    τ=0.341   pairwise=0.673
log_1_100k       τ=0.434   pairwise=0.717
sign_split       τ=0.448   pairwise=0.727
scientific       τ=0.436   pairwise=0.720

[second]
local_0_10       τ=0.400   pairwise=0.703
medium_0_1000    τ=0.335   pairwise=0.670
log_1_100k       τ=0.460   pairwise=0.730
sign_split       τ=0.453   pairwise=0.729
scientific       τ=0.406   pairwise=0.705

[{'model': 'all_MiniLM_L6_v2',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.4355710479064466,
  'pairwise': 0.7205837944479806},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.47415052385059236,
  'pairwise': 0.7403744196887343},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.3568979452856657,
  'pairwise': 0.6784922266139658},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.4332287063519037,
  'pairwise': 0.719236740247209},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.2915218797714784,
  'pairwise': 0.6474900849775093},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.3975477080767265,
  'pairwise': 0.7013531503571028},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.41914333416127925,
  'pairwise': 0.712426324277577},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.23570324741931428,
  'pairwise': 0.6178772068511199},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.4441065596128687,
  'pairwise': 0.7245973756908551},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.24425845693650758,
  'pairwise': 0.6235548930360396},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.44412234658294364,
  'pairwise': 0.7248743227128787},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.4887755504720519,
  'pairwise': 0.7477332110524193},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.308507944113991,
  'pairwise': 0.654305138339921},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.4354484745729798,
  'pairwise': 0.7204566325780993},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.25308864791760405,
  'pairwise': 0.628038553164755},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.3604455284421588,
  'pairwise': 0.6825411981577598},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.48758311048501907,
  'pairwise': 0.7470383790518077},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.4450186260935836,
  'pairwise': 0.7225549407114623},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.4715134434906518,
  'pairwise': 0.7384736669456304},
 {'model': 'all_MiniLM_L6_v2',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.3795654461436246,
  'pairwise': 0.6920640160361806},
 {'model': 'all_mpnet_base_v2',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.35315236675127043,
  'pairwise': 0.6787536627538284},
 {'model': 'all_mpnet_base_v2',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.4080153298782263,
  'pairwise': 0.706812997192557},
 {'model': 'all_mpnet_base_v2',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.5638755282644956,
  'pairwise': 0.7819915678524374},
 {'model': 'all_mpnet_base_v2',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.5685066577355542,
  'pairwise': 0.7878662007029886},
 {'model': 'all_mpnet_base_v2',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.24179015469529472,
  'pairwise': 0.6222446424710418},
 {'model': 'all_mpnet_base_v2',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.2756589043334256,
  'pairwise': 0.6395998474633148},
 {'model': 'all_mpnet_base_v2',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.5058882999345866,
  'pairwise': 0.75657985883259},
 {'model': 'all_mpnet_base_v2',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.4296373521372746,
  'pairwise': 0.7148548089591569},
 {'model': 'all_mpnet_base_v2',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.5834609245919646,
  'pairwise': 0.7955576742885249},
 {'model': 'all_mpnet_base_v2',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.29812413431145646,
  'pairwise': 0.6506096375528252},
 {'model': 'all_mpnet_base_v2',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.430608345424457,
  'pairwise': 0.7181272486145724},
 {'model': 'all_mpnet_base_v2',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.5051862472386577,
  'pairwise': 0.7561274516439987},
 {'model': 'all_mpnet_base_v2',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.5554576209502191,
  'pairwise': 0.7777765480895917},
 {'model': 'all_mpnet_base_v2',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.5526372634415746,
  'pairwise': 0.779762330659361},
 {'model': 'all_mpnet_base_v2',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.23694706543981578,
  'pairwise': 0.6197180219029231},
 {'model': 'all_mpnet_base_v2',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.29104127416144115,
  'pairwise': 0.6474662916509166},
 {'model': 'all_mpnet_base_v2',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.5044650333070856,
  'pairwise': 0.7556538056809974},
 {'model': 'all_mpnet_base_v2',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.5943050455632664,
  'pairwise': 0.7972036890645586},
 {'model': 'all_mpnet_base_v2',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.5019995098489604,
  'pairwise': 0.7541843480877309},
 {'model': 'all_mpnet_base_v2',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.24717994881811356,
  'pairwise': 0.624879248506832},
 {'model': 'e5_large_v2',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.2852969281258944,
  'pairwise': 0.6444766761854551},
 {'model': 'e5_large_v2',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.4699303352948113,
  'pairwise': 0.7379012464415751},
 {'model': 'e5_large_v2',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.5809885612216925,
  'pairwise': 0.7905538866930171},
 {'model': 'e5_large_v2',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.4556699270060002,
  'pairwise': 0.7306543236927824},
 {'model': 'e5_large_v2',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.33718281752368,
  'pairwise': 0.6705449416742343},
 {'model': 'e5_large_v2',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.2999312162913454,
  'pairwise': 0.651843815075474},
 {'model': 'e5_large_v2',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.4690741133873361,
  'pairwise': 0.7375480412067735},
 {'model': 'e5_large_v2',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.5525638090045137,
  'pairwise': 0.7763320158102767},
 {'model': 'e5_large_v2',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.41905284232796614,
  'pairwise': 0.712078118884986},
 {'model': 'e5_large_v2',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.30540106940009104,
  'pairwise': 0.6545597438535726},
 {'model': 'e5_large_v2',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.2735951701426984,
  'pairwise': 0.6385383940434328},
 {'model': 'e5_large_v2',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.44614147764486056,
  'pairwise': 0.725889881078637},
 {'model': 'e5_large_v2',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.4896647317488836,
  'pairwise': 0.7448822134387352},
 {'model': 'e5_large_v2',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.34328711898444897,
  'pairwise': 0.6736448951024815},
 {'model': 'e5_large_v2',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.31187549948184623,
  'pairwise': 0.6578464643461349},
 {'model': 'e5_large_v2',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.23028567323219667,
  'pairwise': 0.6165244799496212},
 {'model': 'e5_large_v2',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.49277723274178686,
  'pairwise': 0.7494718350671414},
 {'model': 'e5_large_v2',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.5824225671852293,
  'pairwise': 0.7912632411067194},
 {'model': 'e5_large_v2',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.39725236622598664,
  'pairwise': 0.701052822232906},
 {'model': 'e5_large_v2',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.34674616728592933,
  'pairwise': 0.6753250353899012},
 {'model': 'bge_large_en_v1.5',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.2852306223916711,
  'pairwise': 0.6446663240090595},
 {'model': 'bge_large_en_v1.5',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.43496538100904725,
  'pairwise': 0.7204829034264199},
 {'model': 'bge_large_en_v1.5',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.3676252156217876,
  'pairwise': 0.6838571805006589},
 {'model': 'bge_large_en_v1.5',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.22309790825885764,
  'pairwise': 0.6133580728150505},
 {'model': 'bge_large_en_v1.5',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.3531815893150349,
  'pairwise': 0.6785727091255069},
 {'model': 'bge_large_en_v1.5',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.28361563925593053,
  'pairwise': 0.6438026336665533},
 {'model': 'bge_large_en_v1.5',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.3416926180028654,
  'pairwise': 0.6733159043176687},
 {'model': 'bge_large_en_v1.5',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.31716831871140766,
  'pairwise': 0.6586176548089593},
 {'model': 'bge_large_en_v1.5',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.22635825751730343,
  'pairwise': 0.6148602438699862},
 {'model': 'bge_large_en_v1.5',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.39269287715216317,
  'pairwise': 0.698521515238443},
 {'model': 'bge_large_en_v1.5',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.3632505201096765,
  'pairwise': 0.6840973542871922},
 {'model': 'bge_large_en_v1.5',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.4497183182664172,
  'pairwise': 0.7279691037046632},
 {'model': 'bge_large_en_v1.5',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.30383235272311193,
  'pairwise': 0.6519483530961792},
 {'model': 'bge_large_en_v1.5',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.1979463453990784,
  'pairwise': 0.600480689173543},
 {'model': 'bge_large_en_v1.5',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.3333573617318138,
  'pairwise': 0.6686031562665693},
 {'model': 'bge_large_en_v1.5',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.28966194677267076,
  'pairwise': 0.6468408141513159},
 {'model': 'bge_large_en_v1.5',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.47890123218967806,
  'pairwise': 0.742873820783505},
 {'model': 'bge_large_en_v1.5',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.5157311535619159,
  'pairwise': 0.7579051383399209},
 {'model': 'bge_large_en_v1.5',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.41533956336647776,
  'pairwise': 0.7106323084646873},
 {'model': 'bge_large_en_v1.5',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.4613833415725266,
  'pairwise': 0.7330088798114169},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.428948321063823,
  'pairwise': 0.7172175126894488},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.39363106957752564,
  'pairwise': 0.6994409170064395},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.26725743396243634,
  'pairwise': 0.6336342555994731},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.16229866990122976,
  'pairwise': 0.5826281827427332},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.1345047211334163,
  'pairwise': 0.5681416557026506},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.38497642156910433,
  'pairwise': 0.6950469119911634},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.40947777825156007,
  'pairwise': 0.7075215582302233},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.20636522791236828,
  'pairwise': 0.6031768115942029},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.20281053759781367,
  'pairwise': 0.6030930952907957},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.12100915405123444,
  'pairwise': 0.5613115106760017},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.4537852422051977,
  'pairwise': 0.7297763878558848},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.4317122941008449,
  'pairwise': 0.718729852182387},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.22723216047479716,
  'pairwise': 0.6136089591567853},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.16889878223189286,
  'pairwise': 0.5859713088749217},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.13087288071178782,
  'pairwise': 0.5662474237951535},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.32949502003562137,
  'pairwise': 0.6668754667831996},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.4209548268677502,
  'pairwise': 0.7134901498260123},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.2434872118964374,
  'pairwise': 0.6217480895915678},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.11529787859890561,
  'pairwise': 0.5586753885633408},
 {'model': 'nomic_embed_text_v1.5',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.16274420219054522,
  'pairwise': 0.5823233805460226},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.26039405022208506,
  'pairwise': 0.6318495432365736},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.1899784887165375,
  'pairwise': 0.5965240349429302},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.5070381340429653,
  'pairwise': 0.7535599472990778},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.49375506300064637,
  'pairwise': 0.7496887770388192},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.5195605835911373,
  'pairwise': 0.7626455880285189},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.19035770072052113,
  'pairwise': 0.5966505598072793},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.2131477342679164,
  'pairwise': 0.6081656442521598},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.47775487375923753,
  'pairwise': 0.7389143610013176},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.4200857737624706,
  'pairwise': 0.7123509955364745},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.5115394656848217,
  'pairwise': 0.7583872978018829},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.0981100856216479,
  'pairwise': 0.5497514708407459},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.17107636051860148,
  'pairwise': 0.5868920660790483},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.4447161342773003,
  'pairwise': 0.7223973649538867},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.4480375060430826,
  'pairwise': 0.7265224417600121},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.5343877311559606,
  'pairwise': 0.7700812119076801},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.16948277339611217,
  'pairwise': 0.58578965419609},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.384747145401843,
  'pairwise': 0.6948159509601994},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.6580752676292653,
  'pairwise': 0.829089855072464},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.46043922828259054,
  'pairwise': 0.7329135390183461},
 {'model': 'Qwen3_Embedding_0.6B',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.5352825586263811,
  'pairwise': 0.7705418196220153},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.3702544431595789,
  'pairwise': 0.6878470409498719},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.21764627812982193,
  'pairwise': 0.610149885804874},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.6290923930378508,
  'pairwise': 0.8145997364953886},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.4554257250406762,
  'pairwise': 0.7306638619170065},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.42170318514928584,
  'pairwise': 0.7130382020445508},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.20625556049270577,
  'pairwise': 0.6045247953769025},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.20061686272709528,
  'pairwise': 0.6016431462040635},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.36326580585299645,
  'pairwise': 0.6816716732542819},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.356208607641314,
  'pairwise': 0.6805616613235802},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.43296008548670706,
  'pairwise': 0.7187903054663173},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.3048064366249549,
  'pairwise': 0.6547239640909862},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.2298032019044068,
  'pairwise': 0.6165497135412024},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.5264742198278122,
  'pairwise': 0.7632859025032939},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.38635639438008357,
  'pairwise': 0.6956714137797553},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.4977258668900907,
  'pairwise': 0.7515324644114071},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.35171301965563895,
  'pairwise': 0.6783221525850989},
 {'model': 'Qwen3_Embedding_4B',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.313235667245216,
  'pairwise': 0.6586342621066131},

### Run: extended models

Add model names to `NEW_MODELS` to extend the paper.

#### PT1

In [ ]:
# Extended run: add model names here to extend the paper.
NEW_MODELS_1 = [
    "sentence-transformers/LaBSE",
    "sentence-transformers/paraphrase-multilingual-mpnet-base-v2",
    "intfloat/multilingual-e5-base",
    "intfloat/multilingual-e5-large",
    "intfloat/multilingual-e5-large-instruct",
    "BAAI/bge-m3",
    "google/embeddinggemma-300m",
]

run_measurement(NEW_MODELS_1)

================================================================================
sentence-transformers/LaBSE
================================================================================

modules.json:   0%|          | 0.00/461 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.02k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/804 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.88GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/397 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/5.22M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.62M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

2_Dense/model.safetensors: reconstructing file:   0%|          |  0.00B / 2.36MB

2_Dense/model.safetensors: downloading bytes:           |  0.00B

=== LaBSE ===

[meter]
local_0_10       τ=0.280   pairwise=0.642
medium_0_1000    τ=0.562   pairwise=0.785
log_1_100k       τ=0.625   pairwise=0.813
sign_split       τ=0.511   pairwise=0.759
scientific       τ=0.447   pairwise=0.726

[kilogram]
local_0_10       τ=0.322   pairwise=0.663
medium_0_1000    τ=0.513   pairwise=0.760
log_1_100k       τ=0.490   pairwise=0.745
sign_split       τ=0.424   pairwise=0.715
scientific       τ=0.455   pairwise=0.730

[liter]
local_0_10       τ=0.308   pairwise=0.656
medium_0_1000    τ=0.571   pairwise=0.789
log_1_100k       τ=0.410   pairwise=0.705
sign_split       τ=0.475   pairwise=0.740
scientific       τ=0.471   pairwise=0.738

[second]
local_0_10       τ=0.259   pairwise=0.631
medium_0_1000    τ=0.455   pairwise=0.730
log_1_100k       τ=0.494   pairwise=0.747
sign_split       τ=0.431   pairwise=0.718
scientific       τ=0.421   pairwise=0.713
================================================================================
sentence-transformers/paraphrase-multilingual-mpnet-base-v2
================================================================================

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/5.12k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/723 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.11GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/402 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

=== paraphrase_multilingual_mpnet_base_v2 ===

[meter]
local_0_10       τ=0.480   pairwise=0.743
medium_0_1000    τ=0.470   pairwise=0.738
log_1_100k       τ=0.250   pairwise=0.625
sign_split       τ=0.042   pairwise=0.521
scientific       τ=0.129   pairwise=0.566

[kilogram]
local_0_10       τ=0.456   pairwise=0.731
medium_0_1000    τ=0.366   pairwise=0.685
log_1_100k       τ=0.359   pairwise=0.679
sign_split       τ=0.037   pairwise=0.519
scientific       τ=0.114   pairwise=0.558

[liter]
local_0_10       τ=0.370   pairwise=0.687
medium_0_1000    τ=0.341   pairwise=0.673
log_1_100k       τ=0.264   pairwise=0.632
sign_split       τ=0.031   pairwise=0.516
scientific       τ=0.140   pairwise=0.571

[second]
local_0_10       τ=0.374   pairwise=0.689
medium_0_1000    τ=0.408   pairwise=0.706
log_1_100k       τ=0.323   pairwise=0.662
sign_split       τ=0.067   pairwise=0.534
scientific       τ=0.130   pairwise=0.566
================================================================================
intfloat/multilingual-e5-base
================================================================================

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/179k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.11GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/418 [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

=== multilingual_e5_base ===

[meter]
local_0_10       τ=0.300   pairwise=0.652
medium_0_1000    τ=0.369   pairwise=0.687
log_1_100k       τ=0.426   pairwise=0.713
sign_split       τ=0.374   pairwise=0.689
scientific       τ=0.354   pairwise=0.679

[kilogram]
local_0_10       τ=0.309   pairwise=0.657
medium_0_1000    τ=0.411   pairwise=0.708
log_1_100k       τ=0.345   pairwise=0.673
sign_split       τ=0.350   pairwise=0.677
scientific       τ=0.359   pairwise=0.681

[liter]
local_0_10       τ=0.295   pairwise=0.649
medium_0_1000    τ=0.397   pairwise=0.701
log_1_100k       τ=0.363   pairwise=0.682
sign_split       τ=0.341   pairwise=0.673
scientific       τ=0.338   pairwise=0.671

[second]
local_0_10       τ=0.212   pairwise=0.608
medium_0_1000    τ=0.386   pairwise=0.696
log_1_100k       τ=0.486   pairwise=0.743
sign_split       τ=0.296   pairwise=0.650
scientific       τ=0.372   pairwise=0.688
================================================================================
intfloat/multilingual-e5-large
================================================================================

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/160k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/690 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.24GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/418 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/201 [00:00<?, ?B/s]

=== multilingual_e5_large ===

[meter]
local_0_10       τ=0.300   pairwise=0.652
medium_0_1000    τ=0.453   pairwise=0.729
log_1_100k       τ=0.471   pairwise=0.735
sign_split       τ=0.442   pairwise=0.724
scientific       τ=0.392   pairwise=0.698

[kilogram]
local_0_10       τ=0.271   pairwise=0.637
medium_0_1000    τ=0.416   pairwise=0.711
log_1_100k       τ=0.365   pairwise=0.683
sign_split       τ=0.421   pairwise=0.713
scientific       τ=0.429   pairwise=0.717

[liter]
local_0_10       τ=0.297   pairwise=0.651
medium_0_1000    τ=0.411   pairwise=0.708
log_1_100k       τ=0.466   pairwise=0.733
sign_split       τ=0.419   pairwise=0.712
scientific       τ=0.385   pairwise=0.694

[second]
local_0_10       τ=0.180   pairwise=0.591
medium_0_1000    τ=0.463   pairwise=0.734
log_1_100k       τ=0.405   pairwise=0.702
sign_split       τ=0.454   pairwise=0.730
scientific       τ=0.404   pairwise=0.704
================================================================================
intfloat/multilingual-e5-large-instruct
================================================================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/128 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/140k [00:00<?, ?B/s]

sentence_xlm-roberta_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/690 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.12GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/271 [00:00<?, ?B/s]

=== multilingual_e5_large_instruct ===

[meter]
local_0_10       τ=0.466   pairwise=0.736
medium_0_1000    τ=0.417   pairwise=0.711
log_1_100k       τ=0.686   pairwise=0.843
sign_split       τ=0.477   pairwise=0.741
scientific       τ=0.469   pairwise=0.737

[kilogram]
local_0_10       τ=0.470   pairwise=0.738
medium_0_1000    τ=0.479   pairwise=0.742
log_1_100k       τ=0.564   pairwise=0.782
sign_split       τ=0.443   pairwise=0.724
scientific       τ=0.484   pairwise=0.745

[liter]
local_0_10       τ=0.489   pairwise=0.748
medium_0_1000    τ=0.506   pairwise=0.756
log_1_100k       τ=0.628   pairwise=0.814
sign_split       τ=0.443   pairwise=0.724
scientific       τ=0.423   pairwise=0.713

[second]
local_0_10       τ=0.323   pairwise=0.663
medium_0_1000    τ=0.582   pairwise=0.795
log_1_100k       τ=0.757   pairwise=0.879
sign_split       τ=0.557   pairwise=0.782
scientific       τ=0.395   pairwise=0.699
================================================================================
BAAI/bge-m3
================================================================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 2.27GB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.27GB

model.safetensors: downloading bytes:           |  0.00B

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

=== bge_m3 ===

[meter]
local_0_10       τ=0.329   pairwise=0.667
medium_0_1000    τ=0.349   pairwise=0.677
log_1_100k       τ=0.494   pairwise=0.747
sign_split       τ=0.378   pairwise=0.692
scientific       τ=0.359   pairwise=0.681

[kilogram]
local_0_10       τ=0.365   pairwise=0.685
medium_0_1000    τ=0.534   pairwise=0.771
log_1_100k       τ=0.440   pairwise=0.720
sign_split       τ=0.291   pairwise=0.648
scientific       τ=0.372   pairwise=0.688

[liter]
local_0_10       τ=0.267   pairwise=0.635
medium_0_1000    τ=0.556   pairwise=0.782
log_1_100k       τ=0.522   pairwise=0.761
sign_split       τ=0.293   pairwise=0.649
scientific       τ=0.356   pairwise=0.680

[second]
local_0_10       τ=0.243   pairwise=0.623
medium_0_1000    τ=0.479   pairwise=0.743
log_1_100k       τ=0.416   pairwise=0.708
sign_split       τ=0.432   pairwise=0.719
scientific       τ=0.410   pairwise=0.707
================================================================================
google/embeddinggemma-300m
================================================================================

modules.json:   0%|          | 0.00/573 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/997 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/18.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/58.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.49k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.21GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/314 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 33.4MB

tokenizer.json: downloading bytes:           |  0.00B

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/312 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/134 [00:00<?, ?B/s]

2_Dense/model.safetensors: reconstructing file:   0%|          |  0.00B / 9.44MB

2_Dense/model.safetensors: downloading bytes:           |  0.00B

config.json:   0%|          | 0.00/134 [00:00<?, ?B/s]

3_Dense/model.safetensors: reconstructing file:   0%|          |  0.00B / 9.44MB

3_Dense/model.safetensors: downloading bytes:           |  0.00B

=== embeddinggemma_300m ===

[meter]
local_0_10       τ=0.289   pairwise=0.646
medium_0_1000    τ=0.320   pairwise=0.662
log_1_100k       τ=0.260   pairwise=0.630
sign_split       τ=0.209   pairwise=0.606
scientific       τ=0.311   pairwise=0.657

[kilogram]
local_0_10       τ=0.272   pairwise=0.638
medium_0_1000    τ=0.393   pairwise=0.699
log_1_100k       τ=0.181   pairwise=0.591
sign_split       τ=0.148   pairwise=0.575
scientific       τ=0.293   pairwise=0.648

[liter]
local_0_10       τ=0.273   pairwise=0.638
medium_0_1000    τ=0.313   pairwise=0.659
log_1_100k       τ=0.153   pairwise=0.577
sign_split       τ=0.136   pairwise=0.569
scientific       τ=0.335   pairwise=0.670

[second]
local_0_10       τ=0.319   pairwise=0.662
medium_0_1000    τ=0.350   pairwise=0.677
log_1_100k       τ=0.131   pairwise=0.565
sign_split       τ=0.148   pairwise=0.575
scientific       τ=0.250   pairwise=0.626

[{'model': 'LaBSE',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.28028649114277393,
  'pairwise': 0.6419736986121952},
 {'model': 'LaBSE',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.5621944628649792,
  'pairwise': 0.7848175437742575},
 {'model': 'LaBSE',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.6253348077156715,
  'pairwise': 0.8127262187088276},
 {'model': 'LaBSE',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.5105365213365939,
  'pairwise': 0.758717647941549},
 {'model': 'LaBSE',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.4469472337572701,
  'pairwise': 0.7258205788652333},
 {'model': 'LaBSE',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.32243436928664243,
  'pairwise': 0.6633242223401898},
 {'model': 'LaBSE',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.512583886453611,
  'pairwise': 0.7597639613205295},
 {'model': 'LaBSE',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.4899651174411971,
  'pairwise': 0.7450376811594204},
 {'model': 'LaBSE',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.42425791553190173,
  'pairwise': 0.7150361534792677},
 {'model': 'LaBSE',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.45467266800156,
  'pairwise': 0.7296315858596928},
 {'model': 'LaBSE',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.3081390344089443,
  'pairwise': 0.6560440452731344},
 {'model': 'LaBSE',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.5707868110332167,
  'pairwise': 0.7891491672250718},
 {'model': 'LaBSE',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.41025918476160067,
  'pairwise': 0.7051868247694335},
 {'model': 'LaBSE',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.4745245993828052,
  'pairwise': 0.7404967648312059},
 {'model': 'LaBSE',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.47090688041228096,
  'pairwise': 0.7378973719520393},
 {'model': 'LaBSE',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.25910776980169925,
  'pairwise': 0.6313205915771501},
 {'model': 'LaBSE',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.4548699182656012,
  'pairwise': 0.7303590249878507},
 {'model': 'LaBSE',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.4943103108731911,
  'pairwise': 0.7472089591567851},
 {'model': 'LaBSE',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.4309686496170117,
  'pairwise': 0.7182333006388052},
 {'model': 'LaBSE',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.4210151796244503,
  'pairwise': 0.7127865453622529},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.4799067714228389,
  'pairwise': 0.7428642892269854},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.47044227512471054,
  'pairwise': 0.738161662039562},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.24990825209400888,
  'pairwise': 0.6249807641633729},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.04157384893160611,
  'pairwise': 0.5212840448595365},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.1294479672363331,
  'pairwise': 0.5655475786096996},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.45634062667928776,
  'pairwise': 0.7308222357150367},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.366382457449615,
  'pairwise': 0.6854668164310919},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.3589063960842054,
  'pairwise': 0.6794861660079051},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.0369475040173748,
  'pairwise': 0.5189118676333597},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.11441415863638646,
  'pairwise': 0.5579026684673771},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.3698164767510868,
  'pairwise': 0.6871480067279099},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.3414295864141668,
  'pairwise': 0.6727911356466086},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.2635093261981217,
  'pairwise': 0.6317702239789197},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.03122929351553207,
  'pairwise': 0.5159483039111679},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.14022889703055483,
  'pairwise': 0.570966219290159},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.37382708875068493,
  'pairwise': 0.6891528966856798},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.4079100551940163,
  'pairwise': 0.7064480680492901},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.32294962423090856,
  'pairwise': 0.661500395256917},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.06719236172271541,
  'pairwise': 0.5341189266781478},
 {'model': 'paraphrase_multilingual_mpnet_base_v2',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.13031760557404806,
  'pairwise': 0.5659824591829222},
 {'model': 'multilingual_e5_base',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.2997627907524808,
  'pairwise': 0.6519297863099798},
 {'model': 'multilingual_e5_base',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.368734467862708,
  'pairwise': 0.6870792675998921},
 {'model': 'multilingual_e5_base',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.42646053002200773,
  'pairwise': 0.7132722002635046},
 {'model': 'multilingual_e5_base',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.37350817583785906,
  'pairwise': 0.6893448741873942},
 {'model': 'multilingual_e5_base',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.35369533170559975,
  'pairwise': 0.6786479631702261},
 {'model': 'multilingual_e5_base',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.3093821125058373,
  'pairwise': 0.6567882995436919},
 {'model': 'multilingual_e5_base',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.41068531765789684,
  'pairwise': 0.7082298622407528},
 {'model': 'multilingual_e5_base',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.3452974240152053,
  'pairwise': 0.6726888010540185},
 {'model': 'multilingual_e5_base',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.34979340616892746,
  'pairwise': 0.6774085818889857},
 {'model': 'multilingual_e5_base',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.3591682921338249,
  'pairwise': 0.6813667048314244},
 {'model': 'multilingual_e5_base',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.29462640718452837,
  'pairwise': 0.6492988261668637},
 {'model': 'multilingual_e5_base',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.3973412199165719,
  'pairwise': 0.7013983529620466},
 {'model': 'multilingual_e5_base',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.36297858343549505,
  'pairwise': 0.6815293807641634},
 {'model': 'multilingual_e5_base',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.340555123510702,
  'pairwise': 0.6726799898105134},
 {'model': 'multilingual_e5_base',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.33783754289475865,
  'pairwise': 0.6706145446586815},
 {'model': 'multilingual_e5_base',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.2124343121378154,
  'pairwise': 0.6076988050359826},
 {'model': 'multilingual_e5_base',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.38643452588481,
  'pairwise': 0.696008942842659},
 {'model': 'multilingual_e5_base',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.4861759402594687,
  'pairwise': 0.7431325428194994},
 {'model': 'multilingual_e5_base',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.295820213645728,
  'pairwise': 0.6499931628220038},
 {'model': 'multilingual_e5_base',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.37235771158758285,
  'pairwise': 0.6880352634284322},
 {'model': 'multilingual_e5_large',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.3002191298081305,
  'pairwise': 0.6521359606928352},
 {'model': 'multilingual_e5_large',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.4532334519643724,
  'pairwise': 0.7294727888469981},
 {'model': 'multilingual_e5_large',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.4705206071604704,
  'pairwise': 0.7353032938076416},
 {'model': 'multilingual_e5_large',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.4417865809123547,
  'pairwise': 0.7237926725434516},
 {'model': 'multilingual_e5_large',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.3920120104285461,
  'pairwise': 0.6981289386150178},
 {'model': 'multilingual_e5_large',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.2712245729830463,
  'pairwise': 0.6374226839412203},
 {'model': 'multilingual_e5_large',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.41562475539606636,
  'pairwise': 0.7106633174360154},
 {'model': 'multilingual_e5_large',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.3653016362631451,
  'pairwise': 0.6826930171277997},
 {'model': 'multilingual_e5_large',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.42070399549517873,
  'pairwise': 0.712979553595826},
 {'model': 'multilingual_e5_large',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.4285073158095662,
  'pairwise': 0.7165098471999712},
 {'model': 'multilingual_e5_large',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.29716490202931717,
  'pairwise': 0.6505848443492056},
 {'model': 'multilingual_e5_large',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.41073507307569296,
  'pairwise': 0.7082813171110548},
 {'model': 'multilingual_e5_large',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.4661796259764161,
  'pairwise': 0.733136231884058},
 {'model': 'multilingual_e5_large',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.4186159220548613,
  'pairwise': 0.7118926320564859},
 {'model': 'multilingual_e5_large',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.384602256577384,
  'pairwise': 0.6943409161306697},
 {'model': 'multilingual_e5_large',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.18041057773337685,
  'pairwise': 0.5914603918510368},
 {'model': 'multilingual_e5_large',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.4626925305152032,
  'pairwise': 0.7344255439854497},
 {'model': 'multilingual_e5_large',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.404723505711195,
  'pairwise': 0.7024047430830039},
 {'model': 'multilingual_e5_large',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.4538053448873834,
  'pairwise': 0.7295368417676583},
 {'model': 'multilingual_e5_large',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.40367293330239784,
  'pairwise': 0.7039927626851334},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.46640910510145484,
  'pairwise': 0.7363925617969747},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.4170249371266939,
  'pairwise': 0.7110525716090522},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.6864831708546845,
  'pairwise': 0.843294861660079},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.47725006124863817,
  'pairwise': 0.7414574815768299},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.4688124171984322,
  'pairwise': 0.7366329511941805},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.46953463988031624,
  'pairwise': 0.7380163782567012},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.47860753390883026,
  'pairwise': 0.7423187519587053},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.564443128196596,
  'pairwise': 0.78226930171278},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.44300672487316006,
  'pairwise': 0.7239980072541415},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.48418007952785785,
  'pairwise': 0.744502909959985},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.48908253578711014,
  'pairwise': 0.7477881175218999},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.5062912260928855,
  'pairwise': 0.7564744851372213},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.6276415380825546,
  'pairwise': 0.8138735177865613},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.4425548308685106,
  'pairwise': 0.7237969167629797},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.42255701367803966,
  'pairwise': 0.7134568864617836},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.3228331445098853,
  'pairwise': 0.6634697638038732},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.5822711900108494,
  'pairwise': 0.7948669706891884},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.7569342759241471,
  'pairwise': 0.8785285902503294},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.557495276626338,
  'pairwise': 0.7821126759025467},
 {'model': 'multilingual_e5_large_instruct',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.39462443598898994,
  'pairwise': 0.6994375840479841},
 {'model': 'bge_m3',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.3290378149824401,
  'pairwise': 0.666670003512271},
 {'model': 'bge_m3',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.3490808788782444,
  'pairwise': 0.6769415865427275},
 {'model': 'bge_m3',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.49401571702179503,
  'pairwise': 0.7470592885375494},
 {'model': 'bge_m3',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.37808638478510903,
  'pairwise': 0.6919247653452759},
 {'model': 'bge_m3',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.358683376139136,
  'pairwise': 0.681172087172825},
 {'model': 'bge_m3',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.3646550437675113,
  'pairwise': 0.6847494640680614},
 {'model': 'bge_m3',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.5339277634285902,
  'pairwise': 0.7705836669124421},
 {'model': 'bge_m3',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.4398022878512208,
  'pairwise': 0.7199472990777339},
 {'model': 'bge_m3',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.2909529465020087,
  'pairwise': 0.6476344882463339},
 {'model': 'bge_m3',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.3721165451461916,
  'pairwise': 0.6879391452739911},
 {'model': 'bge_m3',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.26662140955740715,
  'pairwise': 0.6350744073269028},
 {'model': 'bge_m3',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.5556306703979859,
  'pairwise': 0.781510048597484},
 {'model': 'bge_m3',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.5224072977864472,
  'pairwise': 0.7612479578392624},
 {'model': 'bge_m3',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.2927231485982701,
  'pairwise': 0.6486559819429489},
 {'model': 'bge_m3',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.35556233161320316,
  'pairwise': 0.679646196513475},
 {'model': 'bge_m3',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.2425588533437303,
  'pairwise': 0.6227850225756061},
 {'model': 'bge_m3',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.4793913929219358,
  'pairwise': 0.7428534282421795},
 {'model': 'bge_m3',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.4160346984401842,
  'pairwise': 0.708063768115942},
 {'model': 'bge_m3',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.4318278559765852,
  'pairwise': 0.7191054089090594},
 {'model': 'bge_m3',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.4103770382169168,
  'pairwise': 0.7073639475497637},
 {'model': 'embeddinggemma_300m',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.288624834857306,
  'pairwise': 0.6463044016140724},
 {'model': 'embeddinggemma_300m',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.31986417264829536,
  'pairwise': 0.6620051058307165},
 {'model': 'embeddinggemma_300m',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.26037989187217836,
  'pairwise': 0.6302350461133069},
 {'model': 'embeddinggemma_300m',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.20904439217610182,
  'pairwise': 0.6063230394204627},
 {'model': 'embeddinggemma_300m',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.31067999153779163,
  'pairwise': 0.6572305417137245},
 {'model': 'embeddinggemma_300m',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.2716623719511545,
  'pairwise': 0.63760797059527},
 {'model': 'embeddinggemma_300m',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.3928568048059834,
  'pairwise': 0.6991715918348917},
 {'model': 'embeddinggemma_300m',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.1812452448416298,
  'pairwise': 0.5906656126482214},
 {'model': 'embeddinggemma_300m',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.14793627588563038,
  'pairwise': 0.5752815142539704},
 {'model': 'embeddinggemma_300m',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.2927121313994387,
  'pairwise': 0.6481007487903336},
 {'model': 'embeddinggemma_300m',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.2730650777015399,
  'pairwise': 0.638257150321013},
 {'model': 'embeddinggemma_300m',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.3128960283931665,
  'pairwise': 0.6585468565677566},
 {'model': 'embeddinggemma_300m',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.15340125583136363,
  'pairwise': 0.57673465085639},
 {'model': 'embeddinggemma_300m',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.13581684979896863,
  'pairwise': 0.5691758694246216},
 {'model': 'embeddinggemma_300m',
  'unit': 'liter',
  'range': 'scientific',

#### PT2

In [ ]:
NEW_MODELS_2 = [
    # "Alibaba-NLP/gte-multilingual-base",
    # "Alibaba-NLP/gte-large-en-v1.5",
    "ibm-granite/granite-embedding-107m-multilingual",
    "ibm-granite/granite-embedding-278m-multilingual",
    "ibm-granite/granite-embedding-english-r2",
    "ibm-granite/granite-embedding-97m-multilingual-r2",
    "ibm-granite/granite-embedding-311m-multilingual-r2",
]

run_measurement(NEW_MODELS_2)

================================================================================
ibm-granite/granite-embedding-107m-multilingual
================================================================================

modules.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/611k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/697 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  214MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/462 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/238 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

=== granite_embedding_107m_multilingual ===

[meter]
local_0_10       τ=0.250   pairwise=0.627
medium_0_1000    τ=0.393   pairwise=0.699
log_1_100k       τ=0.297   pairwise=0.648
sign_split       τ=0.205   pairwise=0.605
scientific       τ=0.235   pairwise=0.619

[kilogram]
local_0_10       τ=0.235   pairwise=0.619
medium_0_1000    τ=0.345   pairwise=0.675
log_1_100k       τ=0.205   pairwise=0.603
sign_split       τ=0.207   pairwise=0.606
scientific       τ=0.246   pairwise=0.625

[liter]
local_0_10       τ=0.270   pairwise=0.636
medium_0_1000    τ=0.399   pairwise=0.702
log_1_100k       τ=0.345   pairwise=0.672
sign_split       τ=0.193   pairwise=0.598
scientific       τ=0.256   pairwise=0.630

[second]
local_0_10       τ=0.246   pairwise=0.624
medium_0_1000    τ=0.365   pairwise=0.685
log_1_100k       τ=0.270   pairwise=0.635
sign_split       τ=0.209   pairwise=0.606
scientific       τ=0.254   pairwise=0.628
================================================================================
ibm-granite/granite-embedding-278m-multilingual
================================================================================

modules.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/610k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/698 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  556MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/418 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

=== granite_embedding_278m_multilingual ===

[meter]
local_0_10       τ=0.265   pairwise=0.634
medium_0_1000    τ=0.428   pairwise=0.717
log_1_100k       τ=0.331   pairwise=0.666
sign_split       τ=0.275   pairwise=0.640
scientific       τ=0.260   pairwise=0.632

[kilogram]
local_0_10       τ=0.230   pairwise=0.616
medium_0_1000    τ=0.416   pairwise=0.711
log_1_100k       τ=0.296   pairwise=0.648
sign_split       τ=0.263   pairwise=0.634
scientific       τ=0.244   pairwise=0.624

[liter]
local_0_10       τ=0.277   pairwise=0.640
medium_0_1000    τ=0.411   pairwise=0.708
log_1_100k       τ=0.298   pairwise=0.649
sign_split       τ=0.270   pairwise=0.637
scientific       τ=0.270   pairwise=0.637

[second]
local_0_10       τ=0.223   pairwise=0.613
medium_0_1000    τ=0.443   pairwise=0.724
log_1_100k       τ=0.330   pairwise=0.665
sign_split       τ=0.265   pairwise=0.635
scientific       τ=0.276   pairwise=0.640
================================================================================
ibm-granite/granite-embedding-english-r2
================================================================================

modules.json:   0%|          | 0.00/230 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/12.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/55.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.31k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  298MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/20.8k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.58M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

=== granite_embedding_english_r2 ===

[meter]
local_0_10       τ=0.316   pairwise=0.660
medium_0_1000    τ=0.336   pairwise=0.671
log_1_100k       τ=0.207   pairwise=0.604
sign_split       τ=0.258   pairwise=0.631
scientific       τ=0.331   pairwise=0.667

[kilogram]
local_0_10       τ=0.294   pairwise=0.649
medium_0_1000    τ=0.358   pairwise=0.682
log_1_100k       τ=0.186   pairwise=0.593
sign_split       τ=0.248   pairwise=0.626
scientific       τ=0.234   pairwise=0.618

[liter]
local_0_10       τ=0.334   pairwise=0.669
medium_0_1000    τ=0.374   pairwise=0.689
log_1_100k       τ=0.195   pairwise=0.598
sign_split       τ=0.162   pairwise=0.582
scientific       τ=0.268   pairwise=0.636

[second]
local_0_10       τ=0.302   pairwise=0.653
medium_0_1000    τ=0.377   pairwise=0.691
log_1_100k       τ=0.224   pairwise=0.612
sign_split       τ=0.246   pairwise=0.624
scientific       τ=0.256   pairwise=0.630
================================================================================
ibm-granite/granite-embedding-97m-multilingual-r2
================================================================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/283 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/20.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.22k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  195MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/74 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/12.9k [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 25.3MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/871 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/313 [00:00<?, ?B/s]

=== granite_embedding_97m_multilingual_r2 ===

[meter]
local_0_10       τ=0.306   pairwise=0.655
medium_0_1000    τ=0.310   pairwise=0.657
log_1_100k       τ=0.145   pairwise=0.572
sign_split       τ=0.340   pairwise=0.672
scientific       τ=0.209   pairwise=0.606

[kilogram]
local_0_10       τ=0.274   pairwise=0.639
medium_0_1000    τ=0.352   pairwise=0.678
log_1_100k       τ=0.148   pairwise=0.574
sign_split       τ=0.429   pairwise=0.717
scientific       τ=0.227   pairwise=0.615

[liter]
local_0_10       τ=0.252   pairwise=0.628
medium_0_1000    τ=0.264   pairwise=0.634
log_1_100k       τ=0.180   pairwise=0.590
sign_split       τ=0.387   pairwise=0.696
scientific       τ=0.237   pairwise=0.620

[second]
local_0_10       τ=0.251   pairwise=0.627
medium_0_1000    τ=0.254   pairwise=0.629
log_1_100k       τ=0.149   pairwise=0.574
sign_split       τ=0.337   pairwise=0.671
scientific       τ=0.227   pairwise=0.615
================================================================================
ibm-granite/granite-embedding-311m-multilingual-r2
================================================================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/283 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/21.4k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.19k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  623MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 33.4MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/313 [00:00<?, ?B/s]

=== granite_embedding_311m_multilingual_r2 ===

[meter]
local_0_10       τ=0.382   pairwise=0.693
medium_0_1000    τ=0.250   pairwise=0.627
log_1_100k       τ=0.326   pairwise=0.663
sign_split       τ=0.368   pairwise=0.687
scientific       τ=0.269   pairwise=0.636

[kilogram]
local_0_10       τ=0.379   pairwise=0.692
medium_0_1000    τ=0.273   pairwise=0.639
log_1_100k       τ=0.223   pairwise=0.611
sign_split       τ=0.396   pairwise=0.701
scientific       τ=0.227   pairwise=0.615

[liter]
local_0_10       τ=0.399   pairwise=0.702
medium_0_1000    τ=0.305   pairwise=0.655
log_1_100k       τ=0.299   pairwise=0.649
sign_split       τ=0.393   pairwise=0.699
scientific       τ=0.263   pairwise=0.633

[second]
local_0_10       τ=0.317   pairwise=0.661
medium_0_1000    τ=0.197   pairwise=0.600
log_1_100k       τ=0.239   pairwise=0.620
sign_split       τ=0.457   pairwise=0.731
scientific       τ=0.268   pairwise=0.636

[{'model': 'granite_embedding_107m_multilingual',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.2503454645102057,
  'pairwise': 0.6265589130991766},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.3934328571156283,
  'pairwise': 0.6992408129289227},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.29689847181665824,
  'pairwise': 0.6484927536231885},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.20530936392203925,
  'pairwise': 0.604596396994891},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.23455170848952434,
  'pairwise': 0.6187777467290474},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.23465614001591387,
  'pairwise': 0.618637615318041},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.34519553957737575,
  'pairwise': 0.6748072665571622},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.20529742401520518,
  'pairwise': 0.6026888010540185},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.20736690853622303,
  'pairwise': 0.6056518033834097},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.2463773356310573,
  'pairwise': 0.6246600291486004},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.26973671995560017,
  'pairwise': 0.6364297528838206},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.39911463381311035,
  'pairwise': 0.7021676670489055},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.344725611835165,
  'pairwise': 0.6724068511198945},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.19344702521538548,
  'pairwise': 0.5984944633211761},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.2561684282005746,
  'pairwise': 0.6296708797131241},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.24594306543890085,
  'pairwise': 0.6244137591486772},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.36543737795241915,
  'pairwise': 0.6850260128667989},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.26993247251966307,
  'pairwise': 0.6350050065876153},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.208880951914858,
  'pairwise': 0.6064143326777393},
 {'model': 'granite_embedding_107m_multilingual',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.2535572872153331,
  'pairwise': 0.6283643312139593},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.26521873294933623,
  'pairwise': 0.6341678324839825},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.4284328850294275,
  'pairwise': 0.7169514513056741},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.33109715811944307,
  'pairwise': 0.6655899868247694},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.27513855253533587,
  'pairwise': 0.6398433744400913},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.25979273860803004,
  'pairwise': 0.6315575183937566},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.23007104690043892,
  'pairwise': 0.6163072735874844},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.4157742805484953,
  'pairwise': 0.7105564579770898},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.2957332596858858,
  'pairwise': 0.6479072463768115},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.262879773012927,
  'pairwise': 0.6335971930313572},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.24433285726929513,
  'pairwise': 0.6237781153566037},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.2769025330287342,
  'pairwise': 0.6400883318958603},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.41075217739640507,
  'pairwise': 0.7080414288970049},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.2984960971666601,
  'pairwise': 0.6492152832674571},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.27047388753312707,
  'pairwise': 0.6374324007547975},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.27001073069582393,
  'pairwise': 0.636703244909892},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.22260500197070524,
  'pairwise': 0.6126010657657003},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.4430250794030921,
  'pairwise': 0.7242751605524991},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.3302228541231193,
  'pairwise': 0.6651504611330697},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.2648201809811801,
  'pairwise': 0.6345346636375749},
 {'model': 'granite_embedding_278m_multilingual',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.2764875702318584,
  'pairwise': 0.639992667036729},
 {'model': 'granite_embedding_english_r2',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.3164306462107012,
  'pairwise': 0.6603268907831703},
 {'model': 'granite_embedding_english_r2',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.3364155319124384,
  'pairwise': 0.670543035041432},
 {'model': 'granite_embedding_english_r2',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.20702128505120584,
  'pairwise': 0.6035430830039527},
 {'model': 'granite_embedding_english_r2',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.25810734938675634,
  'pairwise': 0.6310772563789523},
 {'model': 'granite_embedding_english_r2',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.33108925845271164,
  'pairwise': 0.6674951251522931},
 {'model': 'granite_embedding_english_r2',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.29352189629769426,
  'pairwise': 0.6486931232404614},
 {'model': 'granite_embedding_english_r2',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.3583853613149775,
  'pairwise': 0.6817401397240461},
 {'model': 'granite_embedding_english_r2',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.18587081578822295,
  'pairwise': 0.5929723320158102},
 {'model': 'granite_embedding_english_r2',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.24779052009019395,
  'pairwise': 0.6257706284099963},
 {'model': 'granite_embedding_english_r2',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.2336587730894145,
  'pairwise': 0.6183193235756415},
 {'model': 'granite_embedding_english_r2',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.33371160748466316,
  'pairwise': 0.6690900554275471},
 {'model': 'granite_embedding_english_r2',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.3738378333997527,
  'pairwise': 0.6894206792208356},
 {'model': 'granite_embedding_english_r2',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.19515354954095832,
  'pairwise': 0.5976173913043479},
 {'model': 'granite_embedding_english_r2',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.16242006353997804,
  'pairwise': 0.5822365242598033},
 {'model': 'granite_embedding_english_r2',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.26775519340131015,
  'pairwise': 0.6356079487746367},
 {'model': 'granite_embedding_english_r2',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.3021923068840215,
  'pairwise': 0.6531047154668479},
 {'model': 'granite_embedding_english_r2',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.37718877867893,
  'pairwise': 0.6912725789081386},
 {'model': 'granite_embedding_english_r2',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.22441100980605447,
  'pairwise': 0.6122371541501976},
 {'model': 'granite_embedding_english_r2',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.245592710764709,
  'pairwise': 0.6243136856244313},
 {'model': 'granite_embedding_english_r2',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.25572191128734123,
  'pairwise': 0.6295157762227613},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.30589687989531,
  'pairwise': 0.655056907843679},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.3101161575422714,
  'pairwise': 0.6572728135718907},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.1446866485417212,
  'pairwise': 0.5723678524374176},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.3396284508119423,
  'pairwise': 0.6719968689936195},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.20873524219302297,
  'pairwise': 0.6055640694928199},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.27385224628387084,
  'pairwise': 0.6387972090845644},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.3516427426618294,
  'pairwise': 0.678249916310483},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.148178599217091,
  'pairwise': 0.5741206851119894},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.4285420092529272,
  'pairwise': 0.7170613287955501},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.2270956772153874,
  'pairwise': 0.6149423326633287},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.2521003717335042,
  'pairwise': 0.6278208910363422},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.2643252988614799,
  'pairwise': 0.634031070051074},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.18035567144652412,
  'pairwise': 0.5902108036890646},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.3865475837248568,
  'pairwise': 0.6958666917813453},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.23714912788468417,
  'pairwise': 0.6199220210360896},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.25123662803993985,
  'pairwise': 0.6274598393432941},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.253716107326484,
  'pairwise': 0.6286846730152641},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.14873566852934175,
  'pairwise': 0.5743878787878788},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.336925010886752,
  'pairwise': 0.6705440880913007},
 {'model': 'granite_embedding_97m_multilingual_r2',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.22684678318377588,
  'pairwise': 0.6146905599972302},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.3815130580878079,
  'pairwise': 0.6933381439257301},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.2500762886538835,
  'pairwise': 0.6267995620071505},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.3261422422759498,
  'pairwise': 0.663098814229249},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.36823317062195293,
  'pairwise': 0.6870855456134718},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.2687163360906263,
  'pairwise': 0.6359873006168306},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.3789907015123372,
  'pairwise': 0.692068366127946},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.27329116883979393,
  'pairwise': 0.6387431149036358},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.22291855890235204,
  'pairwise': 0.61146930171278},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.3962657361495022,
  'pairwise': 0.7010804876148233},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.22678089597605675,
  'pairwise': 0.6147727660647045},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.398545073706365,
  'pairwise': 0.7021049024531132},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.30476753600812917,
  'pairwise': 0.654684361708244},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.29888428178252097,
  'pairwise': 0.6494640316205533},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.3926983716277996,
  'pairwise': 0.6992673245949332},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.26331049652777505,
  'pairwise': 0.6331878361101642},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.31681366021553,
  'pairwise': 0.6607150764364469},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.196580407657104,
  'pairwise': 0.5998682011512553},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.23944503681171914,
  'pairwise': 0.6197349143610014},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.4565442357852047,
  'pairwise': 0.7312815368391072},
 {'model': 'granite_embedding_311m_multilingual_r2',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.26824464550525035,
  'pairwise': 0.6356581423682127}]

#### PT3

In [ ]:
NEW_MODELS_3 = [
    "mixedbread-ai/mxbai-embed-large-v1",
    "microsoft/harrier-oss-v1-270m",
    "microsoft/harrier-oss-v1-0.6b",
    "lightonai/DenseOn",
]

run_measurement(NEW_MODELS_3)

================================================================================
mixedbread-ai/mxbai-embed-large-v1
================================================================================

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/266 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/114k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/677 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  670MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.24k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/695 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

=== mxbai_embed_large_v1 ===

[meter]
local_0_10       τ=0.304   pairwise=0.654
medium_0_1000    τ=0.443   pairwise=0.724
log_1_100k       τ=0.430   pairwise=0.715
sign_split       τ=0.203   pairwise=0.603
scientific       τ=0.332   pairwise=0.668

[kilogram]
local_0_10       τ=0.291   pairwise=0.648
medium_0_1000    τ=0.366   pairwise=0.685
log_1_100k       τ=0.339   pairwise=0.670
sign_split       τ=0.189   pairwise=0.596
scientific       τ=0.354   pairwise=0.679

[liter]
local_0_10       τ=0.371   pairwise=0.688
medium_0_1000    τ=0.459   pairwise=0.733
log_1_100k       τ=0.317   pairwise=0.659
sign_split       τ=0.151   pairwise=0.577
scientific       τ=0.301   pairwise=0.652

[second]
local_0_10       τ=0.282   pairwise=0.643
medium_0_1000    τ=0.492   pairwise=0.750
log_1_100k       τ=0.495   pairwise=0.748
sign_split       τ=0.413   pairwise=0.710
scientific       τ=0.459   pairwise=0.732
================================================================================
microsoft/harrier-oss-v1-270m
================================================================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/351 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/7.61k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.33k [00:00<?, ?B/s]

[transformers] Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'sliding_attention', 'full_attention'}

model.safetensors: reconstructing file:   0%|          |  0.00B /  536MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

[transformers] Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'sliding_attention', 'full_attention'}
[transformers] Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'sliding_attention', 'full_attention'}

tokenizer.json: reconstructing file:   0%|          |  0.00B / 33.4MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

=== harrier_oss_v1_270m ===

[meter]
local_0_10       τ=0.289   pairwise=0.646
medium_0_1000    τ=0.422   pairwise=0.713
log_1_100k       τ=0.735   pairwise=0.868
sign_split       τ=0.559   pairwise=0.783
scientific       τ=0.195   pairwise=0.598

[kilogram]
local_0_10       τ=0.280   pairwise=0.642
medium_0_1000    τ=0.394   pairwise=0.700
log_1_100k       τ=0.665   pairwise=0.833
sign_split       τ=0.505   pairwise=0.755
scientific       τ=0.169   pairwise=0.585

[liter]
local_0_10       τ=0.206   pairwise=0.604
medium_0_1000    τ=0.421   pairwise=0.713
log_1_100k       τ=0.638   pairwise=0.819
sign_split       τ=0.521   pairwise=0.763
scientific       τ=0.187   pairwise=0.595

[second]
local_0_10       τ=0.220   pairwise=0.611
medium_0_1000    τ=0.448   pairwise=0.727
log_1_100k       τ=0.736   pairwise=0.868
sign_split       τ=0.537   pairwise=0.772
scientific       τ=0.270   pairwise=0.636
================================================================================
microsoft/harrier-oss-v1-0.6b
================================================================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/351 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/7.61k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.35k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.19GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/310 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/5.40k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json: reconstructing file:   0%|          |  0.00B / 11.4MB

tokenizer.json: downloading bytes:           |  0.00B

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/4.12k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

=== harrier_oss_v1_0.6b ===

[meter]
local_0_10       τ=0.272   pairwise=0.638
medium_0_1000    τ=0.465   pairwise=0.735
log_1_100k       τ=0.647   pairwise=0.824
sign_split       τ=0.357   pairwise=0.681
scientific       τ=0.312   pairwise=0.657

[kilogram]
local_0_10       τ=0.311   pairwise=0.658
medium_0_1000    τ=0.470   pairwise=0.738
log_1_100k       τ=0.656   pairwise=0.828
sign_split       τ=0.339   pairwise=0.672
scientific       τ=0.304   pairwise=0.653

[liter]
local_0_10       τ=0.262   pairwise=0.633
medium_0_1000    τ=0.471   pairwise=0.739
log_1_100k       τ=0.653   pairwise=0.827
sign_split       τ=0.337   pairwise=0.671
scientific       τ=0.308   pairwise=0.656

[second]
local_0_10       τ=0.220   pairwise=0.612
medium_0_1000    τ=0.387   pairwise=0.696
log_1_100k       τ=0.637   pairwise=0.819
sign_split       τ=0.404   pairwise=0.705
scientific       τ=0.359   pairwise=0.681
================================================================================
lightonai/DenseOn
================================================================================

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/300 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.3k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  596MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/21.0k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.58M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/312 [00:00<?, ?B/s]

=== DenseOn ===

[meter]
local_0_10       τ=0.299   pairwise=0.652
medium_0_1000    τ=0.395   pairwise=0.700
log_1_100k       τ=0.400   pairwise=0.700
sign_split       τ=0.485   pairwise=0.746
scientific       τ=0.349   pairwise=0.676

[kilogram]
local_0_10       τ=0.324   pairwise=0.664
medium_0_1000    τ=0.354   pairwise=0.680
log_1_100k       τ=0.443   pairwise=0.722
sign_split       τ=0.534   pairwise=0.770
scientific       τ=0.337   pairwise=0.670

[liter]
local_0_10       τ=0.313   pairwise=0.659
medium_0_1000    τ=0.409   pairwise=0.707
log_1_100k       τ=0.490   pairwise=0.745
sign_split       τ=0.485   pairwise=0.746
scientific       τ=0.321   pairwise=0.662

[second]
local_0_10       τ=0.240   pairwise=0.622
medium_0_1000    τ=0.356   pairwise=0.681
log_1_100k       τ=0.439   pairwise=0.720
sign_split       τ=0.455   pairwise=0.730
scientific       τ=0.421   pairwise=0.712

[{'model': 'mxbai_embed_large_v1',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.30404679812894464,
  'pairwise': 0.6542122821034854},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.4425523462901057,
  'pairwise': 0.7243112299885855},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.42965472766002644,
  'pairwise': 0.7148722002635046},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.20287003548886548,
  'pairwise': 0.6031540296563226},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.3321306242424909,
  'pairwise': 0.6679553739059746},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.2912974682932998,
  'pairwise': 0.6477271520755441},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.365517851334956,
  'pairwise': 0.6853639001012658},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.33918940625376676,
  'pairwise': 0.6696242424242425},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.18895292729874863,
  'pairwise': 0.5959990383582584},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.354461265929498,
  'pairwise': 0.6792739341478318},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.37137643909527923,
  'pairwise': 0.6882142737851521},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.45933344500647555,
  'pairwise': 0.7328233358547207},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.31716726564942266,
  'pairwise': 0.6586166007905139},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.15129353437489396,
  'pairwise': 0.5768807839394872},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.300889088312973,
  'pairwise': 0.6522199511316908},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.28156829573188447,
  'pairwise': 0.6427568337887608},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.4920658524026886,
  'pairwise': 0.7495235558844066},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.495147757700041,
  'pairwise': 0.7476115942028986},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.41338672209943317,
  'pairwise': 0.7096826799344954},
 {'model': 'mxbai_embed_large_v1',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.4590214329715671,
  'pairwise': 0.7318062133405947},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.2887782157845116,
  'pairwise': 0.6462027387553372},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.42190747998666855,
  'pairwise': 0.713428176169233},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.7354723638180087,
  'pairwise': 0.8677913043478261},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.5589627491360353,
  'pairwise': 0.7830850150533573},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.19461119963998585,
  'pairwise': 0.5982468109680505},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.279805428330213,
  'pairwise': 0.6417424768378703},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.3936945864019081,
  'pairwise': 0.6995059009765713},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.6653253301578068,
  'pairwise': 0.8327167325428195},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.5047054250506631,
  'pairwise': 0.7553816513958942},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.1685513772358831,
  'pairwise': 0.5850833245949928},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.20576941888765943,
  'pairwise': 0.6042904022931861},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.4208986233998789,
  'pairwise': 0.7131767153860066},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.6375002962632701,
  'pairwise': 0.8188047430830039},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.5205465721487643,
  'pairwise': 0.7634566289392786},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.1873375757468237,
  'pairwise': 0.5945962149648027},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.219912357297135,
  'pairwise': 0.6114165949312597},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.4475914737218906,
  'pairwise': 0.7265876495384925},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.7360568127418685,
  'pairwise': 0.8680859025032939},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.537170654643435,
  'pairwise': 0.7718098887967014},
 {'model': 'harrier_oss_v1_270m',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.26962016665805083,
  'pairwise': 0.6361598781805665},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.27168314325169324,
  'pairwise': 0.6376290790167345},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.46454548354716013,
  'pairwise': 0.7352735922575379},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.6470560360967099,
  'pairwise': 0.8235778656126481},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.3574077669740938,
  'pairwise': 0.6810048857558137},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.3116052919129852,
  'pairwise': 0.6574245675734289},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.3110427528230152,
  'pairwise': 0.6576993024227442},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.46975982492137613,
  'pairwise': 0.7379834697325817},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.6557495821466527,
  'pairwise': 0.8279235836627141},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.3392414841875394,
  'pairwise': 0.6721205526906638},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.3036611159626207,
  'pairwise': 0.6533923785116977},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.26219799764194424,
  'pairwise': 0.6329064321833751},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.47134956021167274,
  'pairwise': 0.7388227705175267},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.6534323211599201,
  'pairwise': 0.8267657444005272},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.33745496316644286,
  'pairwise': 0.6708223477689937},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.30844263852716325,
  'pairwise': 0.6558564851602913},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.2203048281559274,
  'pairwise': 0.6115559333529974},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.38699531125119996,
  'pairwise': 0.696061705653254},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.6374897656434204,
  'pairwise': 0.8187942028985506},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.40428835306186767,
  'pairwise': 0.704579558528511},
 {'model': 'harrier_oss_v1_0.6b',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.3592281594201755,
  'pairwise': 0.6814265645500263},
 {'model': 'DenseOn',
  'unit': 'meter',
  'range': 'local_0_10',
  'kendall': 0.29937369162925903,
  'pairwise': 0.6520515105502935},
 {'model': 'DenseOn',
  'unit': 'meter',
  'range': 'medium_0_1000',
  'kendall': 0.3947141106562847,
  'pairwise': 0.7002824859512164},
 {'model': 'DenseOn',
  'unit': 'meter',
  'range': 'log_1_100k',
  'kendall': 0.400095828640632,
  'pairwise': 0.7000959156785244},
 {'model': 'DenseOn',
  'unit': 'meter',
  'range': 'sign_split',
  'kendall': 0.48542841193463393,
  'pairwise': 0.7456257721674132},
 {'model': 'DenseOn',
  'unit': 'meter',
  'range': 'scientific',
  'kendall': 0.34876275918952315,
  'pairwise': 0.6760308826840529},
 {'model': 'DenseOn',
  'unit': 'kilogram',
  'range': 'local_0_10',
  'kendall': 0.32395172215555634,
  'pairwise': 0.664346810473144},
 {'model': 'DenseOn',
  'unit': 'kilogram',
  'range': 'medium_0_1000',
  'kendall': 0.353642268616779,
  'pairwise': 0.6795084549721528},
 {'model': 'DenseOn',
  'unit': 'kilogram',
  'range': 'log_1_100k',
  'kendall': 0.4429791099664875,
  'pairwise': 0.721529907773386},
 {'model': 'DenseOn',
  'unit': 'kilogram',
  'range': 'sign_split',
  'kendall': 0.5343937824065924,
  'pairwise': 0.7702824388974887},
 {'model': 'DenseOn',
  'unit': 'kilogram',
  'range': 'scientific',
  'kendall': 0.3370041720868453,
  'pairwise': 0.6702166663920619},
 {'model': 'DenseOn',
  'unit': 'liter',
  'range': 'local_0_10',
  'kendall': 0.31321961468754284,
  'pairwise': 0.6586195300256712},
 {'model': 'DenseOn',
  'unit': 'liter',
  'range': 'medium_0_1000',
  'kendall': 0.4090436095249392,
  'pairwise': 0.7073411775439192},
 {'model': 'DenseOn',
  'unit': 'liter',
  'range': 'log_1_100k',
  'kendall': 0.48965314806704896,
  'pairwise': 0.7448706192358365},
 {'model': 'DenseOn',
  'unit': 'liter',
  'range': 'sign_split',
  'kendall': 0.4853391748434392,
  'pairwise': 0.7455362522912018},
 {'model': 'DenseOn',
  'unit': 'liter',
  'range': 'scientific',
  'kendall': 0.3208723860094003,
  'pairwise': 0.6620538413234816},
 {'model': 'DenseOn',
  'unit': 'second',
  'range': 'local_0_10',
  'kendall': 0.2397380141611031,
  'pairwise': 0.6217283435675861},
 {'model': 'DenseOn',
  'unit': 'second',
  'range': 'medium_0_1000',
  'kendall': 0.35624421722633176,
  'pairwise': 0.6808565771606722},
 {'model': 'DenseOn',
  'unit': 'second',
  'range': 'log_1_100k',
  'kendall': 0.43920625524552626,
  'pairwise': 0.7196411067193675},
 {'model': 'DenseOn',
  'unit': 'second',
  'range': 'sign_split',
  'kendall': 0.45522601947509644,
  'pairwise': 0.7302038039869277},
 {'model': 'DenseOn',
  'unit': 'second',
  'range': 'scientific',
  'kendall': 0.4209999890586159,
  'pairwise': 0.7124750397051431}]

# Exam 2 - Lexical vs. numerical similarity

**Definitions** (number generation, distances, correlations).

Changes:

* the association statistic is now Kendall's tau (scipy's tau-b, which corrects
  for the heavy ties in the Levenshtein distances) instead of Spearman's rho,
  matching the caption of Table 3 and the statistic used in Tables 1, 2 and 4.
  **Every number in Table 3 changes** - tau-b is systematically smaller in
  magnitude than rho, so old and new values must not be mixed;
* results are written per model to `csv/<model>_lexical.csv` in long format, so
  the table can be rebuilt for any subset of models. Previously each
  `run_lexical` call overwrote the same `.tex`, which made the appendix version
  impossible;
* the LaTeX emission moved to the Tables section (`table_lexical`), where the
  other three tables are built. The old inline version also closed the tabular
  inside the model loop, so it only ever emitted one row.

In [ ]:
#!/usr/bin/env python3

"""
Investigate whether embedding similarity reflects numerical similarity.

For each embedding model:

- generate 50 floats + 50 ints
- embed all numbers as strings
- compute cosine similarity for every pair
- compare against
    * character Levenshtein
    * tokenizer Levenshtein
    * numerical distance

Reports Kendall's tau (tau-b, so ties in the Levenshtein distances are handled)
overall and for several subsets. Results are written per model to
    produced_results/csv/<model>_lexical.csv
and the LaTeX table is built from those files in the Tables section.
"""

from __future__ import annotations

import itertools
import random
import gc

import numpy as np
import pandas as pd
import torch
from scipy.stats import kendalltau
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer
from Levenshtein import distance as levenshtein
from tqdm import tqdm
import os

RESULTS_DIR = "produced_results"
CSV_DIR = os.path.join(RESULTS_DIR, "csv")
os.makedirs(CSV_DIR, exist_ok=True)

# ----------------------------------------------------------------------

SEED = 12345

N_FLOATS = 50
N_INTS = 50

LOW = -1000
HIGH = 1000

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ----------------------------------------------------------------------


def run_lexical(models):
    random.seed(SEED)
    np.random.seed(SEED)


    def make_numbers():

        floats = [
            round(random.uniform(LOW, HIGH), 5)
            for _ in range(N_FLOATS)
        ]

        ints = [
            random.randint(LOW, HIGH)
            for _ in range(N_INTS)
        ]

        return floats, ints


    floats, ints = make_numbers()

    items = []

    for x in floats:
        items.append(
            {
                "value": float(x),
                "text": f"{x:.5f}",
                "type": "float",
                "sign": "positive" if x >= 0 else "negative",
            }
        )

    for x in ints:
        items.append(
            {
                "value": float(x),
                "text": str(x),
                "type": "int",
                "sign": "positive" if x >= 0 else "negative",
            }
        )


    # ----------------------------------------------------------------------


    def token_levenshtein(tokenizer, a: str, b: str):
        ta = tokenizer.encode(a, add_special_tokens=False)
        tb = tokenizer.encode(b, add_special_tokens=False)
        return levenshtein(tuple(ta), tuple(tb))


    def cosine_matrix(x):
        x = x / np.linalg.norm(x, axis=1, keepdims=True)
        return x @ x.T


    # ----------------------------------------------------------------------

    pair_records = []

    for i, j in itertools.combinations(range(len(items)), 2):

        A = items[i]
        B = items[j]

        pair_records.append(
            {
                "i": i,
                "j": j,
                "char_lev": levenshtein(A["text"], B["text"]),
                "num_dist": abs(A["value"] - B["value"]),
                "same_type": A["type"] == B["type"],
                "type_pair": f"{A['type']}-{B['type']}",
                "same_sign": A["sign"] == B["sign"],
                "sign_pair": f"{A['sign']}-{B['sign']}",
            }
        )

    pairs_df = pd.DataFrame(pair_records)

    # ----------------------------------------------------------------------


    def correlations(df):
        """Kendall's tau-b between embedding similarity and each reference."""

        sim = df["similarity"]

        return {
            "char_lev":
                kendalltau(sim, -df["char_lev"]).statistic,
            "token_lev":
                kendalltau(sim, -df["token_lev"]).statistic,
            "num_dist":
                kendalltau(sim, -df["num_dist"]).statistic,
        }

    # ----------------------------------------------------------------------

    results = {}

    for model_name in models:

        print("=" * 80)
        print(model_name)

        model_id = model_name.split("/")[-1].replace("-", "_")

        tokenizer = AutoTokenizer.from_pretrained(
            model_name,
            trust_remote_code=True,
        )

        token_dists = []

        for rec in tqdm(pair_records, leave=False, desc="token distances"):
            token_dists.append(
                token_levenshtein(
                    tokenizer,
                    items[rec["i"]]["text"],
                    items[rec["j"]]["text"],
                )
            )

        model = SentenceTransformer(
            model_name,
            trust_remote_code=True,
            device=DEVICE,
        ).float()

        embeddings = model.encode(
            [x["text"] for x in items],
            normalize_embeddings=True,
            convert_to_numpy=True,
            show_progress_bar=True,
        )

        sim = cosine_matrix(embeddings)

        similarities = []

        for rec in pair_records:
            similarities.append(sim[rec["i"], rec["j"]])

        df = pairs_df.copy()
        df["similarity"] = similarities
        df["token_lev"] = token_dists

        # ------------------------------------------------------------------
        # every subset, in long format
        # ------------------------------------------------------------------

        rows = []

        def add(group_type, group, sub):
            for reference, tau in correlations(sub).items():
                rows.append({
                    "model": model_id,
                    "group_type": group_type,
                    "group": str(group),
                    "reference": reference,
                    "tau": tau,
                    "n_pairs": len(sub),
                })

        add("overall", "all", df)

        for group_type in ["type_pair", "same_sign", "sign_pair"]:
            for key, sub in df.groupby(group_type):
                add(group_type, key, sub)

        out = pd.DataFrame(rows)
        out.to_csv(os.path.join(CSV_DIR, f"{model_id}_lexical.csv"), index=False)

        print("\nKendall's tau (x100)")
        print(
            out[out.group_type.isin(["overall", "type_pair"])]
            .pivot(index="reference", columns="group", values="tau")
            .mul(100)
            .round(1)
            .to_string()
        )
        print()

        results[model_id] = out

        del model, tokenizer, embeddings, sim
        gc.collect()
        torch.cuda.empty_cache()

    print("Wrote per-model CSVs. Build the LaTeX table with table_lexical().")
    return results

### Run: baseline models

In [ ]:
# Baseline models (the original paper set + Qwen3 4B / 8B)
MODELS = [
    "sentence-transformers/all-MiniLM-L6-v2",
    "sentence-transformers/all-mpnet-base-v2",
    "intfloat/e5-large-v2",
    "BAAI/bge-large-en-v1.5",
    "nomic-ai/nomic-embed-text-v1.5",
    "Qwen/Qwen3-Embedding-0.6B",
    "Qwen/Qwen3-Embedding-4B",
    "Qwen/Qwen3-Embedding-8B",
]

run_lexical(MODELS)

================================================================================
sentence-transformers/all-MiniLM-L6-v2

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   21.0         22.0       17.1     44.2
num_dist   28.1         23.0       28.7     39.0
token_lev  15.1         10.4       10.2     37.1

================================================================================
sentence-transformers/all-mpnet-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   27.7         31.7       21.0     41.9
num_dist   26.1         40.9       26.0     36.2
token_lev  20.4         19.9        8.7     34.0

================================================================================
intfloat/e5-large-v2

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   29.0         23.9       27.2     45.1
num_dist   16.9         18.2       15.3     32.8
token_lev  22.0         15.2       14.5     38.7

================================================================================
BAAI/bge-large-en-v1.5

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   10.9         25.2       29.1     35.2
num_dist    8.0         26.5        6.9     18.6
token_lev   7.7         22.9       31.1     18.5

================================================================================
nomic-ai/nomic-embed-text-v1.5

WARNING:transformers_modules.nomic_hyphen_ai.nomic_hyphen_bert_hyphen_2048.7710840340a098cfb869c4f65e87cf2b1b70caca.modeling_hf_nomic_bert:<All keys matched successfully>

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   -5.6         16.9       28.9     32.8
num_dist    6.5          5.8        5.9     15.2
token_lev -16.9         -3.7        5.7     17.5

================================================================================
Qwen/Qwen3-Embedding-0.6B

Loading weights:   0%|          | 0/310 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   47.6         23.6       30.7     50.8
num_dist   11.7         13.7       13.7     25.2
token_lev  47.6         23.6       30.7     50.8

================================================================================
Qwen/Qwen3-Embedding-4B

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   30.1         26.3       38.8     53.8
num_dist   13.1         12.6        8.4     27.3
token_lev  30.1         26.3       38.8     53.8

================================================================================
Qwen/Qwen3-Embedding-8B

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   36.7         33.9       39.2     49.5
num_dist   18.3         24.2       15.8     25.1
token_lev  36.7         33.9       39.2     49.5

Wrote per-model CSVs. Build the LaTeX table with table_lexical().

{'all_MiniLM_L6_v2':                model group_type              group  reference       tau  \
 0   all_MiniLM_L6_v2    overall                all   char_lev  0.209675
 1   all_MiniLM_L6_v2    overall                all  token_lev  0.150933
 2   all_MiniLM_L6_v2    overall                all   num_dist  0.280550
 3   all_MiniLM_L6_v2  type_pair        float-float   char_lev  0.220345
 4   all_MiniLM_L6_v2  type_pair        float-float  token_lev  0.104305
 5   all_MiniLM_L6_v2  type_pair        float-float   num_dist  0.230249
 6   all_MiniLM_L6_v2  type_pair          float-int   char_lev  0.171122
 7   all_MiniLM_L6_v2  type_pair          float-int  token_lev  0.101823
 8   all_MiniLM_L6_v2  type_pair          float-int   num_dist  0.287474
 9   all_MiniLM_L6_v2  type_pair            int-int   char_lev  0.442376
 10  all_MiniLM_L6_v2  type_pair            int-int  token_lev  0.370988
 11  all_MiniLM_L6_v2  type_pair            int-int   num_dist  0.390081
 12  all_MiniLM_L6_v2  same_sign              False   char_lev  0.084570
 13  all_MiniLM_L6_v2  same_sign              False  token_lev -0.010239
 14  all_MiniLM_L6_v2  same_sign              False   num_dist -0.115432
 15  all_MiniLM_L6_v2  same_sign               True   char_lev  0.239265
 16  all_MiniLM_L6_v2  same_sign               True  token_lev  0.196791
 17  all_MiniLM_L6_v2  same_sign               True   num_dist  0.226048
 18  all_MiniLM_L6_v2  sign_pair  negative-negative   char_lev  0.315085
 19  all_MiniLM_L6_v2  sign_pair  negative-negative  token_lev  0.216205
 20  all_MiniLM_L6_v2  sign_pair  negative-negative   num_dist  0.285081
 21  all_MiniLM_L6_v2  sign_pair  negative-positive   char_lev  0.102238
 22  all_MiniLM_L6_v2  sign_pair  negative-positive  token_lev  0.000165
 23  all_MiniLM_L6_v2  sign_pair  negative-positive   num_dist -0.085269
 24  all_MiniLM_L6_v2  sign_pair  positive-negative   char_lev  0.133314
 25  all_MiniLM_L6_v2  sign_pair  positive-negative  token_lev  0.009524
 26  all_MiniLM_L6_v2  sign_pair  positive-negative   num_dist -0.168280
 27  all_MiniLM_L6_v2  sign_pair  positive-positive   char_lev  0.261396
 28  all_MiniLM_L6_v2  sign_pair  positive-positive  token_lev  0.174499
 29  all_MiniLM_L6_v2  sign_pair  positive-positive   num_dist  0.215500

     n_pairs
 0      4950
 1      4950
 2      4950
 3      1225
 4      1225
 5      1225
 6      2500
 7      2500
 8      2500
 9      1225
 10     1225
 11     1225
 12     2491
 13     2491
 14     2491
 15     2459
 16     2459
 17     2459
 18     1378
 19     1378
 20     1378
 21     1327
 22     1327
 23     1327
 24     1164
 25     1164
 26     1164
 27     1081
 28     1081
 29     1081  ,
 'all_mpnet_base_v2':                 model group_type              group  reference       tau  \
 0   all_mpnet_base_v2    overall                all   char_lev  0.276966
 1   all_mpnet_base_v2    overall                all  token_lev  0.203585
 2   all_mpnet_base_v2    overall                all   num_dist  0.260928
 3   all_mpnet_base_v2  type_pair        float-float   char_lev  0.317357
 4   all_mpnet_base_v2  type_pair        float-float  token_lev  0.199382
 5   all_mpnet_base_v2  type_pair        float-float   num_dist  0.409068
 6   all_mpnet_base_v2  type_pair          float-int   char_lev  0.209549
 7   all_mpnet_base_v2  type_pair          float-int  token_lev  0.087179
 8   all_mpnet_base_v2  type_pair          float-int   num_dist  0.260175
 9   all_mpnet_base_v2  type_pair            int-int   char_lev  0.419336
 10  all_mpnet_base_v2  type_pair            int-int  token_lev  0.339864
 11  all_mpnet_base_v2  type_pair            int-int   num_dist  0.362390
 12  all_mpnet_base_v2  same_sign              False   char_lev  0.217190
 13  all_mpnet_base_v2  same_sign              False  token_lev  0.101153
 14  all_mpnet_base_v2  same_sign              False   num_dist -0.116932
 15  all_mpnet_base_v2  same_sign               True   char_lev  0.298794
 16  all_mpnet_base_v2  same_sign               True  token_lev  0.230701
 17  all_mpnet_base_v2  same_sign               True   num_dist  0.149134
 18  all_mpnet_base_v2  sign_pair  negative-negative   char_lev  0.405678
 19  all_mpnet_base_v2  sign_pair  negative-negative  token_lev  0.284958
 20  all_mpnet_base_v2  sign_pair  negative-negative   num_dist  0.165650
 21  all_mpnet_base_v2  sign_pair  negative-positive   char_lev  0.268241
 22  all_mpnet_base_v2  sign_pair  negative-positive  token_lev  0.166657
 23  all_mpnet_base_v2  sign_pair  negative-positive   num_dist -0.059305
 24  all_mpnet_base_v2  sign_pair  positive-negative   char_lev  0.155678
 25  all_mpnet_base_v2  sign_pair  positive-negative  token_lev -0.001197
 26  all_mpnet_base_v2  sign_pair  positive-negative   num_dist -0.195943
 27  all_mpnet_base_v2  sign_pair  positive-positive   char_lev  0.292263
 28  all_mpnet_base_v2  sign_pair  positive-positive  token_lev  0.171760
 29  all_mpnet_base_v2  sign_pair  positive-positive   num_dist  0.158455

     n_pairs
 0      4950
 1      4950
 2      4950
 3      1225
 4      1225
 5      1225
 6      2500
 7      2500
 8      2500
 9      1225
 10     1225
 11     1225
 12     2491
 13     2491
 14     2491
 15     2459
 16     2459
 17     2459
 18     1378
 19     1378
 20     1378
 21     1327
 22     1327
 23     1327
 24     1164
 25     1164
 26     1164
 27     1081
 28     1081
 29     1081  ,
 'e5_large_v2':           model group_type              group  reference       tau  n_pairs
 0   e5_large_v2    overall                all   char_lev  0.289815     4950
 1   e5_large_v2    overall                all  token_lev  0.219934     4950
 2   e5_large_v2    overall                all   num_dist  0.169364     4950
 3   e5_large_v2  type_pair        float-float   char_lev  0.238916     1225
 4   e5_large_v2  type_pair        float-float  token_lev  0.152302     1225
 5   e5_large_v2  type_pair        float-float   num_dist  0.181860     1225
 6   e5_large_v2  type_pair          float-int   char_lev  0.272215     2500
 7   e5_large_v2  type_pair          float-int  token_lev  0.144878     2500
 8   e5_large_v2  type_pair          float-int   num_dist  0.152897     2500
 9   e5_large_v2  type_pair            int-int   char_lev  0.450794     1225
 10  e5_large_v2  type_pair            int-int  token_lev  0.387016     1225
 11  e5_large_v2  type_pair            int-int   num_dist  0.328140     1225
 12  e5_large_v2  same_sign              False   char_lev  0.212335     2491
 13  e5_large_v2  same_sign              False  token_lev  0.103335     2491
 14  e5_large_v2  same_sign              False   num_dist -0.045165     2491
 15  e5_large_v2  same_sign               True   char_lev  0.358338     2459
 16  e5_large_v2  same_sign               True  token_lev  0.310149     2459
 17  e5_large_v2  same_sign               True   num_dist  0.110263     2459
 18  e5_large_v2  sign_pair  negative-negative   char_lev  0.533553     1378
 19  e5_large_v2  sign_pair  negative-negative  token_lev  0.460514     1378
 20  e5_large_v2  sign_pair  negative-negative   num_dist  0.118086     1378
 21  e5_large_v2  sign_pair  negative-positive   char_lev  0.282982     1327
 22  e5_large_v2  sign_pair  negative-positive  token_lev  0.187155     1327
 23  e5_large_v2  sign_pair  negative-positive   num_dist -0.017684     1327
 24  e5_large_v2  sign_pair  positive-negative   char_lev  0.085462     1164
 25  e5_large_v2  sign_pair  positive-negative  token_lev -0.054334     1164
 26  e5_large_v2  sign_pair  positive-negative   num_dist -0.076588     1164
 27  e5_large_v2  sign_pair  positive-positive   char_lev  0.377777     1081
 28  e5_large_v2  sign_pair  positive-positive  token_lev  0.229506     1081
 29  e5_large_v2  sign_pair  positive-positive   num_dist  0.093327     1081,
 'bge_large_en_v1.5':                 model group_type              group  reference       tau  \
 0   bge_large_en_v1.5    overall                all   char_lev  0.108600
 1   bge_large_en_v1.5    overall                all  token_lev  0.076706
 2   bge_large_en_v1.5    overall                all   num_dist  0.080009
 3   bge_large_en_v1.5  type_pair        float-float   char_lev  0.252062
 4   bge_large_en_v1.5  type_pair        float-float  token_lev  0.229067
 5   bge_large_en_v1.5  type_pair        float-float   num_dist  0.265213
 6   bge_large_en_v1.5  type_pair          float-int   char_lev  0.290833
 7   bge_large_en_v1.5  type_pair          float-int  token_lev  0.311191
 8   bge_large_en_v1.5  type_pair          float-int   num_dist  0.069228
 9   bge_large_en_v1.5  type_pair            int-int   char_lev  0.351784
 10  bge_large_en_v1.5  type_pair            int-int  token_lev  0.184607
 11  bge_large_en_v1.5  type_pair            int-int   num_dist  0.185502
 12  bge_large_en_v1.5  same_sign              False   char_lev  0.058437
 13  bge_large_en_v1.5  same_sign              False  token_lev  0.008275
 14  bge_large_en_v1.5  same_sign              False   num_dist  0.005143
 15  bge_large_en_v1.5  same_sign               True   char_lev  0.150944
 16  bge_large_en_v1.5  same_sign               True  token_lev  0.125321
 17  bge_large_en_v1.5  same_sign               True   num_dist  0.083559
 18  bge_large_en_v1.5  sign_pair  negative-negative   char_lev  0.197970
 19  bge_large_en_v1.5  sign_pair  negative-negative  token_lev  0.176605
 20  bge_large_en_v1.5  sign_pair  negative-negative   num_dist  0.091288
 21  bge_large_en_v1.5  sign_pair  negative-positive   char_lev  0.175010
 22  bge_large_en_v1.5  sign_pair  negative-positive  token_lev  0.106545
 23  bge_large_en_v1.5  sign_pair  negative-positive   num_dist  0.034223
 24  bge_large_en_v1.5  sign_pair  positive-negative   char_lev -0.128461
 25  bge_large_en_v1.5  sign_pair  positive-negative  token_lev -0.116070
 26  bge_large_en_v1.5  sign_pair  positive-negative   num_dist -0.011094
 27  bge_large_en_v1.5  sign_pair  positive-positive   char_lev  0.129622
 28  bge_large_en_v1.5  sign_pair  positive-positive  token_lev  0.072225
 29  bge_large_en_v1.5  sign_pair  positive-positive   num_dist  0.069674

     n_pairs
 0      4950
 1      4950
 2      4950
 3      1225
 4      1225
 5      1225
 6      2500
 7      2500
 8      2500
 9      1225
 10     1225
 11     1225
 12     2491
 13     2491
 14     2491
 15     2459
 16     2459
 17     2459
 18     1378
 19     1378
 20     1378
 21     1327
 22     1327
 23     1327
 24     1164
 25     1164
 26     1164
 27     1081
 28     1081
 29     1081  ,
 'nomic_embed_text_v1.5':                     model group_type              group  reference       tau  \
 0   nomic_embed_text_v1.5    overall                all   char_lev -0.055534
 1   nomic_embed_text_v1.5    overall                all  token_lev -0.168959
 2   nomic_embed_text_v1.5    overall                all   num_dist  0.064583
 3   nomic_embed_text_v1.5  type_pair        float-float   char_lev  0.169500
 4   nomic_embed_text_v1.5  type_pair        float-float  token_lev -0.037088
 5   nomic_embed_text_v1.5  type_pair        float-float   num_dist  0.057788
 6   nomic_embed_text_v1.5  type_pair          float-int   char_lev  0.289471
 7   nomic_embed_text_v1.5  type_pair          float-int  token_lev  0.056523
 8   nomic_embed_text_v1.5  type_pair          float-int   num_dist  0.058924
 9   nomic_embed_text_v1.5  type_pair            int-int   char_lev  0.328081
 10  nomic_embed_text_v1.5  type_pair            int-int  token_lev  0.175485
 11  nomic_embed_text_v1.5  type_pair            int-int   num_dist  0.152269
 12  nomic_embed_text_v1.5  same_sign              False   char_lev -0.085888
 13  nomic_embed_text_v1.5  same_sign              False  token_lev -0.213843
 14  nomic_embed_text_v1.5  same_sign              False   num_dist -0.075708
 15  nomic_embed_text_v1.5  same_sign               True   char_lev -0.032052
 16  nomic_embed_text_v1.5  same_sign               True  token_lev -0.148463
 17  nomic_embed_text_v1.5  same_sign               True   num_dist  0.163207
 18  nomic_embed_text_v1.5  sign_pair  negative-negative   char_lev -0.041473
 19  nomic_embed_text_v1.5  sign_pair  negative-negative  token_lev -0.179513
 20  nomic_embed_text_v1.5  sign_pair  negative-negative   num_dist  0.240850
 21  nomic_embed_text_v1.5  sign_pair  negative-positive   char_lev -0.001329
 22  nomic_embed_text_v1.5  sign_pair  negative-positive  token_lev -0.136740
 23  nomic_embed_text_v1.5  sign_pair  negative-positive   num_dist -0.047872
 24  nomic_embed_text_v1.5  sign_pair  positive-negative   char_lev -0.225042
 25  nomic_embed_text_v1.5  sign_pair  positive-negative  token_lev -0.347883
 26  nomic_embed_text_v1.5  sign_pair  positive-negative   num_dist -0.109806
 27  nomic_embed_text_v1.5  sign_pair  positive-positive   char_lev -0.049423
 28  nomic_embed_text_v1.5  sign_pair  positive-positive  token_lev -0.196333
 29  nomic_embed_text_v1.5  sign_pair  positive-positive   num_dist  0.088749

     n_pairs
 0      4950
 1      4950
 2      4950
 3      1225
 4      1225
 5      1225
 6      2500
 7      2500
 8      2500
 9      1225
 10     1225
 11     1225
 12     2491
 13     2491
 14     2491
 15     2459
 16     2459
 17     2459
 18     1378
 19     1378
 20     1378
 21     1327
 22     1327
 23     1327
 24     1164
 25     1164
 26     1164
 27     1081
 28     1081
 29     1081  ,
 'Qwen3_Embedding_0.6B':                    model group_type              group  reference       tau  \
 0   Qwen3_Embedding_0.6B    overall                all   char_lev  0.475902
 1   Qwen3_Embedding_0.6B    overall                all  token_lev  0.475902
 2   Qwen3_Embedding_0.6B    overall                all   num_dist  0.116978
 3   Qwen3_Embedding_0.6B  type_pair        float-float   char_lev  0.236396
 4   Qwen3_Embedding_0.6B  type_pair        float-float  token_lev  0.236396
 5   Qwen3_Embedding_0.6B  type_pair        float-float   num_dist  0.136647
 6   Qwen3_Embedding_0.6B  type_pair          float-int   char_lev  0.306824
 7   Qwen3_Embedding_0.6B  type_pair          float-int  token_lev  0.306824
 8   Qwen3_Embedding_0.6B  type_pair          float-int   num_dist  0.137218
 9   Qwen3_Embedding_0.6B  type_pair            int-int   char_lev  0.507947
 10  Qwen3_Embedding_0.6B  type_pair            int-int  token_lev  0.507947
 11  Qwen3_Embedding_0.6B  type_pair            int-int   num_dist  0.251888
 12  Qwen3_Embedding_0.6B  same_sign              False   char_lev  0.433850
 13  Qwen3_Embedding_0.6B  same_sign              False  token_lev  0.433850
 14  Qwen3_Embedding_0.6B  same_sign              False   num_dist -0.125890
 15  Qwen3_Embedding_0.6B  same_sign               True   char_lev  0.494935
 16  Qwen3_Embedding_0.6B  same_sign               True  token_lev  0.494935
 17  Qwen3_Embedding_0.6B  same_sign               True   num_dist  0.134743
 18  Qwen3_Embedding_0.6B  sign_pair  negative-negative   char_lev  0.517876
 19  Qwen3_Embedding_0.6B  sign_pair  negative-negative  token_lev  0.517876
 20  Qwen3_Embedding_0.6B  sign_pair  negative-negative   num_dist  0.192381
 21  Qwen3_Embedding_0.6B  sign_pair  negative-positive   char_lev  0.469826
 22  Qwen3_Embedding_0.6B  sign_pair  negative-positive  token_lev  0.469826
 23  Qwen3_Embedding_0.6B  sign_pair  negative-positive   num_dist -0.086879
 24  Qwen3_Embedding_0.6B  sign_pair  positive-negative   char_lev  0.442376
 25  Qwen3_Embedding_0.6B  sign_pair  positive-negative  token_lev  0.442376
 26  Qwen3_Embedding_0.6B  sign_pair  positive-negative   num_dist -0.182141
 27  Qwen3_Embedding_0.6B  sign_pair  positive-positive   char_lev  0.479373
 28  Qwen3_Embedding_0.6B  sign_pair  positive-positive  token_lev  0.479373
 29  Qwen3_Embedding_0.6B  sign_pair  positive-positive   num_dist  0.076794

     n_pairs
 0      4950
 1      4950
 2      4950
 3      1225
 4      1225
 5      1225
 6      2500
 7      2500
 8      2500
 9      1225
 10     1225
 11     1225
 12     2491
 13     2491
 14     2491
 15     2459
 16     2459
 17     2459
 18     1378
 19     1378
 20     1378
 21     1327
 22     1327
 23     1327
 24     1164
 25     1164
 26     1164
 27     1081
 28     1081
 29     1081  ,
 'Qwen3_Embedding_4B':                  model group_type              group  reference       tau  \
 0   Qwen3_Embedding_4B    overall                all   char_lev  0.301487
 1   Qwen3_Embedding_4B    overall                all  token_lev  0.301487
 2   Qwen3_Embedding_4B    overall                all   num_dist  0.130511
 3   Qwen3_Embedding_4B  type_pair        float-float   char_lev  0.263178
 4   Qwen3_Embedding_4B  type_pair        float-float  token_lev  0.263178
 5   Qwen3_Embedding_4B  type_pair        float-float   num_dist  0.125548
 6   Qwen3_Embedding_4B  type_pair          float-int   char_lev  0.387547
 7   Qwen3_Embedding_4B  type_pair          float-int  token_lev  0.387547
 8   Qwen3_Embedding_4B  type_pair          float-int   num_dist  0.084222
 9   Qwen3_Embedding_4B  type_pair            int-int   char_lev  0.537522
 10  Qwen3_Embedding_4B  type_pair            int-int  token_lev  0.537522
 11  Qwen3_Embedding_4B  type_pair            int-int   num_dist  0.273403
 12  Qwen3_Embedding_4B  same_sign              False   char_lev  0.205481
 13  Qwen3_Embedding_4B  same_sign              False  token_lev  0.205481
 14  Qwen3_Embedding_4B  same_sign              False   num_dist -0.174118
 15  Qwen3_Embedding_4B  same_sign               True   char_lev  0.368089
 16  Qwen3_Embedding_4B  same_sign               True  token_lev  0.368089
 17  Qwen3_Embedding_4B  same_sign               True   num_dist  0.181442
 18  Qwen3_Embedding_4B  sign_pair  negative-negative   char_lev  0.383098
 19  Qwen3_Embedding_4B  sign_pair  negative-negative  token_lev  0.383098
 20  Qwen3_Embedding_4B  sign_pair  negative-negative   num_dist  0.255742
 21  Qwen3_Embedding_4B  sign_pair  negative-positive   char_lev  0.245578
 22  Qwen3_Embedding_4B  sign_pair  negative-positive  token_lev  0.245578
 23  Qwen3_Embedding_4B  sign_pair  negative-positive   num_dist -0.151915
 24  Qwen3_Embedding_4B  sign_pair  positive-negative   char_lev  0.177710
 25  Qwen3_Embedding_4B  sign_pair  positive-negative  token_lev  0.177710
 26  Qwen3_Embedding_4B  sign_pair  positive-negative   num_dist -0.196157
 27  Qwen3_Embedding_4B  sign_pair  positive-positive   char_lev  0.405031
 28  Qwen3_Embedding_4B  sign_pair  positive-positive  token_lev  0.405031
 29  Qwen3_Embedding_4B  sign_pair  positive-positive   num_dist  0.092193

     n_pairs
 0      4950
 1      4950
 2      4950
 3      1225
 4      1225
 5      1225
 6      2500
 7      2500
 8      2500
 9      1225
 10     1225
 11     1225
 12     2491
 13     2491
 14     2491
 15     2459
 16     2459
 17     2459
 18     1378
 19     1378
 20     1378
 21     1327
 22     1327
 23     1327
 24     1164
 25     1164
 26     1164
 27     1081
 28     1081
 29     1081  ,
 'Qwen3_Embedding_8B':                  model group_type              group  reference       tau  \
 0   Qwen3_Embedding_8B    overall                all   char_lev  0.366878
 1   Qwen3_Embedding_8B    overall                all  token_lev  0.366878
 2   Qwen3_Embedding_8B    overall                all   num_dist  0.183117
 3   Qwen3_Embedding_8B  type_pair        float-float   char_lev  0.339270
 4   Qwen3_Embedding_8B  type_pair        float-float  token_lev  0.339270
 5   Qwen3_Embedding_8B  type_pair        float-float   num_dist  0.241801
 6   Qwen3_Embedding_8B  type_pair          float-int   char_lev  0.391643
 7   Qwen3_Embedding_8B  type_pair          float-int  token_lev  0.391643
 8   Qwen3_Embedding_8B  type_pair          float-int   num_dist  0.157558
 9   Qwen3_Embedding_8B  type_pair            int-int   char_lev  0.494698
 10  Qwen3_Embedding_8B  type_pair            int-int  token_lev  0.494698
 11  Qwen3_Embedding_8B  type_pair            int-int   num_dist  0.250671

### Run: extended models

Add model names to `NEW_MODELS` to extend the paper.

#### PT1

In [ ]:
# Extended run: add model names here to extend the paper.
NEW_MODELS_1 = [
    "sentence-transformers/LaBSE",
    "sentence-transformers/paraphrase-multilingual-mpnet-base-v2",
    "intfloat/multilingual-e5-base",
    "intfloat/multilingual-e5-large",
    "intfloat/multilingual-e5-large-instruct",
    "BAAI/bge-m3",
    "google/embeddinggemma-300m",
]

run_lexical(NEW_MODELS_1)

================================================================================
sentence-transformers/LaBSE

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   39.6         32.7       28.5     48.7
num_dist   18.1         29.7       18.8     24.4
token_lev  42.7         42.0       13.0     35.7

================================================================================
sentence-transformers/paraphrase-multilingual-mpnet-base-v2

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev    5.0         17.8       19.8     29.7
num_dist    8.1         14.4        7.0      8.2
token_lev -11.5         -5.0        3.7      6.4

================================================================================
intfloat/multilingual-e5-base

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   23.5         32.6       34.3     50.3
num_dist   17.2         24.1       23.3     25.4
token_lev   6.8         27.3       13.6     27.7

================================================================================
intfloat/multilingual-e5-large

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   25.5         32.4       29.4     50.1
num_dist   18.4         37.4       26.9     24.9
token_lev   6.8         24.9        0.9     31.2

================================================================================
intfloat/multilingual-e5-large-instruct

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   39.7         28.1       29.4     40.4
num_dist   26.9         49.1       29.9     30.7
token_lev  27.5         25.3       15.9     22.4

================================================================================
BAAI/bge-m3

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   18.1         31.3       36.8     49.2
num_dist   19.5         34.3       22.7     29.7
token_lev   3.6         25.0       25.7     31.9

================================================================================
google/embeddinggemma-300m

Loading weights:   0%|          | 0/314 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   51.6         36.3       39.6     44.6
num_dist    3.3          8.3        2.1      8.8
token_lev  51.6         36.3       39.6     44.6

Wrote per-model CSVs. Build the LaTeX table with table_lexical().

{'LaBSE':     model group_type              group  reference       tau  n_pairs
 0   LaBSE    overall                all   char_lev  0.395809     4950
 1   LaBSE    overall                all  token_lev  0.427459     4950
 2   LaBSE    overall                all   num_dist  0.180788     4950
 3   LaBSE  type_pair        float-float   char_lev  0.327291     1225
 4   LaBSE  type_pair        float-float  token_lev  0.420275     1225
 5   LaBSE  type_pair        float-float   num_dist  0.297079     1225
 6   LaBSE  type_pair          float-int   char_lev  0.285077     2500
 7   LaBSE  type_pair          float-int  token_lev  0.130356     2500
 8   LaBSE  type_pair          float-int   num_dist  0.188060     2500
 9   LaBSE  type_pair            int-int   char_lev  0.486978     1225
 10  LaBSE  type_pair            int-int  token_lev  0.357097     1225
 11  LaBSE  type_pair            int-int   num_dist  0.244031     1225
 12  LaBSE  same_sign              False   char_lev  0.391798     2491
 13  LaBSE  same_sign              False  token_lev  0.361992     2491
 14  LaBSE  same_sign              False   num_dist -0.113886     2491
 15  LaBSE  same_sign               True   char_lev  0.380889     2459
 16  LaBSE  same_sign               True  token_lev  0.451765     2459
 17  LaBSE  same_sign               True   num_dist  0.173281     2459
 18  LaBSE  sign_pair  negative-negative   char_lev  0.481651     1378
 19  LaBSE  sign_pair  negative-negative  token_lev  0.523496     1378
 20  LaBSE  sign_pair  negative-negative   num_dist  0.200107     1378
 21  LaBSE  sign_pair  negative-positive   char_lev  0.480435     1327
 22  LaBSE  sign_pair  negative-positive  token_lev  0.507121     1327
 23  LaBSE  sign_pair  negative-positive   num_dist -0.089227     1327
 24  LaBSE  sign_pair  positive-negative   char_lev  0.372042     1164
 25  LaBSE  sign_pair  positive-negative  token_lev  0.349627     1164
 26  LaBSE  sign_pair  positive-negative   num_dist -0.147413     1164
 27  LaBSE  sign_pair  positive-positive   char_lev  0.441211     1081
 28  LaBSE  sign_pair  positive-positive  token_lev  0.517087     1081
 29  LaBSE  sign_pair  positive-positive   num_dist  0.151719     1081,
 'paraphrase_multilingual_mpnet_base_v2':                                     model group_type              group  \
 0   paraphrase_multilingual_mpnet_base_v2    overall                all
 1   paraphrase_multilingual_mpnet_base_v2    overall                all
 2   paraphrase_multilingual_mpnet_base_v2    overall                all
 3   paraphrase_multilingual_mpnet_base_v2  type_pair        float-float
 4   paraphrase_multilingual_mpnet_base_v2  type_pair        float-float
 5   paraphrase_multilingual_mpnet_base_v2  type_pair        float-float
 6   paraphrase_multilingual_mpnet_base_v2  type_pair          float-int
 7   paraphrase_multilingual_mpnet_base_v2  type_pair          float-int
 8   paraphrase_multilingual_mpnet_base_v2  type_pair          float-int
 9   paraphrase_multilingual_mpnet_base_v2  type_pair            int-int
 10  paraphrase_multilingual_mpnet_base_v2  type_pair            int-int
 11  paraphrase_multilingual_mpnet_base_v2  type_pair            int-int
 12  paraphrase_multilingual_mpnet_base_v2  same_sign              False
 13  paraphrase_multilingual_mpnet_base_v2  same_sign              False
 14  paraphrase_multilingual_mpnet_base_v2  same_sign              False
 15  paraphrase_multilingual_mpnet_base_v2  same_sign               True
 16  paraphrase_multilingual_mpnet_base_v2  same_sign               True
 17  paraphrase_multilingual_mpnet_base_v2  same_sign               True
 18  paraphrase_multilingual_mpnet_base_v2  sign_pair  negative-negative
 19  paraphrase_multilingual_mpnet_base_v2  sign_pair  negative-negative
 20  paraphrase_multilingual_mpnet_base_v2  sign_pair  negative-negative
 21  paraphrase_multilingual_mpnet_base_v2  sign_pair  negative-positive
 22  paraphrase_multilingual_mpnet_base_v2  sign_pair  negative-positive
 23  paraphrase_multilingual_mpnet_base_v2  sign_pair  negative-positive
 24  paraphrase_multilingual_mpnet_base_v2  sign_pair  positive-negative
 25  paraphrase_multilingual_mpnet_base_v2  sign_pair  positive-negative
 26  paraphrase_multilingual_mpnet_base_v2  sign_pair  positive-negative
 27  paraphrase_multilingual_mpnet_base_v2  sign_pair  positive-positive
 28  paraphrase_multilingual_mpnet_base_v2  sign_pair  positive-positive
 29  paraphrase_multilingual_mpnet_base_v2  sign_pair  positive-positive

     reference       tau  n_pairs
 0    char_lev  0.050281     4950
 1   token_lev -0.114879     4950
 2    num_dist  0.080662     4950
 3    char_lev  0.178361     1225
 4   token_lev -0.049768     1225
 5    num_dist  0.144124     1225
 6    char_lev  0.197976     2500
 7   token_lev  0.036709     2500
 8    num_dist  0.069609     2500
 9    char_lev  0.296990     1225
 10  token_lev  0.063914     1225
 11   num_dist  0.082002     1225
 12   char_lev  0.011355     2491
 13  token_lev -0.181951     2491
 14   num_dist -0.248642     2491
 15   char_lev  0.047403     2459
 16  token_lev -0.119527     2459
 17   num_dist  0.234527     2459
 18   char_lev  0.016975     1378
 19  token_lev -0.131115     1378
 20   num_dist  0.253304     1378
 21   char_lev  0.064283     1327
 22  token_lev -0.099259     1327
 23   num_dist -0.217622     1327
 24   char_lev -0.037346     1164
 25  token_lev -0.273754     1164
 26   num_dist -0.285841     1164
 27   char_lev  0.091350     1081
 28  token_lev -0.116894     1081
 29   num_dist  0.212615     1081  ,
 'multilingual_e5_base':                    model group_type              group  reference       tau  \
 0   multilingual_e5_base    overall                all   char_lev  0.234631
 1   multilingual_e5_base    overall                all  token_lev  0.067578
 2   multilingual_e5_base    overall                all   num_dist  0.171890
 3   multilingual_e5_base  type_pair        float-float   char_lev  0.325613
 4   multilingual_e5_base  type_pair        float-float  token_lev  0.273276
 5   multilingual_e5_base  type_pair        float-float   num_dist  0.241119
 6   multilingual_e5_base  type_pair          float-int   char_lev  0.343390
 7   multilingual_e5_base  type_pair          float-int  token_lev  0.135879
 8   multilingual_e5_base  type_pair          float-int   num_dist  0.233195
 9   multilingual_e5_base  type_pair            int-int   char_lev  0.503066
 10  multilingual_e5_base  type_pair            int-int  token_lev  0.277256
 11  multilingual_e5_base  type_pair            int-int   num_dist  0.253655
 12  multilingual_e5_base  same_sign              False   char_lev  0.165098
 13  multilingual_e5_base  same_sign              False  token_lev -0.035176
 14  multilingual_e5_base  same_sign              False   num_dist  0.000631
 15  multilingual_e5_base  same_sign               True   char_lev  0.277385
 16  multilingual_e5_base  same_sign               True  token_lev  0.126392
 17  multilingual_e5_base  same_sign               True   num_dist  0.085613
 18  multilingual_e5_base  sign_pair  negative-negative   char_lev  0.359191
 19  multilingual_e5_base  sign_pair  negative-negative  token_lev  0.262597
 20  multilingual_e5_base  sign_pair  negative-negative   num_dist  0.077884
 21  multilingual_e5_base  sign_pair  negative-positive   char_lev  0.221651
 22  multilingual_e5_base  sign_pair  negative-positive  token_lev  0.071377
 23  multilingual_e5_base  sign_pair  negative-positive   num_dist  0.019031
 24  multilingual_e5_base  sign_pair  positive-negative   char_lev  0.133104
 25  multilingual_e5_base  sign_pair  positive-negative  token_lev -0.122384
 26  multilingual_e5_base  sign_pair  positive-negative   num_dist -0.026283
 27  multilingual_e5_base  sign_pair  positive-positive   char_lev  0.236635
 28  multilingual_e5_base  sign_pair  positive-positive  token_lev -0.017893
 29  multilingual_e5_base  sign_pair  positive-positive   num_dist  0.084995

     n_pairs
 0      4950
 1      4950
 2      4950
 3      1225
 4      1225
 5      1225
 6      2500
 7      2500
 8      2500
 9      1225
 10     1225
 11     1225
 12     2491
 13     2491
 14     2491
 15     2459
 16     2459
 17     2459
 18     1378
 19     1378
 20     1378
 21     1327
 22     1327
 23     1327
 24     1164
 25     1164
 26     1164
 27     1081
 28     1081
 29     1081  ,
 'multilingual_e5_large':                     model group_type              group  reference       tau  \
 0   multilingual_e5_large    overall                all   char_lev  0.254556
 1   multilingual_e5_large    overall                all  token_lev  0.068153
 2   multilingual_e5_large    overall                all   num_dist  0.183733
 3   multilingual_e5_large  type_pair        float-float   char_lev  0.323992
 4   multilingual_e5_large  type_pair        float-float  token_lev  0.248644
 5   multilingual_e5_large  type_pair        float-float   num_dist  0.373969
 6   multilingual_e5_large  type_pair          float-int   char_lev  0.294489
 7   multilingual_e5_large  type_pair          float-int  token_lev  0.009130
 8   multilingual_e5_large  type_pair          float-int   num_dist  0.268593
 9   multilingual_e5_large  type_pair            int-int   char_lev  0.501332
 10  multilingual_e5_large  type_pair            int-int  token_lev  0.311888
 11  multilingual_e5_large  type_pair            int-int   num_dist  0.248661
 12  multilingual_e5_large  same_sign              False   char_lev  0.175145
 13  multilingual_e5_large  same_sign              False  token_lev -0.045069
 14  multilingual_e5_large  same_sign              False   num_dist  0.028280
 15  multilingual_e5_large  same_sign               True   char_lev  0.305345
 16  multilingual_e5_large  same_sign               True  token_lev  0.133811
 17  multilingual_e5_large  same_sign               True   num_dist  0.097899
 18  multilingual_e5_large  sign_pair  negative-negative   char_lev  0.372822
 19  multilingual_e5_large  sign_pair  negative-negative  token_lev  0.244357
 20  multilingual_e5_large  sign_pair  negative-negative   num_dist  0.086717
 21  multilingual_e5_large  sign_pair  negative-positive   char_lev  0.218370
 22  multilingual_e5_large  sign_pair  negative-positive  token_lev  0.059072
 23  multilingual_e5_large  sign_pair  negative-positive   num_dist  0.013070
 24  multilingual_e5_large  sign_pair  positive-negative   char_lev  0.236665
 25  multilingual_e5_large  sign_pair  positive-negative  token_lev -0.043528
 26  multilingual_e5_large  sign_pair  positive-negative   num_dist  0.038707
 27  multilingual_e5_large  sign_pair  positive-positive   char_lev  0.290205
 28  multilingual_e5_large  sign_pair  positive-positive  token_lev  0.014784
 29  multilingual_e5_large  sign_pair  positive-positive   num_dist  0.102024

     n_pairs
 0      4950
 1      4950
 2      4950
 3      1225
 4      1225
 5      1225
 6      2500
 7      2500
 8      2500
 9      1225
 10     1225
 11     1225
 12     2491
 13     2491
 14     2491
 15     2459
 16     2459
 17     2459
 18     1378
 19     1378
 20     1378
 21     1327
 22     1327
 23     1327
 24     1164
 25     1164
 26     1164
 27     1081
 28     1081
 29     1081  ,
 'multilingual_e5_large_instruct':                              model group_type              group  reference  \
 0   multilingual_e5_large_instruct    overall                all   char_lev
 1   multilingual_e5_large_instruct    overall                all  token_lev
 2   multilingual_e5_large_instruct    overall                all   num_dist
 3   multilingual_e5_large_instruct  type_pair        float-float   char_lev
 4   multilingual_e5_large_instruct  type_pair        float-float  token_lev
 5   multilingual_e5_large_instruct  type_pair        float-float   num_dist
 6   multilingual_e5_large_instruct  type_pair          float-int   char_lev
 7   multilingual_e5_large_instruct  type_pair          float-int  token_lev
 8   multilingual_e5_large_instruct  type_pair          float-int   num_dist
 9   multilingual_e5_large_instruct  type_pair            int-int   char_lev
 10  multilingual_e5_large_instruct  type_pair            int-int  token_lev
 11  multilingual_e5_large_instruct  type_pair            int-int   num_dist
 12  multilingual_e5_large_instruct  same_sign              False   char_lev
 13  multilingual_e5_large_instruct  same_sign              False  token_lev
 14  multilingual_e5_large_instruct  same_sign              False   num_dist
 15  multilingual_e5_large_instruct  same_sign               True   char_lev
 16  multilingual_e5_large_instruct  same_sign               True  token_lev
 17  multilingual_e5_large_instruct  same_sign               True   num_dist
 18  multilingual_e5_large_instruct  sign_pair  negative-negative   char_lev
 19  multilingual_e5_large_instruct  sign_pair  negative-negative  token_lev
 20  multilingual_e5_large_instruct  sign_pair  negative-negative   num_dist
 21  multilingual_e5_large_instruct  sign_pair  negative-positive   char_lev
 22  multilingual_e5_large_instruct  sign_pair  negative-positive  token_lev
 23  multilingual_e5_large_instruct  sign_pair  negative-positive   num_dist
 24  multilingual_e5_large_instruct  sign_pair  positive-negative   char_lev
 25  multilingual_e5_large_instruct  sign_pair  positive-negative  token_lev
 26  multilingual_e5_large_instruct  sign_pair  positive-negative   num_dist
 27  multilingual_e5_large_instruct  sign_pair  positive-positive   char_lev
 28  multilingual_e5_large_instruct  sign_pair  positive-positive  token_lev
 29  multilingual_e5_large_instruct  sign_pair  positive-positive   num_dist

          tau  n_pairs
 0   0.396572     4950
 1   0.275374     4950
 2   0.268549     4950
 3   0.281273     1225
 4   0.252662     1225
 5   0.490975     1225
 6   0.294391     2500
 7   0.158803     2500
 8   0.299179     2500
 9   0.404422     1225
 10  0.223799     1225
 11  0.306555     1225
 12  0.431094     2491
 13  0.288420     2491
 14  0.073504     2491
 15  0.362208     2459
 16  0.243997     2459
 17  0.160861     2459
 18  0.479531     1378
 19  0.396132     1378
 20  0.163594     1378
 21  0.489301     1327
 22  0.397250     1327
 23  0.058396     1327
 24  0.315471     1164
 25  0.107087     1164
 26  0.109891     1164
 27  0.426365     1081
 28  0.182529     1081
 29  0.182045     1081  ,
 'bge_m3':      model group_type              group  reference       tau  n_pairs
 0   bge_m3    overall                all   char_lev  0.181454     4950
 1   bge_m3    overall                all  token_lev  0.035597     4950
 2   bge_m3    overall                all   num_dist  0.194906     4950
 3   bge_m3  type_pair        float-float   char_lev  0.312976     1225
 4   bge_m3  type_pair        float-float  token_lev  0.250220     1225
 5   bge_m3  type_pair        float-float   num_dist  0.343411     1225
 6   bge_m3  type_pair          float-int   char_lev  0.367814     2500
 7   bge_m3  type_pair          float-int  token_lev  0.257131     2500
 8   bge_m3  type_pair          float-int   num_dist  0.226805     2500
 9   bge_m3  type_pair            int-int   char_lev  0.492235     1225
 10  bge_m3  type_pair            int-int  token_lev  0.319221     1225
 11  bge_m3  type_pair            int-int   num_dist  0.297152     1225
 12  bge_m3  same_sign              False   char_lev  0.108325     2491
 13  bge_m3  same_sign              False  token_lev -0.082731     2491
 14  bge_m3  same_sign              False   num_dist -0.048136     2491
 15  bge_m3  same_sign               True   char_lev  0.216968     2459
 16  bge_m3  same_sign               True  token_lev  0.102326     2459
 17  bge_m3  same_sign               True   num_dist  0.129501     2459
 18  bge_m3  sign_pair  negative-negative   char_lev  0.291832     1378
 19  bge_m3  sign_pair  negative-negative  token_lev  0.244789     1378
 20  bge_m3  sign_pair  negative-negative   num_dist  0.134654     1378
 21  bge_m3  sign_pair  negative-positive   char_lev  0.192439     1327
 22  bge_m3  sign_pair  negative-positive  token_lev  0.035412     1327
 23  bge_m3  sign_pair  negative-positive   num_dist -0.024885     1327
 24  bge_m3  sign_pair  positive-negative   char_lev -0.008924     1164
 25  bge_m3  sign_pair  positive-negative  token_lev -0.259156     1164
 26  bge_m3  sign_pair  positive-negative   num_dist -0.084820     1164
 27  bge_m3  sign_pair  positive-positive   char_lev  0.210262     1081
 28  bge_m3  sign_pair  positive-positive  token_lev -0.019903     1081
 29  bge_m3  sign_pair  positive-positive   num_dist  0.123380     1081,
 'embeddinggemma_300m':                   model group_type              group  reference       tau  \
 0   embeddinggemma_300m    overall                all   char_lev  0.515698
 1   embeddinggemma_300m    overall                all  token_lev  0.515698
 2   embeddinggemma_300m    overall                all   num_dist  0.033083
 3   embeddinggemma_300m  type_pair        float-float   char_lev  0.362895
 4   embeddinggemma_300m  type_pair        float-float  token_lev  0.362895
 5   embeddinggemma_300m  type_pair        float-float   num_dist  0.083148
 6   embeddinggemma_300m  type_pair          float-int   char_lev  0.395537
 7   embeddinggemma_300m  type_pair          float-int  token_lev  0.395537
 8   embeddinggemma_300m  type_pair          float-int   num_dist  0.021105
 9   embeddinggemma_300m  type_pair            int-int   char_lev  0.446250
 10  embeddinggemma_300m  type_pair            int-int  token_lev  0.446250
 11  embeddinggemma_300m  type_pair            int-int   num_dist  0.088068
 12  embeddinggemma_300m  same_sign              False   char_lev  0.513765
 13  embeddinggemma_300m  same_sign              False  token_lev  0.513765
 14  embeddinggemma_300m  same_sign              False   num_dist -0.050080
 15  embeddinggemma_300m  same_sign               True   char_lev  0.538087
 16  embeddinggemma_300m  same_sign               True  token_lev  0.538087
 17  embeddinggemma_300m  same_sign               True   num_dist  0.071424
 18  embeddinggemma_300m  sign_pair  negative-negative   char_lev  0.575900
 19  embeddinggemma_300m  sign_pair  negative-negative  token_lev  0.575900
 20  embeddinggemma_300m  sign_pair  negative-negative   num_dist  0.072637
 21  embeddinggemma_300m  sign_pair  negative-positive   char_lev  0.524924
 22  embeddinggemma_300m  sign_pair  negative-positive  token_lev  0.524924
 23  embeddinggemma_300m  sign_pair  negative-positive   num_dist -0.006639
 24  embeddinggemma_300m  sign_pair  positive-negative   char_lev  0.510440
 25  embeddinggemma_300m  sign_pair  positive-negative  token_lev  0.510440
 26  embeddinggemma_300m  sign_pair  positive-negative   num_dist -0.102156
 27  embeddinggemma_300m  sign_pair  positive-positive   char_lev  0.486451
 28  embeddinggemma_300m  sign_pair  positive-positive  token_lev  0.486451
 29  embeddinggemma_300m  sign_pair  positive-positive   num_dist  0.078117

     n_pairs
 0      4950
 1      4950
 2      4950
 3      1225
 4      1225
 5      1225
 6      2500
 7      2500
 8      2500
 9      1225
 10     1225
 11     1225
 12     2491
 13     2491
 14     2491
 15     2459
 16     2459
 17     2459
 18     1378
 19     1378
 20     1378
 21     1327
 22     1327
 23     1327
 24     1164
 25     1164
 26     1164
 27     1081
 28     1081
 29     1081  }

#### PT2

In [ ]:
NEW_MODELS_2 = [
    # "Alibaba-NLP/gte-multilingual-base",
    # "Alibaba-NLP/gte-large-en-v1.5",
    "ibm-granite/granite-embedding-107m-multilingual",
    "ibm-granite/granite-embedding-278m-multilingual",
    "ibm-granite/granite-embedding-english-r2",
    "ibm-granite/granite-embedding-97m-multilingual-r2",
    "ibm-granite/granite-embedding-311m-multilingual-r2",
]

run_lexical(NEW_MODELS_2)

================================================================================
ibm-granite/granite-embedding-107m-multilingual

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   27.0         25.9       32.4     43.1
num_dist   16.7         14.9       16.4     20.6
token_lev  16.7         10.9       14.1     31.0

================================================================================
ibm-granite/granite-embedding-278m-multilingual

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   29.4         25.1       33.2     46.3
num_dist   14.8         11.7       14.6     21.1
token_lev  16.3         11.8       14.5     25.2

================================================================================
ibm-granite/granite-embedding-english-r2

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   16.7         29.9       29.6     44.6
num_dist   14.4         20.5       10.8     22.6
token_lev   9.1         14.7        4.6     21.1

================================================================================
ibm-granite/granite-embedding-97m-multilingual-r2

Loading weights:   0%|          | 0/74 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev    4.9         17.5       11.9     27.9
num_dist   12.5         12.5       12.7     21.2
token_lev   8.5         18.9        2.5     29.3

================================================================================
ibm-granite/granite-embedding-311m-multilingual-r2

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   14.2         32.5       33.3     53.6
num_dist    9.1         17.0       10.4     11.8
token_lev  14.2         32.5       33.3     53.6

Wrote per-model CSVs. Build the LaTeX table with table_lexical().

{'granite_embedding_107m_multilingual':                                   model group_type              group  \
 0   granite_embedding_107m_multilingual    overall                all
 1   granite_embedding_107m_multilingual    overall                all
 2   granite_embedding_107m_multilingual    overall                all
 3   granite_embedding_107m_multilingual  type_pair        float-float
 4   granite_embedding_107m_multilingual  type_pair        float-float
 5   granite_embedding_107m_multilingual  type_pair        float-float
 6   granite_embedding_107m_multilingual  type_pair          float-int
 7   granite_embedding_107m_multilingual  type_pair          float-int
 8   granite_embedding_107m_multilingual  type_pair          float-int
 9   granite_embedding_107m_multilingual  type_pair            int-int
 10  granite_embedding_107m_multilingual  type_pair            int-int
 11  granite_embedding_107m_multilingual  type_pair            int-int
 12  granite_embedding_107m_multilingual  same_sign              False
 13  granite_embedding_107m_multilingual  same_sign              False
 14  granite_embedding_107m_multilingual  same_sign              False
 15  granite_embedding_107m_multilingual  same_sign               True
 16  granite_embedding_107m_multilingual  same_sign               True
 17  granite_embedding_107m_multilingual  same_sign               True
 18  granite_embedding_107m_multilingual  sign_pair  negative-negative
 19  granite_embedding_107m_multilingual  sign_pair  negative-negative
 20  granite_embedding_107m_multilingual  sign_pair  negative-negative
 21  granite_embedding_107m_multilingual  sign_pair  negative-positive
 22  granite_embedding_107m_multilingual  sign_pair  negative-positive
 23  granite_embedding_107m_multilingual  sign_pair  negative-positive
 24  granite_embedding_107m_multilingual  sign_pair  positive-negative
 25  granite_embedding_107m_multilingual  sign_pair  positive-negative
 26  granite_embedding_107m_multilingual  sign_pair  positive-negative
 27  granite_embedding_107m_multilingual  sign_pair  positive-positive
 28  granite_embedding_107m_multilingual  sign_pair  positive-positive
 29  granite_embedding_107m_multilingual  sign_pair  positive-positive

     reference       tau  n_pairs
 0    char_lev  0.270305     4950
 1   token_lev  0.167063     4950
 2    num_dist  0.166985     4950
 3    char_lev  0.259262     1225
 4   token_lev  0.108972     1225
 5    num_dist  0.149350     1225
 6    char_lev  0.324258     2500
 7   token_lev  0.140812     2500
 8    num_dist  0.164292     2500
 9    char_lev  0.430850     1225
 10  token_lev  0.310397     1225
 11   num_dist  0.206371     1225
 12   char_lev  0.254067     2491
 13  token_lev  0.092374     2491
 14   num_dist -0.147793     2491
 15   char_lev  0.246106     2459
 16  token_lev  0.180504     2459
 17   num_dist  0.149631     2459
 18   char_lev  0.301182     1378
 19  token_lev  0.290852     1378
 20   num_dist  0.144180     1378
 21   char_lev  0.298410     1327
 22  token_lev  0.160949     1327
 23   num_dist -0.143596     1327
 24   char_lev  0.220712     1164
 25  token_lev  0.026719     1164
 26   num_dist -0.154970     1164
 27   char_lev  0.246707     1081
 28  token_lev  0.079990     1081
 29   num_dist  0.151693     1081  ,
 'granite_embedding_278m_multilingual':                                   model group_type              group  \
 0   granite_embedding_278m_multilingual    overall                all
 1   granite_embedding_278m_multilingual    overall                all
 2   granite_embedding_278m_multilingual    overall                all
 3   granite_embedding_278m_multilingual  type_pair        float-float
 4   granite_embedding_278m_multilingual  type_pair        float-float
 5   granite_embedding_278m_multilingual  type_pair        float-float
 6   granite_embedding_278m_multilingual  type_pair          float-int
 7   granite_embedding_278m_multilingual  type_pair          float-int
 8   granite_embedding_278m_multilingual  type_pair          float-int
 9   granite_embedding_278m_multilingual  type_pair            int-int
 10  granite_embedding_278m_multilingual  type_pair            int-int
 11  granite_embedding_278m_multilingual  type_pair            int-int
 12  granite_embedding_278m_multilingual  same_sign              False
 13  granite_embedding_278m_multilingual  same_sign              False
 14  granite_embedding_278m_multilingual  same_sign              False
 15  granite_embedding_278m_multilingual  same_sign               True
 16  granite_embedding_278m_multilingual  same_sign               True
 17  granite_embedding_278m_multilingual  same_sign               True
 18  granite_embedding_278m_multilingual  sign_pair  negative-negative
 19  granite_embedding_278m_multilingual  sign_pair  negative-negative
 20  granite_embedding_278m_multilingual  sign_pair  negative-negative
 21  granite_embedding_278m_multilingual  sign_pair  negative-positive
 22  granite_embedding_278m_multilingual  sign_pair  negative-positive
 23  granite_embedding_278m_multilingual  sign_pair  negative-positive
 24  granite_embedding_278m_multilingual  sign_pair  positive-negative
 25  granite_embedding_278m_multilingual  sign_pair  positive-negative
 26  granite_embedding_278m_multilingual  sign_pair  positive-negative
 27  granite_embedding_278m_multilingual  sign_pair  positive-positive
 28  granite_embedding_278m_multilingual  sign_pair  positive-positive
 29  granite_embedding_278m_multilingual  sign_pair  positive-positive

     reference       tau  n_pairs
 0    char_lev  0.294264     4950
 1   token_lev  0.163411     4950
 2    num_dist  0.147778     4950
 3    char_lev  0.250986     1225
 4   token_lev  0.117721     1225
 5    num_dist  0.117420     1225
 6    char_lev  0.331996     2500
 7   token_lev  0.144927     2500
 8    num_dist  0.145548     2500
 9    char_lev  0.462660     1225
 10  token_lev  0.251653     1225
 11   num_dist  0.210539     1225
 12   char_lev  0.279053     2491
 13  token_lev  0.094098     2491
 14   num_dist -0.149641     2491
 15   char_lev  0.276113     2459
 16  token_lev  0.181740     2459
 17   num_dist  0.128261     2459
 18   char_lev  0.313748     1378
 19  token_lev  0.258579     1378
 20   num_dist  0.120591     1378
 21   char_lev  0.343041     1327
 22  token_lev  0.185765     1327
 23   num_dist -0.135180     1327
 24   char_lev  0.205624     1164
 25  token_lev -0.016327     1164
 26   num_dist -0.166693     1164
 27   char_lev  0.350780     1081
 28  token_lev  0.140783     1081
 29   num_dist  0.137851     1081  ,
 'granite_embedding_english_r2':                            model group_type              group  reference  \
 0   granite_embedding_english_r2    overall                all   char_lev
 1   granite_embedding_english_r2    overall                all  token_lev
 2   granite_embedding_english_r2    overall                all   num_dist
 3   granite_embedding_english_r2  type_pair        float-float   char_lev
 4   granite_embedding_english_r2  type_pair        float-float  token_lev
 5   granite_embedding_english_r2  type_pair        float-float   num_dist
 6   granite_embedding_english_r2  type_pair          float-int   char_lev
 7   granite_embedding_english_r2  type_pair          float-int  token_lev
 8   granite_embedding_english_r2  type_pair          float-int   num_dist
 9   granite_embedding_english_r2  type_pair            int-int   char_lev
 10  granite_embedding_english_r2  type_pair            int-int  token_lev
 11  granite_embedding_english_r2  type_pair            int-int   num_dist
 12  granite_embedding_english_r2  same_sign              False   char_lev
 13  granite_embedding_english_r2  same_sign              False  token_lev
 14  granite_embedding_english_r2  same_sign              False   num_dist
 15  granite_embedding_english_r2  same_sign               True   char_lev
 16  granite_embedding_english_r2  same_sign               True  token_lev
 17  granite_embedding_english_r2  same_sign               True   num_dist
 18  granite_embedding_english_r2  sign_pair  negative-negative   char_lev
 19  granite_embedding_english_r2  sign_pair  negative-negative  token_lev
 20  granite_embedding_english_r2  sign_pair  negative-negative   num_dist
 21  granite_embedding_english_r2  sign_pair  negative-positive   char_lev
 22  granite_embedding_english_r2  sign_pair  negative-positive  token_lev
 23  granite_embedding_english_r2  sign_pair  negative-positive   num_dist
 24  granite_embedding_english_r2  sign_pair  positive-negative   char_lev
 25  granite_embedding_english_r2  sign_pair  positive-negative  token_lev
 26  granite_embedding_english_r2  sign_pair  positive-negative   num_dist
 27  granite_embedding_english_r2  sign_pair  positive-positive   char_lev
 28  granite_embedding_english_r2  sign_pair  positive-positive  token_lev
 29  granite_embedding_english_r2  sign_pair  positive-positive   num_dist

          tau  n_pairs
 0   0.166539     4950
 1   0.090639     4950
 2   0.144342     4950
 3   0.298612     1225
 4   0.146638     1225
 5   0.205098     1225
 6   0.295870     2500
 7   0.046075     2500
 8   0.107860     2500
 9   0.445558     1225
 10  0.211378     1225
 11  0.225818     1225
 12  0.037969     2491
 13 -0.056309     2491
 14 -0.066502     2491
 15  0.247985     2459
 16  0.153329     2459
 17  0.135092     2459
 18  0.323303     1378
 19  0.256918     1378
 20  0.125505     1378
 21  0.084867     1327
 22  0.034114     1327
 23 -0.014770     1327
 24  0.027685     1164
 25 -0.133091     1164
 26 -0.127740     1164
 27  0.160236     1081
 28  0.045881     1081
 29  0.145380     1081  ,
 'granite_embedding_97m_multilingual_r2':                                     model group_type              group  \
 0   granite_embedding_97m_multilingual_r2    overall                all
 1   granite_embedding_97m_multilingual_r2    overall                all
 2   granite_embedding_97m_multilingual_r2    overall                all
 3   granite_embedding_97m_multilingual_r2  type_pair        float-float
 4   granite_embedding_97m_multilingual_r2  type_pair        float-float
 5   granite_embedding_97m_multilingual_r2  type_pair        float-float
 6   granite_embedding_97m_multilingual_r2  type_pair          float-int
 7   granite_embedding_97m_multilingual_r2  type_pair          float-int
 8   granite_embedding_97m_multilingual_r2  type_pair          float-int
 9   granite_embedding_97m_multilingual_r2  type_pair            int-int
 10  granite_embedding_97m_multilingual_r2  type_pair            int-int
 11  granite_embedding_97m_multilingual_r2  type_pair            int-int
 12  granite_embedding_97m_multilingual_r2  same_sign              False
 13  granite_embedding_97m_multilingual_r2  same_sign              False
 14  granite_embedding_97m_multilingual_r2  same_sign              False
 15  granite_embedding_97m_multilingual_r2  same_sign               True
 16  granite_embedding_97m_multilingual_r2  same_sign               True
 17  granite_embedding_97m_multilingual_r2  same_sign               True
 18  granite_embedding_97m_multilingual_r2  sign_pair  negative-negative
 19  granite_embedding_97m_multilingual_r2  sign_pair  negative-negative
 20  granite_embedding_97m_multilingual_r2  sign_pair  negative-negative
 21  granite_embedding_97m_multilingual_r2  sign_pair  negative-positive
 22  granite_embedding_97m_multilingual_r2  sign_pair  negative-positive
 23  granite_embedding_97m_multilingual_r2  sign_pair  negative-positive
 24  granite_embedding_97m_multilingual_r2  sign_pair  positive-negative
 25  granite_embedding_97m_multilingual_r2  sign_pair  positive-negative
 26  granite_embedding_97m_multilingual_r2  sign_pair  positive-negative
 27  granite_embedding_97m_multilingual_r2  sign_pair  positive-positive
 28  granite_embedding_97m_multilingual_r2  sign_pair  positive-positive
 29  granite_embedding_97m_multilingual_r2  sign_pair  positive-positive

     reference       tau  n_pairs
 0    char_lev  0.049160     4950
 1   token_lev  0.084577     4950
 2    num_dist  0.125013     4950
 3    char_lev  0.175473     1225
 4   token_lev  0.189286     1225
 5    num_dist  0.124907     1225
 6    char_lev  0.118861     2500
 7   token_lev  0.025304     2500
 8    num_dist  0.126754     2500
 9    char_lev  0.278648     1225
 10  token_lev  0.293006     1225
 11   num_dist  0.211802     1225
 12   char_lev -0.044278     2491
 13  token_lev -0.068694     2491
 14   num_dist -0.042960     2491
 15   char_lev  0.097834     2459
 16  token_lev  0.185254     2459
 17   num_dist  0.124617     2459
 18   char_lev  0.081351     1378
 19  token_lev  0.136870     1378
 20   num_dist  0.141981     1378
 21   char_lev -0.011010     1327
 22  token_lev  0.025663     1327
 23   num_dist -0.013673     1327
 24   char_lev -0.029196     1164
 25  token_lev -0.113711     1164
 26   num_dist -0.093338     1164
 27   char_lev  0.120055     1081
 28  token_lev  0.238139     1081
 29   num_dist  0.100910     1081  ,
 'granite_embedding_311m_multilingual_r2':                                      model group_type              group  \
 0   granite_embedding_311m_multilingual_r2    overall                all
 1   granite_embedding_311m_multilingual_r2    overall                all
 2   granite_embedding_311m_multilingual_r2    overall                all
 3   granite_embedding_311m_multilingual_r2  type_pair        float-float
 4   granite_embedding_311m_multilingual_r2  type_pair        float-float
 5   granite_embedding_311m_multilingual_r2  type_pair        float-float
 6   granite_embedding_311m_multilingual_r2  type_pair          float-int
 7   granite_embedding_311m_multilingual_r2  type_pair          float-int
 8   granite_embedding_311m_multilingual_r2  type_pair          float-int
 9   granite_embedding_311m_multilingual_r2  type_pair            int-int
 10  granite_embedding_311m_multilingual_r2  type_pair            int-int
 11  granite_embedding_311m_multilingual_r2  type_pair            int-int
 12  granite_embedding_311m_multilingual_r2  same_sign              False
 13  granite_embedding_311m_multilingual_r2  same_sign              False
 14  granite_embedding_311m_multilingual_r2  same_sign              False
 15  granite_embedding_311m_multilingual_r2  same_sign               True
 16  granite_embedding_311m_multilingual_r2  same_sign               True
 17  granite_embedding_311m_multilingual_r2  same_sign               True
 18  granite_embedding_311m_multilingual_r2  sign_pair  negative-negative
 19  granite_embedding_311m_multilingual_r2  sign_pair  negative-negative
 20  granite_embedding_311m_multilingual_r2  sign_pair  negative-negative
 21  granite_embedding_311m_multilingual_r2  sign_pair  negative-positive
 22  granite_embedding_311m_multilingual_r2  sign_pair  negative-positive
 23  granite_embedding_311m_multilingual_r2  sign_pair  negative-positive
 24  granite_embedding_311m_multilingual_r2  sign_pair  positive-negative
 25  granite_embedding_311m_multilingual_r2  sign_pair  positive-negative
 26  granite_embedding_311m_multilingual_r2  sign_pair  positive-negative
 27  granite_embedding_311m_multilingual_r2  sign_pair  positive-positive
 28  granite_embedding_311m_multilingual_r2  sign_pair  positive-positive
 29  granite_embedding_311m_multilingual_r2  sign_pair  positive-positive

     reference       tau  n_pairs
 0    char_lev  0.142062     4950
 1   token_lev  0.142062     4950
 2    num_dist  0.091213     4950
 3    char_lev  0.324886     1225
 4   token_lev  0.324886     1225
 5    num_dist  0.170444     1225
 6    char_lev  0.333214     2500
 7   token_lev  0.333214     2500
 8    num_dist  0.104023     2500
 9    char_lev  0.535577     1225
 10  token_lev  0.535577     1225
 11   num_dist  0.118187     1225
 12   char_lev  0.055427     2491
 13  token_lev  0.055427     2491
 14   num_dist -0.008218     2491
 15   char_lev  0.234519     2459
 16  token_lev  0.234519     2459
 17   num_dist  0.108400     2459
 18   char_lev  0.218523     1378
 19  token_lev  0.218523     1378
 20   num_dist  0.134654     1378
 21   char_lev  0.101094     1327
 22  token_lev  0.101094     1327
 23   num_dist  0.055283     1327
 24   char_lev  0.145789     1164
 25  token_lev  0.145789     1164
 26   num_dist -0.096462     1164
 27   char_lev  0.286338     1081
 28  token_lev  0.286338     1081
 29   num_dist  0.098006     1081  }

#### PT3

In [ ]:
NEW_MODELS_3 = [
    "mixedbread-ai/mxbai-embed-large-v1",
    "microsoft/harrier-oss-v1-270m",
    "microsoft/harrier-oss-v1-0.6b",
    "lightonai/DenseOn"
]

run_lexical(NEW_MODELS_3)

================================================================================
mixedbread-ai/mxbai-embed-large-v1

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

[transformers] Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'sliding_attention', 'full_attention'}

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   10.0         24.2       28.7     33.9
num_dist    6.9         18.0        6.1     16.5
token_lev   5.4         16.0       26.6     17.1

================================================================================
microsoft/harrier-oss-v1-270m

[transformers] Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'sliding_attention', 'full_attention'}

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

[transformers] Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'sliding_attention', 'full_attention'}
[transformers] Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'sliding_attention', 'full_attention'}

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   28.4         42.5       30.5     43.1
num_dist   23.3         48.5       32.8     38.0
token_lev  28.4         42.5       30.5     43.1

================================================================================
microsoft/harrier-oss-v1-0.6b

Loading weights:   0%|          | 0/310 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   27.0         42.1       32.0     43.0
num_dist   21.7         46.1       29.7     32.6
token_lev  27.0         42.1       32.0     43.0

================================================================================
lightonai/DenseOn

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

Kendall's tau (x100)
group       all  float-float  float-int  int-int
reference
char_lev   23.5         18.1       21.0     36.9
num_dist   20.2         20.2       18.9     33.3
token_lev  27.4         17.0       25.1     31.6

Wrote per-model CSVs. Build the LaTeX table with table_lexical().

{'mxbai_embed_large_v1':                    model group_type              group  reference       tau  \
 0   mxbai_embed_large_v1    overall                all   char_lev  0.099826
 1   mxbai_embed_large_v1    overall                all  token_lev  0.054175
 2   mxbai_embed_large_v1    overall                all   num_dist  0.068817
 3   mxbai_embed_large_v1  type_pair        float-float   char_lev  0.241846
 4   mxbai_embed_large_v1  type_pair        float-float  token_lev  0.159513
 5   mxbai_embed_large_v1  type_pair        float-float   num_dist  0.180180
 6   mxbai_embed_large_v1  type_pair          float-int   char_lev  0.287213
 7   mxbai_embed_large_v1  type_pair          float-int  token_lev  0.266303
 8   mxbai_embed_large_v1  type_pair          float-int   num_dist  0.060714
 9   mxbai_embed_large_v1  type_pair            int-int   char_lev  0.339039
 10  mxbai_embed_large_v1  type_pair            int-int  token_lev  0.170679
 11  mxbai_embed_large_v1  type_pair            int-int   num_dist  0.165257
 12  mxbai_embed_large_v1  same_sign              False   char_lev  0.055532
 13  mxbai_embed_large_v1  same_sign              False  token_lev -0.007417
 14  mxbai_embed_large_v1  same_sign              False   num_dist -0.014401
 15  mxbai_embed_large_v1  same_sign               True   char_lev  0.141439
 16  mxbai_embed_large_v1  same_sign               True  token_lev  0.100163
 17  mxbai_embed_large_v1  same_sign               True   num_dist  0.096910
 18  mxbai_embed_large_v1  sign_pair  negative-negative   char_lev  0.158415
 19  mxbai_embed_large_v1  sign_pair  negative-negative  token_lev  0.117405
 20  mxbai_embed_large_v1  sign_pair  negative-negative   num_dist  0.113094
 21  mxbai_embed_large_v1  sign_pair  negative-positive   char_lev  0.158706
 22  mxbai_embed_large_v1  sign_pair  negative-positive  token_lev  0.079384
 23  mxbai_embed_large_v1  sign_pair  negative-positive   num_dist  0.010097
 24  mxbai_embed_large_v1  sign_pair  positive-negative   char_lev -0.100028
 25  mxbai_embed_large_v1  sign_pair  positive-negative  token_lev -0.122099
 26  mxbai_embed_large_v1  sign_pair  positive-negative   num_dist -0.034555
 27  mxbai_embed_large_v1  sign_pair  positive-positive   char_lev  0.148378
 28  mxbai_embed_large_v1  sign_pair  positive-positive  token_lev  0.075388
 29  mxbai_embed_large_v1  sign_pair  positive-positive   num_dist  0.079624

     n_pairs
 0      4950
 1      4950
 2      4950
 3      1225
 4      1225
 5      1225
 6      2500
 7      2500
 8      2500
 9      1225
 10     1225
 11     1225
 12     2491
 13     2491
 14     2491
 15     2459
 16     2459
 17     2459
 18     1378
 19     1378
 20     1378
 21     1327
 22     1327
 23     1327
 24     1164
 25     1164
 26     1164
 27     1081
 28     1081
 29     1081  ,
 'harrier_oss_v1_270m':                   model group_type              group  reference       tau  \
 0   harrier_oss_v1_270m    overall                all   char_lev  0.283606
 1   harrier_oss_v1_270m    overall                all  token_lev  0.283606
 2   harrier_oss_v1_270m    overall                all   num_dist  0.232726
 3   harrier_oss_v1_270m  type_pair        float-float   char_lev  0.424908
 4   harrier_oss_v1_270m  type_pair        float-float  token_lev  0.424908
 5   harrier_oss_v1_270m  type_pair        float-float   num_dist  0.485090
 6   harrier_oss_v1_270m  type_pair          float-int   char_lev  0.304580
 7   harrier_oss_v1_270m  type_pair          float-int  token_lev  0.304580
 8   harrier_oss_v1_270m  type_pair          float-int   num_dist  0.327523
 9   harrier_oss_v1_270m  type_pair            int-int   char_lev  0.431326
 10  harrier_oss_v1_270m  type_pair            int-int  token_lev  0.431326
 11  harrier_oss_v1_270m  type_pair            int-int   num_dist  0.379614
 12  harrier_oss_v1_270m  same_sign              False   char_lev  0.229628
 13  harrier_oss_v1_270m  same_sign              False  token_lev  0.229628
 14  harrier_oss_v1_270m  same_sign              False   num_dist -0.070238
 15  harrier_oss_v1_270m  same_sign               True   char_lev  0.338738
 16  harrier_oss_v1_270m  same_sign               True  token_lev  0.338738
 17  harrier_oss_v1_270m  same_sign               True   num_dist  0.137303
 18  harrier_oss_v1_270m  sign_pair  negative-negative   char_lev  0.485525
 19  harrier_oss_v1_270m  sign_pair  negative-negative  token_lev  0.485525
 20  harrier_oss_v1_270m  sign_pair  negative-negative   num_dist  0.179574
 21  harrier_oss_v1_270m  sign_pair  negative-positive   char_lev  0.240267
 22  harrier_oss_v1_270m  sign_pair  negative-positive  token_lev  0.240267
 23  harrier_oss_v1_270m  sign_pair  negative-positive   num_dist -0.060062
 24  harrier_oss_v1_270m  sign_pair  positive-negative   char_lev  0.157461
 25  harrier_oss_v1_270m  sign_pair  positive-negative  token_lev  0.157461
 26  harrier_oss_v1_270m  sign_pair  positive-negative   num_dist -0.102406
 27  harrier_oss_v1_270m  sign_pair  positive-positive   char_lev  0.292410
 28  harrier_oss_v1_270m  sign_pair  positive-positive  token_lev  0.292410
 29  harrier_oss_v1_270m  sign_pair  positive-positive   num_dist  0.128466

     n_pairs
 0      4950
 1      4950
 2      4950
 3      1225
 4      1225
 5      1225
 6      2500
 7      2500
 8      2500
 9      1225
 10     1225
 11     1225
 12     2491
 13     2491
 14     2491
 15     2459
 16     2459
 17     2459
 18     1378
 19     1378
 20     1378
 21     1327
 22     1327
 23     1327
 24     1164
 25     1164
 26     1164
 27     1081
 28     1081
 29     1081  ,
 'harrier_oss_v1_0.6b':                   model group_type              group  reference       tau  \
 0   harrier_oss_v1_0.6b    overall                all   char_lev  0.269830
 1   harrier_oss_v1_0.6b    overall                all  token_lev  0.269830
 2   harrier_oss_v1_0.6b    overall                all   num_dist  0.216930
 3   harrier_oss_v1_0.6b  type_pair        float-float   char_lev  0.420924
 4   harrier_oss_v1_0.6b  type_pair        float-float  token_lev  0.420924
 5   harrier_oss_v1_0.6b  type_pair        float-float   num_dist  0.460770
 6   harrier_oss_v1_0.6b  type_pair          float-int   char_lev  0.320298
 7   harrier_oss_v1_0.6b  type_pair          float-int  token_lev  0.320298
 8   harrier_oss_v1_0.6b  type_pair          float-int   num_dist  0.296911
 9   harrier_oss_v1_0.6b  type_pair            int-int   char_lev  0.430142
 10  harrier_oss_v1_0.6b  type_pair            int-int  token_lev  0.430142
 11  harrier_oss_v1_0.6b  type_pair            int-int   num_dist  0.326344
 12  harrier_oss_v1_0.6b  same_sign              False   char_lev  0.178737
 13  harrier_oss_v1_0.6b  same_sign              False  token_lev  0.178737
 14  harrier_oss_v1_0.6b  same_sign              False   num_dist -0.192049
 15  harrier_oss_v1_0.6b  same_sign               True   char_lev  0.313521
 16  harrier_oss_v1_0.6b  same_sign               True  token_lev  0.313521
 17  harrier_oss_v1_0.6b  same_sign               True   num_dist  0.206725
 18  harrier_oss_v1_0.6b  sign_pair  negative-negative   char_lev  0.371664
 19  harrier_oss_v1_0.6b  sign_pair  negative-negative  token_lev  0.371664
 20  harrier_oss_v1_0.6b  sign_pair  negative-negative   num_dist  0.268903
 21  harrier_oss_v1_0.6b  sign_pair  negative-positive   char_lev  0.226672
 22  harrier_oss_v1_0.6b  sign_pair  negative-positive  token_lev  0.226672
 23  harrier_oss_v1_0.6b  sign_pair  negative-positive   num_dist -0.134836
 24  harrier_oss_v1_0.6b  sign_pair  positive-negative   char_lev  0.093253
 25  harrier_oss_v1_0.6b  sign_pair  positive-negative  token_lev  0.093253
 26  harrier_oss_v1_0.6b  sign_pair  positive-negative   num_dist -0.293641
 27  harrier_oss_v1_0.6b  sign_pair  positive-positive   char_lev  0.319217
 28  harrier_oss_v1_0.6b  sign_pair  positive-positive  token_lev  0.319217
 29  harrier_oss_v1_0.6b  sign_pair  positive-positive   num_dist  0.174368

     n_pairs
 0      4950
 1      4950
 2      4950
 3      1225
 4      1225
 5      1225
 6      2500
 7      2500
 8      2500
 9      1225
 10     1225
 11     1225
 12     2491
 13     2491
 14     2491
 15     2459
 16     2459
 17     2459
 18     1378
 19     1378
 20     1378
 21     1327
 22     1327
 23     1327
 24     1164
 25     1164
 26     1164
 27     1081
 28     1081
 29     1081  ,
 'DenseOn':       model group_type              group  reference       tau  n_pairs
 0   DenseOn    overall                all   char_lev  0.234951     4950
 1   DenseOn    overall                all  token_lev  0.273888     4950
 2   DenseOn    overall                all   num_dist  0.202382     4950
 3   DenseOn  type_pair        float-float   char_lev  0.180538     1225
 4   DenseOn  type_pair        float-float  token_lev  0.170142     1225
 5   DenseOn  type_pair        float-float   num_dist  0.201737     1225
 6   DenseOn  type_pair          float-int   char_lev  0.209521     2500
 7   DenseOn  type_pair          float-int  token_lev  0.250626     2500
 8   DenseOn  type_pair          float-int   num_dist  0.188804     2500
 9   DenseOn  type_pair            int-int   char_lev  0.369400     1225
 10  DenseOn  type_pair            int-int  token_lev  0.316359     1225
 11  DenseOn  type_pair            int-int   num_dist  0.332885     1225
 12  DenseOn  same_sign              False   char_lev  0.155751     2491
 13  DenseOn  same_sign              False  token_lev  0.182985     2491
 14  DenseOn  same_sign              False   num_dist  0.001032     2491
 15  DenseOn  same_sign               True   char_lev  0.271336     2459
 16  DenseOn  same_sign               True  token_lev  0.300705     2459
 17  DenseOn  same_sign               True   num_dist  0.047117     2459
 18  DenseOn  sign_pair  negative-negative   char_lev  0.187313     1378
 19  DenseOn  sign_pair  negative-negative  token_lev  0.240879     1378
 20  DenseOn  sign_pair  negative-negative   num_dist  0.082387     1378
 21  DenseOn  sign_pair  negative-positive   char_lev  0.231440     1327
 22  DenseOn  sign_pair  negative-positive  token_lev  0.326206     1327
 23  DenseOn  sign_pair  negative-positive   num_dist -0.024581     1327
 24  DenseOn  sign_pair  positive-negative   char_lev  0.009095     1164
 25  DenseOn  sign_pair  positive-negative  token_lev -0.074127     1164
 26  DenseOn  sign_pair  positive-negative   num_dist  0.032558     1164
 27  DenseOn  sign_pair  positive-positive   char_lev  0.413564     1081
 28  DenseOn  sign_pair  positive-positive  token_lev  0.426596     1081
 29  DenseOn  sign_pair  positive-positive   num_dist  0.034507     1081}

# Exam 3 - Is similarity just miscalibrated?

**RQ.** Cosine similarity is a fixed, unweighted read-out of the embedding. If
the physical ordering *is* encoded but on directions cosine happens to ignore,
a learned read-out should recover it. If even a learned read-out fails, the
information is not there.

**Setup.** Instead of the dot product, fit a linear regressor on the absolute
embedding difference of a pair:

    d_hat(a, b) = w . |E(a) - E(b)| + b0

trained to predict `log1p(|v_a - v_b|)`. Data is split at the **item** level, so
no test pair shares a string with any training pair. One probe per
(model, range), pooled over the four quantities.

**Evaluation.** Every test item serves once as anchor; Kendall's tau and pairwise
accuracy are computed over the remaining test items and averaged. The whole
split-fit-evaluate loop is repeated over `REG_N_SPLITS = 5` random splits and
averaged, since a single split leaves only 7-9 test items. The identical
protocol is applied to plain cosine similarity, giving the directly comparable
`kendall_cosine` / `pairwise_cosine` columns. As in Table 1, the anchor is
excluded from its own candidate list and pairs with equal true distance are
skipped in pairwise accuracy. Unlike Table 1, only test items are used and
distances are linear for every range.

Run the Exam 1 definitions cell first - this reuses `RANGES`, `units`,
`range_texts` and `CSV_DIR` from it.

**Output.** For each model, two files next to the existing ones:

    <model>_benchmark_full_regression_experiment.csv
    <model>_benchmark_summary_regression_experiment.csv

In [ ]:
"""
Exam 3 -- is embedding similarity just miscalibrated for measurement?

Instead of reading the physical ordering off the cosine similarity, we fit a
linear regressor on the *absolute embedding difference* of a pair and let it
predict the physical distance of that pair.

    d_hat(a, b) = w . |E(a) - E(b)| + b0

If a linear read-out recovers the physical ordering, the information is present
in the embedding and cosine similarity is merely a badly calibrated probe.
If it does not, the information is largely absent.

Protocol
--------
* Split, per range, at the *item* level (not the pair level), so no test pair
  shares a string with the training pairs.
* One probe per (model, range, split), pooled over the four quantities, since
  the four quantities share the same numeric values. Target: log1p(|v_i - v_j|).
* Repeated over REG_N_SPLITS random splits; reported values are means over
  splits, with the across-split standard deviation kept alongside.
* Evaluation: every test item serves once as anchor; Kendall's tau and pairwise
  accuracy are computed over the remaining test items and averaged.
* The identical protocol is applied to plain cosine similarity, which gives the
  directly comparable `kendall_cosine` / `pairwise_cosine` columns.

Note: as in Table 1, the anchor is excluded from its own candidate list and pairs
with equal true distance are skipped in pairwise accuracy (`pairwise_accuracy`
from the Exam 1 definitions). Unlike Table 1, only test items are used and
distances are linear for every range, so Table 4 is internally comparable but
not comparable to Table 1 in absolute terms.
"""

from sklearn.linear_model import RidgeCV

REG_TEST_FRACTION = 0.35
REG_MIN_TEST = 4
REG_N_SPLITS = 5
REG_SEED = 12345
REG_ALPHAS = np.logspace(-2, 4, 13)


# --------------------------------------------------------------------
# SPLIT + FEATURES
# --------------------------------------------------------------------

def split_indices(n, test_fraction=REG_TEST_FRACTION, seed=REG_SEED):
    """Item-level split: returns (train_idx, test_idx)."""
    rng = np.random.default_rng(seed)
    perm = rng.permutation(n)
    n_test = max(REG_MIN_TEST, int(round(test_fraction * n)))
    n_test = min(n_test, n - 3)
    return np.sort(perm[n_test:]), np.sort(perm[:n_test])


def pair_features(emb, idx):
    """|e_i - e_j| for every unordered pair drawn from `idx`."""
    i, j = np.triu_indices(len(idx), k=1)
    a, b = np.asarray(idx)[i], np.asarray(idx)[j]
    return np.abs(emb[a] - emb[b]), a, b


def ranking_metrics_from_scores(score, true_dist):
    """
    score:     higher = predicted to be closer to the anchor
    true_dist: ground-truth physical distance to the anchor
    """
    score = np.asarray(score, dtype=float)
    true_dist = np.asarray(true_dist, dtype=float)

    tau = kendalltau(true_dist, -score).statistic

    return tau, pairwise_accuracy(true_dist, score)


def anchored_scores(score_fn, values, test_idx):
    """Average tau / pairwise accuracy over all test items used as anchor."""
    taus, accs = [], []

    for anchor in test_idx:
        others = np.array([k for k in test_idx if k != anchor])
        true_dist = np.abs(values[others] - values[anchor])
        tau, acc = ranking_metrics_from_scores(score_fn(anchor, others), true_dist)
        taus.append(tau)
        accs.append(acc)

    return float(np.nanmean(taus)), float(np.nanmean(accs))


# --------------------------------------------------------------------
# PER-MODEL RUN
# --------------------------------------------------------------------

def run_regression_benchmark(model_name, encoder=None):
    """
    `encoder` is only used for testing: any object exposing
    .encode(texts, normalize_embeddings=True) works.
    """

    model_id = model_name.split("/")[-1].replace("-", "_")
    print("=" * 80)
    print(model_name)
    print("=" * 80)

    model = encoder or SentenceTransformer(model_name, trust_remote_code=True).float()

    # embed once, then drop the model to free GPU memory
    emb = {}
    for unit in units:
        for name, values in RANGES.items():
            emb[(unit, name)] = model.encode(
                range_texts(unit, name, values),
                normalize_embeddings=True,
            ).astype(np.float32)

    if encoder is None:
        del model
        gc.collect()
        torch.cuda.empty_cache()

    rows = []

    for name, raw_values in RANGES.items():

        values = np.asarray(raw_values, dtype=float)

        # split -> unit -> (tau_probe, acc_probe, tau_cos, acc_cos)
        per_split = {unit: [] for unit in units}
        alphas = []

        for s in range(REG_N_SPLITS):

            train_idx, test_idx = split_indices(len(values), seed=REG_SEED + s)

            # one probe per (range, split), pooled over the four quantities
            X, y = [], []
            for unit in units:
                feats, a, b = pair_features(emb[(unit, name)], train_idx)
                X.append(feats)
                y.append(np.log1p(np.abs(values[a] - values[b])))

            X = np.vstack(X)
            y = np.concatenate(y)

            reg = RidgeCV(alphas=REG_ALPHAS).fit(X, y)
            alphas.append(float(reg.alpha_))

            for unit in units:
                e = emb[(unit, name)]

                tau_r, acc_r = anchored_scores(
                    lambda anchor, others: -reg.predict(np.abs(e[others] - e[anchor])),
                    values,
                    test_idx,
                )
                tau_c, acc_c = anchored_scores(
                    lambda anchor, others: e[others] @ e[anchor],
                    values,
                    test_idx,
                )

                per_split[unit].append((tau_r, acc_r, tau_c, acc_c))

        for unit in units:

            arr = np.array(per_split[unit])  # (n_splits, 4)
            mean = arr.mean(axis=0)
            sd = arr.std(axis=0, ddof=1) if len(arr) > 1 else np.zeros(4)

            print(
                f"{unit:9s} {name:15s}  "
                f"probe \u03c4={mean[0]:.3f}(\u00b1{sd[0]:.3f}) pairwise={mean[1]:.3f}   |   "
                f"cosine \u03c4={mean[2]:.3f}(\u00b1{sd[2]:.3f}) pairwise={mean[3]:.3f}"
            )

            rows.append({
                "model": model_id,
                "unit": unit,
                "range": name,
                "kendall": mean[0],
                "pairwise": mean[1],
                "kendall_cosine": mean[2],
                "pairwise_cosine": mean[3],
                "kendall_sd_splits": sd[0],
                "kendall_cosine_sd_splits": sd[2],
                "alpha_median": float(np.median(alphas)),
                "n_splits": REG_N_SPLITS,
                "n_train_pairs": int(X.shape[0]),
                "n_train_items": int(len(train_idx)),
                "n_test_items": int(len(test_idx)),
            })

    df = pd.DataFrame(rows)

    summary = df.groupby("model").agg(
        kendall_mean=("kendall", "mean"),
        pairwise_mean=("pairwise", "mean"),
        kendall_std=("kendall", "std"),
        pairwise_std=("pairwise", "std"),
        kendall_cosine_mean=("kendall_cosine", "mean"),
        pairwise_cosine_mean=("pairwise_cosine", "mean"),
        kendall_cosine_std=("kendall_cosine", "std"),
        pairwise_cosine_std=("pairwise_cosine", "std"),
    ).reset_index()

    df.to_csv(
        os.path.join(CSV_DIR, f"{model_id}_benchmark_full_regression_experiment.csv"),
        index=False,
    )
    summary.to_csv(
        os.path.join(CSV_DIR, f"{model_id}_benchmark_summary_regression_experiment.csv"),
        index=False,
    )

    print()
    print(summary.to_string(index=False))

    gc.collect()
    torch.cuda.empty_cache()

    return df


def run_regression(models):
    """Run the calibration probe over a list of model names."""
    out = []
    for model_name in models:
        out.append(run_regression_benchmark(model_name))
    return pd.concat(out, ignore_index=True) if out else pd.DataFrame()

### Run: baseline models

In [ ]:
# Baseline models (the original paper set + Qwen3 4B / 8B)
MODELS = [
    "sentence-transformers/all-MiniLM-L6-v2",
    "sentence-transformers/all-mpnet-base-v2",
    "intfloat/e5-large-v2",
    "BAAI/bge-large-en-v1.5",
    "nomic-ai/nomic-embed-text-v1.5",
    "Qwen/Qwen3-Embedding-0.6B",
    "Qwen/Qwen3-Embedding-4B",
    "Qwen/Qwen3-Embedding-8B",
]

run_regression(MODELS)

================================================================================
sentence-transformers/all-MiniLM-L6-v2
================================================================================

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.577(±0.167) pairwise=0.791   |   cosine τ=0.502(±0.141) pairwise=0.754
kilogram  local_0_10       probe τ=0.568(±0.190) pairwise=0.786   |   cosine τ=0.482(±0.092) pairwise=0.744
liter     local_0_10       probe τ=0.581(±0.139) pairwise=0.793   |   cosine τ=0.509(±0.131) pairwise=0.758
second    local_0_10       probe τ=0.545(±0.122) pairwise=0.775   |   cosine τ=0.393(±0.096) pairwise=0.699
meter     medium_0_1000    probe τ=0.502(±0.159) pairwise=0.755   |   cosine τ=0.398(±0.120) pairwise=0.702
kilogram  medium_0_1000    probe τ=0.421(±0.197) pairwise=0.714   |   cosine τ=0.386(±0.110) pairwise=0.696
liter     medium_0_1000    probe τ=0.452(±0.189) pairwise=0.729   |   cosine τ=0.451(±0.124) pairwise=0.728
second    medium_0_1000    probe τ=0.463(±0.176) pairwise=0.735   |   cosine τ=0.409(±0.085) pairwise=0.707
meter     log_1_100k       probe τ=0.122(±0.146) pairwise=0.561   |   cosine τ=0.233(±0.166) pairwise=0.617
kilogram  log_1_100k       probe τ=0.105(±0.199) pairwise=0.553   |   cosine τ=0.139(±0.130) pairwise=0.570
liter     log_1_100k       probe τ=0.164(±0.174) pairwise=0.582   |   cosine τ=0.356(±0.106) pairwise=0.678
second    log_1_100k       probe τ=0.100(±0.089) pairwise=0.550   |   cosine τ=0.318(±0.162) pairwise=0.659
meter     sign_split       probe τ=0.510(±0.074) pairwise=0.759   |   cosine τ=0.370(±0.153) pairwise=0.688
kilogram  sign_split       probe τ=0.424(±0.067) pairwise=0.715   |   cosine τ=0.451(±0.141) pairwise=0.728
liter     sign_split       probe τ=0.451(±0.093) pairwise=0.729   |   cosine τ=0.425(±0.108) pairwise=0.715
second    sign_split       probe τ=0.416(±0.075) pairwise=0.711   |   cosine τ=0.497(±0.117) pairwise=0.752
meter     scientific       probe τ=0.237(±0.088) pairwise=0.618   |   cosine τ=0.283(±0.169) pairwise=0.641
kilogram  scientific       probe τ=0.344(±0.112) pairwise=0.672   |   cosine τ=0.243(±0.151) pairwise=0.621
liter     scientific       probe τ=0.246(±0.122) pairwise=0.623   |   cosine τ=0.260(±0.150) pairwise=0.630
second    scientific       probe τ=0.179(±0.185) pairwise=0.590   |   cosine τ=0.316(±0.125) pairwise=0.658

           model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
all_MiniLM_L6_v2      0.370436        0.68698     0.168693      0.085602              0.37105              0.687225            0.102108             0.052329
================================================================================
sentence-transformers/all-mpnet-base-v2
================================================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.601(±0.133) pairwise=0.804   |   cosine τ=0.396(±0.164) pairwise=0.700
kilogram  local_0_10       probe τ=0.601(±0.168) pairwise=0.804   |   cosine τ=0.353(±0.133) pairwise=0.678
liter     local_0_10       probe τ=0.710(±0.091) pairwise=0.860   |   cosine τ=0.485(±0.097) pairwise=0.745
second    local_0_10       probe τ=0.713(±0.147) pairwise=0.861   |   cosine τ=0.331(±0.139) pairwise=0.667
meter     medium_0_1000    probe τ=0.451(±0.142) pairwise=0.728   |   cosine τ=0.394(±0.158) pairwise=0.699
kilogram  medium_0_1000    probe τ=0.448(±0.177) pairwise=0.728   |   cosine τ=0.429(±0.171) pairwise=0.717
liter     medium_0_1000    probe τ=0.454(±0.226) pairwise=0.730   |   cosine τ=0.455(±0.199) pairwise=0.731
second    medium_0_1000    probe τ=0.444(±0.206) pairwise=0.725   |   cosine τ=0.480(±0.160) pairwise=0.744
meter     log_1_100k       probe τ=0.182(±0.076) pairwise=0.591   |   cosine τ=0.507(±0.150) pairwise=0.754
kilogram  log_1_100k       probe τ=0.162(±0.113) pairwise=0.581   |   cosine τ=0.267(±0.124) pairwise=0.634
liter     log_1_100k       probe τ=0.286(±0.095) pairwise=0.643   |   cosine τ=0.407(±0.137) pairwise=0.703
second    log_1_100k       probe τ=0.190(±0.155) pairwise=0.595   |   cosine τ=0.483(±0.133) pairwise=0.742
meter     sign_split       probe τ=0.565(±0.176) pairwise=0.787   |   cosine τ=0.575(±0.092) pairwise=0.791
kilogram  sign_split       probe τ=0.606(±0.178) pairwise=0.807   |   cosine τ=0.552(±0.128) pairwise=0.780
liter     sign_split       probe τ=0.506(±0.136) pairwise=0.757   |   cosine τ=0.559(±0.123) pairwise=0.783
second    sign_split       probe τ=0.494(±0.113) pairwise=0.751   |   cosine τ=0.498(±0.113) pairwise=0.753
meter     scientific       probe τ=0.241(±0.056) pairwise=0.621   |   cosine τ=0.200(±0.147) pairwise=0.600
kilogram  scientific       probe τ=0.281(±0.062) pairwise=0.640   |   cosine τ=0.259(±0.132) pairwise=0.629
liter     scientific       probe τ=0.359(±0.067) pairwise=0.679   |   cosine τ=0.203(±0.107) pairwise=0.602
second    scientific       probe τ=0.298(±0.080) pairwise=0.649   |   cosine τ=0.249(±0.152) pairwise=0.625

            model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
all_mpnet_base_v2      0.429649       0.716966     0.173071      0.088296             0.404028              0.703761            0.119241             0.060755
================================================================================
intfloat/e5-large-v2
================================================================================

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.509(±0.137) pairwise=0.757   |   cosine τ=0.316(±0.150) pairwise=0.660
kilogram  local_0_10       probe τ=0.625(±0.051) pairwise=0.816   |   cosine τ=0.339(±0.147) pairwise=0.671
liter     local_0_10       probe τ=0.621(±0.042) pairwise=0.814   |   cosine τ=0.408(±0.146) pairwise=0.707
second    local_0_10       probe τ=0.540(±0.150) pairwise=0.774   |   cosine τ=0.239(±0.125) pairwise=0.621
meter     medium_0_1000    probe τ=0.613(±0.142) pairwise=0.810   |   cosine τ=0.412(±0.059) pairwise=0.708
kilogram  medium_0_1000    probe τ=0.663(±0.100) pairwise=0.835   |   cosine τ=0.413(±0.101) pairwise=0.709
liter     medium_0_1000    probe τ=0.620(±0.121) pairwise=0.814   |   cosine τ=0.390(±0.099) pairwise=0.698
second    medium_0_1000    probe τ=0.690(±0.140) pairwise=0.849   |   cosine τ=0.458(±0.095) pairwise=0.732
meter     log_1_100k       probe τ=0.443(±0.053) pairwise=0.722   |   cosine τ=0.515(±0.142) pairwise=0.758
kilogram  log_1_100k       probe τ=0.426(±0.023) pairwise=0.713   |   cosine τ=0.402(±0.125) pairwise=0.701
liter     log_1_100k       probe τ=0.410(±0.095) pairwise=0.705   |   cosine τ=0.448(±0.136) pairwise=0.724
second    log_1_100k       probe τ=0.373(±0.073) pairwise=0.687   |   cosine τ=0.419(±0.105) pairwise=0.710
meter     sign_split       probe τ=0.472(±0.115) pairwise=0.740   |   cosine τ=0.496(±0.096) pairwise=0.750
kilogram  sign_split       probe τ=0.523(±0.103) pairwise=0.766   |   cosine τ=0.366(±0.131) pairwise=0.685
liter     sign_split       probe τ=0.456(±0.145) pairwise=0.731   |   cosine τ=0.346(±0.071) pairwise=0.675
second    sign_split       probe τ=0.490(±0.109) pairwise=0.748   |   cosine τ=0.338(±0.064) pairwise=0.670
meter     scientific       probe τ=0.287(±0.116) pairwise=0.644   |   cosine τ=0.200(±0.145) pairwise=0.600
kilogram  scientific       probe τ=0.260(±0.140) pairwise=0.630   |   cosine τ=0.208(±0.148) pairwise=0.604
liter     scientific       probe τ=0.273(±0.119) pairwise=0.637   |   cosine τ=0.213(±0.118) pairwise=0.606
second    scientific       probe τ=0.317(±0.133) pairwise=0.659   |   cosine τ=0.219(±0.101) pairwise=0.610

      model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
e5_large_v2      0.480571       0.742555     0.133321      0.068255              0.35728               0.67996            0.097807             0.049364
================================================================================
BAAI/bge-large-en-v1.5
================================================================================

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.582(±0.241) pairwise=0.795   |   cosine τ=0.351(±0.115) pairwise=0.677
kilogram  local_0_10       probe τ=0.590(±0.241) pairwise=0.799   |   cosine τ=0.347(±0.118) pairwise=0.676
liter     local_0_10       probe τ=0.579(±0.241) pairwise=0.793   |   cosine τ=0.420(±0.155) pairwise=0.713
second    local_0_10       probe τ=0.587(±0.168) pairwise=0.797   |   cosine τ=0.347(±0.066) pairwise=0.676
meter     medium_0_1000    probe τ=0.339(±0.083) pairwise=0.671   |   cosine τ=0.474(±0.167) pairwise=0.740
kilogram  medium_0_1000    probe τ=0.247(±0.135) pairwise=0.625   |   cosine τ=0.363(±0.278) pairwise=0.684
liter     medium_0_1000    probe τ=0.339(±0.065) pairwise=0.672   |   cosine τ=0.467(±0.214) pairwise=0.736
second    medium_0_1000    probe τ=0.543(±0.185) pairwise=0.774   |   cosine τ=0.579(±0.156) pairwise=0.793
meter     log_1_100k       probe τ=0.222(±0.153) pairwise=0.611   |   cosine τ=0.400(±0.211) pairwise=0.700
kilogram  log_1_100k       probe τ=0.160(±0.168) pairwise=0.580   |   cosine τ=0.269(±0.199) pairwise=0.635
liter     log_1_100k       probe τ=0.297(±0.167) pairwise=0.649   |   cosine τ=0.254(±0.175) pairwise=0.627
second    log_1_100k       probe τ=0.271(±0.051) pairwise=0.636   |   cosine τ=0.334(±0.170) pairwise=0.667
meter     sign_split       probe τ=0.024(±0.303) pairwise=0.513   |   cosine τ=0.151(±0.141) pairwise=0.577
kilogram  sign_split       probe τ=0.018(±0.287) pairwise=0.510   |   cosine τ=0.143(±0.130) pairwise=0.572
liter     sign_split       probe τ=0.125(±0.317) pairwise=0.564   |   cosine τ=0.143(±0.128) pairwise=0.573
second    sign_split       probe τ=0.449(±0.195) pairwise=0.728   |   cosine τ=0.457(±0.097) pairwise=0.732
meter     scientific       probe τ=0.238(±0.106) pairwise=0.619   |   cosine τ=0.187(±0.107) pairwise=0.594
kilogram  scientific       probe τ=0.257(±0.123) pairwise=0.629   |   cosine τ=0.202(±0.057) pairwise=0.601
liter     scientific       probe τ=0.243(±0.092) pairwise=0.621   |   cosine τ=0.171(±0.087) pairwise=0.586
second    scientific       probe τ=0.343(±0.092) pairwise=0.671   |   cosine τ=0.319(±0.096) pairwise=0.660

            model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
bge_large_en_v1.5      0.322725       0.662945     0.181252      0.091846             0.318893              0.660906            0.126464             0.064242
================================================================================
nomic-ai/nomic-embed-text-v1.5
================================================================================

WARNING:transformers_modules.nomic_hyphen_ai.nomic_hyphen_bert_hyphen_2048.7710840340a098cfb869c4f65e87cf2b1b70caca.modeling_hf_nomic_bert:<All keys matched successfully>

meter     local_0_10       probe τ=0.528(±0.165) pairwise=0.767   |   cosine τ=0.494(±0.167) pairwise=0.750
kilogram  local_0_10       probe τ=0.546(±0.150) pairwise=0.776   |   cosine τ=0.525(±0.147) pairwise=0.766
liter     local_0_10       probe τ=0.528(±0.149) pairwise=0.768   |   cosine τ=0.532(±0.136) pairwise=0.769
second    local_0_10       probe τ=0.528(±0.202) pairwise=0.767   |   cosine τ=0.416(±0.162) pairwise=0.710
meter     medium_0_1000    probe τ=0.510(±0.137) pairwise=0.758   |   cosine τ=0.503(±0.181) pairwise=0.756
kilogram  medium_0_1000    probe τ=0.432(±0.173) pairwise=0.718   |   cosine τ=0.518(±0.235) pairwise=0.763
liter     medium_0_1000    probe τ=0.470(±0.219) pairwise=0.738   |   cosine τ=0.534(±0.200) pairwise=0.771
second    medium_0_1000    probe τ=0.486(±0.154) pairwise=0.747   |   cosine τ=0.484(±0.200) pairwise=0.746
meter     log_1_100k       probe τ=0.216(±0.039) pairwise=0.608   |   cosine τ=0.057(±0.110) pairwise=0.529
kilogram  log_1_100k       probe τ=0.183(±0.094) pairwise=0.591   |   cosine τ=0.008(±0.136) pairwise=0.504
liter     log_1_100k       probe τ=0.288(±0.067) pairwise=0.644   |   cosine τ=-0.009(±0.104) pairwise=0.495
second    log_1_100k       probe τ=0.163(±0.046) pairwise=0.582   |   cosine τ=0.024(±0.104) pairwise=0.512
meter     sign_split       probe τ=-0.057(±0.189) pairwise=0.471   |   cosine τ=0.090(±0.232) pairwise=0.546
kilogram  sign_split       probe τ=-0.027(±0.221) pairwise=0.487   |   cosine τ=0.191(±0.187) pairwise=0.597
liter     sign_split       probe τ=-0.019(±0.213) pairwise=0.490   |   cosine τ=0.133(±0.188) pairwise=0.568
second    sign_split       probe τ=-0.028(±0.168) pairwise=0.486   |   cosine τ=0.021(±0.240) pairwise=0.511
meter     scientific       probe τ=0.257(±0.091) pairwise=0.629   |   cosine τ=0.160(±0.170) pairwise=0.580
kilogram  scientific       probe τ=0.241(±0.090) pairwise=0.621   |   cosine τ=0.132(±0.140) pairwise=0.566
liter     scientific       probe τ=0.260(±0.104) pairwise=0.630   |   cosine τ=0.141(±0.171) pairwise=0.571
second    scientific       probe τ=0.305(±0.087) pairwise=0.652   |   cosine τ=0.206(±0.188) pairwise=0.603

                model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
nomic_embed_text_v1.5      0.290537       0.646473     0.208996      0.105879              0.25802              0.630773             0.21245             0.107791
================================================================================
Qwen/Qwen3-Embedding-0.6B
================================================================================

Loading weights:   0%|          | 0/310 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.280(±0.219) pairwise=0.643   |   cosine τ=0.221(±0.127) pairwise=0.613
kilogram  local_0_10       probe τ=0.396(±0.143) pairwise=0.702   |   cosine τ=0.187(±0.106) pairwise=0.596
liter     local_0_10       probe τ=0.211(±0.252) pairwise=0.608   |   cosine τ=0.105(±0.164) pairwise=0.554
second    local_0_10       probe τ=0.354(±0.290) pairwise=0.681   |   cosine τ=0.190(±0.172) pairwise=0.596
meter     medium_0_1000    probe τ=0.270(±0.122) pairwise=0.637   |   cosine τ=0.278(±0.138) pairwise=0.641
kilogram  medium_0_1000    probe τ=0.076(±0.208) pairwise=0.538   |   cosine τ=0.316(±0.075) pairwise=0.660
liter     medium_0_1000    probe τ=0.278(±0.068) pairwise=0.641   |   cosine τ=0.297(±0.082) pairwise=0.650
second    medium_0_1000    probe τ=0.381(±0.125) pairwise=0.693   |   cosine τ=0.405(±0.103) pairwise=0.705
meter     log_1_100k       probe τ=0.357(±0.070) pairwise=0.679   |   cosine τ=0.311(±0.100) pairwise=0.656
kilogram  log_1_100k       probe τ=0.302(±0.068) pairwise=0.651   |   cosine τ=0.249(±0.079) pairwise=0.625
liter     log_1_100k       probe τ=0.370(±0.125) pairwise=0.685   |   cosine τ=0.251(±0.113) pairwise=0.626
second    log_1_100k       probe τ=0.334(±0.140) pairwise=0.667   |   cosine τ=0.504(±0.103) pairwise=0.752
meter     sign_split       probe τ=0.302(±0.180) pairwise=0.653   |   cosine τ=0.505(±0.052) pairwise=0.755
kilogram  sign_split       probe τ=0.329(±0.180) pairwise=0.667   |   cosine τ=0.412(±0.152) pairwise=0.709
liter     sign_split       probe τ=0.286(±0.170) pairwise=0.645   |   cosine τ=0.466(±0.142) pairwise=0.735
second    sign_split       probe τ=0.390(±0.123) pairwise=0.698   |   cosine τ=0.519(±0.188) pairwise=0.762
meter     scientific       probe τ=0.383(±0.129) pairwise=0.691   |   cosine τ=0.371(±0.075) pairwise=0.686
kilogram  scientific       probe τ=0.317(±0.158) pairwise=0.659   |   cosine τ=0.379(±0.079) pairwise=0.690
liter     scientific       probe τ=0.351(±0.162) pairwise=0.675   |   cosine τ=0.387(±0.067) pairwise=0.694
second    scientific       probe τ=0.419(±0.160) pairwise=0.710   |   cosine τ=0.384(±0.068) pairwise=0.692

               model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
Qwen3_Embedding_0.6B      0.319305       0.661134     0.077353      0.038813             0.336977               0.66982            0.116107             0.058202
================================================================================
Qwen/Qwen3-Embedding-4B
================================================================================

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.523(±0.179) pairwise=0.766   |   cosine τ=0.364(±0.094) pairwise=0.685
kilogram  local_0_10       probe τ=0.356(±0.236) pairwise=0.681   |   cosine τ=0.209(±0.091) pairwise=0.606
liter     local_0_10       probe τ=0.394(±0.253) pairwise=0.700   |   cosine τ=0.332(±0.084) pairwise=0.668
second    local_0_10       probe τ=0.540(±0.205) pairwise=0.774   |   cosine τ=0.309(±0.130) pairwise=0.657
meter     medium_0_1000    probe τ=0.481(±0.194) pairwise=0.743   |   cosine τ=0.308(±0.096) pairwise=0.656
kilogram  medium_0_1000    probe τ=0.504(±0.196) pairwise=0.755   |   cosine τ=0.231(±0.157) pairwise=0.617
liter     medium_0_1000    probe τ=0.471(±0.193) pairwise=0.739   |   cosine τ=0.297(±0.152) pairwise=0.651
second    medium_0_1000    probe τ=0.540(±0.212) pairwise=0.774   |   cosine τ=0.375(±0.258) pairwise=0.690
meter     log_1_100k       probe τ=0.478(±0.062) pairwise=0.739   |   cosine τ=0.469(±0.060) pairwise=0.735
kilogram  log_1_100k       probe τ=0.246(±0.082) pairwise=0.623   |   cosine τ=0.192(±0.136) pairwise=0.596
liter     log_1_100k       probe τ=0.295(±0.114) pairwise=0.648   |   cosine τ=0.348(±0.083) pairwise=0.674
second    log_1_100k       probe τ=0.475(±0.095) pairwise=0.738   |   cosine τ=0.499(±0.063) pairwise=0.750
meter     sign_split       probe τ=0.390(±0.175) pairwise=0.698   |   cosine τ=0.474(±0.073) pairwise=0.740
kilogram  sign_split       probe τ=0.352(±0.143) pairwise=0.679   |   cosine τ=0.416(±0.135) pairwise=0.710
liter     sign_split       probe τ=0.333(±0.207) pairwise=0.669   |   cosine τ=0.428(±0.125) pairwise=0.717
second    sign_split       probe τ=0.402(±0.227) pairwise=0.704   |   cosine τ=0.406(±0.056) pairwise=0.706
meter     scientific       probe τ=0.386(±0.103) pairwise=0.693   |   cosine τ=0.333(±0.115) pairwise=0.667
kilogram  scientific       probe τ=0.390(±0.120) pairwise=0.695   |   cosine τ=0.335(±0.125) pairwise=0.667
liter     scientific       probe τ=0.440(±0.131) pairwise=0.720   |   cosine τ=0.378(±0.096) pairwise=0.689
second    scientific       probe τ=0.384(±0.135) pairwise=0.692   |   cosine τ=0.430(±0.046) pairwise=0.715

             model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
Qwen3_Embedding_4B      0.419036       0.711377     0.081719      0.041566             0.356646              0.679749            0.085335             0.042787
================================================================================
Qwen/Qwen3-Embedding-8B
================================================================================

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.461(±0.086) pairwise=0.735   |   cosine τ=0.307(±0.079) pairwise=0.657
kilogram  local_0_10       probe τ=0.439(±0.225) pairwise=0.724   |   cosine τ=0.267(±0.128) pairwise=0.636
liter     local_0_10       probe τ=0.441(±0.236) pairwise=0.724   |   cosine τ=0.267(±0.155) pairwise=0.635
second    local_0_10       probe τ=0.475(±0.147) pairwise=0.740   |   cosine τ=0.352(±0.112) pairwise=0.679
meter     medium_0_1000    probe τ=0.478(±0.212) pairwise=0.742   |   cosine τ=0.233(±0.092) pairwise=0.619
kilogram  medium_0_1000    probe τ=0.355(±0.231) pairwise=0.680   |   cosine τ=0.172(±0.182) pairwise=0.589
liter     medium_0_1000    probe τ=0.395(±0.166) pairwise=0.701   |   cosine τ=0.257(±0.086) pairwise=0.632
second    medium_0_1000    probe τ=0.448(±0.093) pairwise=0.727   |   cosine τ=0.419(±0.150) pairwise=0.713
meter     log_1_100k       probe τ=0.439(±0.124) pairwise=0.720   |   cosine τ=0.442(±0.087) pairwise=0.721
kilogram  log_1_100k       probe τ=0.345(±0.162) pairwise=0.673   |   cosine τ=0.308(±0.073) pairwise=0.654
liter     log_1_100k       probe τ=0.378(±0.159) pairwise=0.689   |   cosine τ=0.392(±0.121) pairwise=0.696
second    log_1_100k       probe τ=0.367(±0.125) pairwise=0.684   |   cosine τ=0.262(±0.059) pairwise=0.631
meter     sign_split       probe τ=0.328(±0.124) pairwise=0.666   |   cosine τ=0.378(±0.133) pairwise=0.692
kilogram  sign_split       probe τ=0.425(±0.113) pairwise=0.715   |   cosine τ=0.466(±0.091) pairwise=0.736
liter     sign_split       probe τ=0.359(±0.139) pairwise=0.682   |   cosine τ=0.475(±0.075) pairwise=0.740
second    sign_split       probe τ=0.489(±0.145) pairwise=0.747   |   cosine τ=0.482(±0.138) pairwise=0.744
meter     scientific       probe τ=0.427(±0.096) pairwise=0.713   |   cosine τ=0.319(±0.122) pairwise=0.660
kilogram  scientific       probe τ=0.416(±0.065) pairwise=0.708   |   cosine τ=0.292(±0.121) pairwise=0.646
liter     scientific       probe τ=0.441(±0.124) pairwise=0.721   |   cosine τ=0.321(±0.115) pairwise=0.660
second    scientific       probe τ=0.394(±0.085) pairwise=0.697   |   cosine τ=0.329(±0.107) pairwise=0.664

             model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
Qwen3_Embedding_8B      0.414982       0.709402     0.047408       0.02434             0.337001              0.670181            0.086865             0.043705

,model,unit,range,kendall,pairwise,kendall_cosine,pairwise_cosine,kendall_sd_splits,kendall_cosine_sd_splits,alpha_median,n_splits,n_train_pairs,n_train_items,n_test_items
0,all_MiniLM_L6_v2,meter,local_0_10,0.576620,0.790989,0.501545,0.754045,0.166925,0.140543,0.01,5,364,14,7
1,all_MiniLM_L6_v2,kilogram,local_0_10,0.567783,0.785934,0.481814,0.743820,0.190263,0.092168,0.01,5,364,14,7
2,all_MiniLM_L6_v2,liter,local_0_10,0.580728,0.793208,0.509030,0.757718,0.138605,0.131197,0.01,5,364,14,7
3,all_MiniLM_L6_v2,second,local_0_10,0.545342,0.774935,0.393496,0.699288,0.122473,0.095776,0.01,5,364,14,7
4,all_MiniLM_L6_v2,meter,medium_0_1000,0.502110,0.754631,0.398138,0.702051,0.159232,0.119772,0.01,5,364,14,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,Qwen3_Embedding_8B,second,sign_split,0.489269,0.747452,0.481829,0.743841,0.145291,0.137654,0.01,5,364,14,7
156,Qwen3_Embedding_8B,meter,scientific,0.426984,0.713492,0.319048,0.659524,0.096454,0.122104,0.01,5,480,16,9
157,Qwen3_Embedding_8B,kilogram,scientific,0.415873,0.707937,0.292063,0.646032,0.065108,0.120937,0.01,5,480,16,9
158,Qwen3_Embedding_8B,liter,scientific,0.441270,0.720635,0.320635,0.660317,0.123794,0.115093,0.01,5,480,16,9
159,Qwen3_Embedding_8B,second,scientific,0.393651,0.696825,0.328571,0.664286,0.085036,0.107011,0.01,5,480,16,9

### Run: extended models

#### PT1

In [ ]:
NEW_MODELS_1 = [
    "sentence-transformers/LaBSE",
    "sentence-transformers/paraphrase-multilingual-mpnet-base-v2",
    "intfloat/multilingual-e5-base",
    "intfloat/multilingual-e5-large",
    "intfloat/multilingual-e5-large-instruct",
    "BAAI/bge-m3",
    "google/embeddinggemma-300m",
]

run_regression(NEW_MODELS_1)

================================================================================
sentence-transformers/LaBSE
================================================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.713(±0.124) pairwise=0.861   |   cosine τ=0.332(±0.050) pairwise=0.668
kilogram  local_0_10       probe τ=0.694(±0.133) pairwise=0.852   |   cosine τ=0.405(±0.054) pairwise=0.705
liter     local_0_10       probe τ=0.695(±0.079) pairwise=0.852   |   cosine τ=0.393(±0.097) pairwise=0.699
second    local_0_10       probe τ=0.622(±0.123) pairwise=0.816   |   cosine τ=0.302(±0.121) pairwise=0.653
meter     medium_0_1000    probe τ=0.734(±0.055) pairwise=0.872   |   cosine τ=0.582(±0.092) pairwise=0.795
kilogram  medium_0_1000    probe τ=0.715(±0.060) pairwise=0.862   |   cosine τ=0.557(±0.116) pairwise=0.783
liter     medium_0_1000    probe τ=0.737(±0.039) pairwise=0.873   |   cosine τ=0.614(±0.089) pairwise=0.811
second    medium_0_1000    probe τ=0.655(±0.112) pairwise=0.832   |   cosine τ=0.452(±0.095) pairwise=0.729
meter     log_1_100k       probe τ=0.477(±0.117) pairwise=0.739   |   cosine τ=0.543(±0.113) pairwise=0.772
kilogram  log_1_100k       probe τ=0.435(±0.121) pairwise=0.718   |   cosine τ=0.465(±0.099) pairwise=0.733
liter     log_1_100k       probe τ=0.421(±0.114) pairwise=0.711   |   cosine τ=0.448(±0.074) pairwise=0.724
second    log_1_100k       probe τ=0.485(±0.111) pairwise=0.742   |   cosine τ=0.500(±0.108) pairwise=0.750
meter     sign_split       probe τ=0.410(±0.087) pairwise=0.708   |   cosine τ=0.519(±0.125) pairwise=0.764
kilogram  sign_split       probe τ=0.294(±0.085) pairwise=0.649   |   cosine τ=0.425(±0.184) pairwise=0.715
liter     sign_split       probe τ=0.324(±0.122) pairwise=0.664   |   cosine τ=0.506(±0.161) pairwise=0.757
second    sign_split       probe τ=0.332(±0.106) pairwise=0.669   |   cosine τ=0.437(±0.116) pairwise=0.722
meter     scientific       probe τ=0.351(±0.142) pairwise=0.675   |   cosine τ=0.298(±0.112) pairwise=0.649
kilogram  scientific       probe τ=0.286(±0.148) pairwise=0.643   |   cosine τ=0.305(±0.121) pairwise=0.652
liter     scientific       probe τ=0.330(±0.124) pairwise=0.665   |   cosine τ=0.330(±0.108) pairwise=0.665
second    scientific       probe τ=0.305(±0.125) pairwise=0.652   |   cosine τ=0.298(±0.110) pairwise=0.649

model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
LaBSE       0.50067       0.752722     0.173673      0.088596             0.435549              0.719746            0.101191              0.05156
================================================================================
sentence-transformers/paraphrase-multilingual-mpnet-base-v2
================================================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.663(±0.081) pairwise=0.835   |   cosine τ=0.566(±0.078) pairwise=0.786
kilogram  local_0_10       probe τ=0.701(±0.104) pairwise=0.855   |   cosine τ=0.447(±0.161) pairwise=0.727
liter     local_0_10       probe τ=0.635(±0.076) pairwise=0.821   |   cosine τ=0.440(±0.143) pairwise=0.723
second    local_0_10       probe τ=0.628(±0.038) pairwise=0.818   |   cosine τ=0.463(±0.075) pairwise=0.735
meter     medium_0_1000    probe τ=0.255(±0.148) pairwise=0.629   |   cosine τ=0.471(±0.139) pairwise=0.738
kilogram  medium_0_1000    probe τ=0.235(±0.150) pairwise=0.619   |   cosine τ=0.276(±0.129) pairwise=0.640
liter     medium_0_1000    probe τ=0.169(±0.153) pairwise=0.586   |   cosine τ=0.351(±0.211) pairwise=0.678
second    medium_0_1000    probe τ=0.247(±0.167) pairwise=0.625   |   cosine τ=0.459(±0.099) pairwise=0.733
meter     log_1_100k       probe τ=0.132(±0.118) pairwise=0.566   |   cosine τ=0.014(±0.078) pairwise=0.507
kilogram  log_1_100k       probe τ=0.173(±0.078) pairwise=0.587   |   cosine τ=0.076(±0.110) pairwise=0.538
liter     log_1_100k       probe τ=0.124(±0.038) pairwise=0.562   |   cosine τ=-0.014(±0.046) pairwise=0.493
second    log_1_100k       probe τ=0.084(±0.083) pairwise=0.542   |   cosine τ=0.087(±0.105) pairwise=0.544
meter     sign_split       probe τ=-0.005(±0.231) pairwise=0.498   |   cosine τ=0.021(±0.136) pairwise=0.511
kilogram  sign_split       probe τ=0.012(±0.219) pairwise=0.507   |   cosine τ=-0.061(±0.164) pairwise=0.469
liter     sign_split       probe τ=-0.011(±0.193) pairwise=0.495   |   cosine τ=-0.018(±0.131) pairwise=0.492
second    sign_split       probe τ=0.060(±0.165) pairwise=0.531   |   cosine τ=0.035(±0.101) pairwise=0.518
meter     scientific       probe τ=0.302(±0.077) pairwise=0.651   |   cosine τ=0.111(±0.158) pairwise=0.556
kilogram  scientific       probe τ=0.343(±0.077) pairwise=0.671   |   cosine τ=0.092(±0.143) pairwise=0.546
liter     scientific       probe τ=0.321(±0.130) pairwise=0.660   |   cosine τ=0.119(±0.160) pairwise=0.560
second    scientific       probe τ=0.303(±0.085) pairwise=0.652   |   cosine τ=0.149(±0.199) pairwise=0.575

                                model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
paraphrase_multilingual_mpnet_base_v2      0.268532       0.635484     0.226307      0.114271             0.204228              0.603354            0.205619             0.104152
================================================================================
intfloat/multilingual-e5-base
================================================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.524(±0.155) pairwise=0.765   |   cosine τ=0.320(±0.172) pairwise=0.662
kilogram  local_0_10       probe τ=0.586(±0.130) pairwise=0.797   |   cosine τ=0.352(±0.182) pairwise=0.679
liter     local_0_10       probe τ=0.525(±0.076) pairwise=0.766   |   cosine τ=0.340(±0.191) pairwise=0.672
second    local_0_10       probe τ=0.486(±0.142) pairwise=0.746   |   cosine τ=0.308(±0.198) pairwise=0.656
meter     medium_0_1000    probe τ=0.440(±0.185) pairwise=0.723   |   cosine τ=0.319(±0.106) pairwise=0.663
kilogram  medium_0_1000    probe τ=0.441(±0.150) pairwise=0.724   |   cosine τ=0.349(±0.078) pairwise=0.678
liter     medium_0_1000    probe τ=0.487(±0.067) pairwise=0.747   |   cosine τ=0.368(±0.114) pairwise=0.687
second    medium_0_1000    probe τ=0.418(±0.152) pairwise=0.712   |   cosine τ=0.369(±0.055) pairwise=0.688
meter     log_1_100k       probe τ=0.304(±0.139) pairwise=0.652   |   cosine τ=0.399(±0.115) pairwise=0.699
kilogram  log_1_100k       probe τ=0.289(±0.082) pairwise=0.645   |   cosine τ=0.326(±0.119) pairwise=0.663
liter     log_1_100k       probe τ=0.288(±0.135) pairwise=0.644   |   cosine τ=0.330(±0.110) pairwise=0.665
second    log_1_100k       probe τ=0.343(±0.111) pairwise=0.672   |   cosine τ=0.410(±0.077) pairwise=0.705
meter     sign_split       probe τ=0.371(±0.196) pairwise=0.688   |   cosine τ=0.354(±0.120) pairwise=0.678
kilogram  sign_split       probe τ=0.359(±0.222) pairwise=0.682   |   cosine τ=0.324(±0.150) pairwise=0.664
liter     sign_split       probe τ=0.301(±0.157) pairwise=0.653   |   cosine τ=0.313(±0.159) pairwise=0.658
second    sign_split       probe τ=0.233(±0.142) pairwise=0.618   |   cosine τ=0.292(±0.149) pairwise=0.647
meter     scientific       probe τ=0.375(±0.172) pairwise=0.687   |   cosine τ=0.235(±0.128) pairwise=0.617
kilogram  scientific       probe τ=0.383(±0.163) pairwise=0.691   |   cosine τ=0.232(±0.091) pairwise=0.616
liter     scientific       probe τ=0.340(±0.149) pairwise=0.670   |   cosine τ=0.222(±0.104) pairwise=0.611
second    scientific       probe τ=0.373(±0.112) pairwise=0.687   |   cosine τ=0.222(±0.111) pairwise=0.611

               model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
multilingual_e5_base      0.393187       0.698434     0.093537      0.047818             0.319085              0.660992            0.055054             0.028106
================================================================================
intfloat/multilingual-e5-large
================================================================================

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.539(±0.075) pairwise=0.773   |   cosine τ=0.382(±0.112) pairwise=0.694
kilogram  local_0_10       probe τ=0.555(±0.149) pairwise=0.781   |   cosine τ=0.314(±0.130) pairwise=0.660
liter     local_0_10       probe τ=0.528(±0.164) pairwise=0.768   |   cosine τ=0.348(±0.095) pairwise=0.676
second    local_0_10       probe τ=0.459(±0.115) pairwise=0.733   |   cosine τ=0.273(±0.132) pairwise=0.638
meter     medium_0_1000    probe τ=0.474(±0.200) pairwise=0.739   |   cosine τ=0.451(±0.129) pairwise=0.728
kilogram  medium_0_1000    probe τ=0.431(±0.294) pairwise=0.718   |   cosine τ=0.425(±0.146) pairwise=0.715
liter     medium_0_1000    probe τ=0.501(±0.228) pairwise=0.753   |   cosine τ=0.379(±0.131) pairwise=0.692
second    medium_0_1000    probe τ=0.498(±0.266) pairwise=0.752   |   cosine τ=0.355(±0.106) pairwise=0.680
meter     log_1_100k       probe τ=0.381(±0.108) pairwise=0.691   |   cosine τ=0.375(±0.092) pairwise=0.688
kilogram  log_1_100k       probe τ=0.434(±0.094) pairwise=0.717   |   cosine τ=0.350(±0.102) pairwise=0.675
liter     log_1_100k       probe τ=0.397(±0.101) pairwise=0.699   |   cosine τ=0.400(±0.106) pairwise=0.700
second    log_1_100k       probe τ=0.449(±0.076) pairwise=0.725   |   cosine τ=0.442(±0.108) pairwise=0.721
meter     sign_split       probe τ=0.410(±0.109) pairwise=0.708   |   cosine τ=0.531(±0.107) pairwise=0.768
kilogram  sign_split       probe τ=0.509(±0.046) pairwise=0.758   |   cosine τ=0.492(±0.114) pairwise=0.748
liter     sign_split       probe τ=0.505(±0.067) pairwise=0.756   |   cosine τ=0.435(±0.128) pairwise=0.720
second    sign_split       probe τ=0.445(±0.102) pairwise=0.726   |   cosine τ=0.581(±0.111) pairwise=0.794
meter     scientific       probe τ=0.295(±0.158) pairwise=0.648   |   cosine τ=0.273(±0.083) pairwise=0.637
kilogram  scientific       probe τ=0.330(±0.113) pairwise=0.665   |   cosine τ=0.316(±0.072) pairwise=0.658
liter     scientific       probe τ=0.316(±0.112) pairwise=0.658   |   cosine τ=0.246(±0.093) pairwise=0.623
second    scientific       probe τ=0.249(±0.159) pairwise=0.625   |   cosine τ=0.241(±0.118) pairwise=0.621

                model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
multilingual_e5_large       0.43529       0.719518     0.085597      0.044025             0.380376              0.691732            0.092075             0.046744
================================================================================
intfloat/multilingual-e5-large-instruct
================================================================================

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.720(±0.101) pairwise=0.863   |   cosine τ=0.570(±0.099) pairwise=0.788
kilogram  local_0_10       probe τ=0.759(±0.101) pairwise=0.883   |   cosine τ=0.559(±0.084) pairwise=0.783
liter     local_0_10       probe τ=0.770(±0.124) pairwise=0.889   |   cosine τ=0.540(±0.056) pairwise=0.773
second    local_0_10       probe τ=0.690(±0.095) pairwise=0.849   |   cosine τ=0.385(±0.139) pairwise=0.695
meter     medium_0_1000    probe τ=0.612(±0.147) pairwise=0.809   |   cosine τ=0.465(±0.106) pairwise=0.735
kilogram  medium_0_1000    probe τ=0.589(±0.143) pairwise=0.798   |   cosine τ=0.498(±0.189) pairwise=0.753
liter     medium_0_1000    probe τ=0.601(±0.139) pairwise=0.804   |   cosine τ=0.483(±0.146) pairwise=0.745
second    medium_0_1000    probe τ=0.636(±0.143) pairwise=0.822   |   cosine τ=0.547(±0.165) pairwise=0.776
meter     log_1_100k       probe τ=0.470(±0.112) pairwise=0.735   |   cosine τ=0.453(±0.103) pairwise=0.727
kilogram  log_1_100k       probe τ=0.523(±0.079) pairwise=0.762   |   cosine τ=0.321(±0.102) pairwise=0.660
liter     log_1_100k       probe τ=0.516(±0.108) pairwise=0.758   |   cosine τ=0.356(±0.105) pairwise=0.678
second    log_1_100k       probe τ=0.548(±0.105) pairwise=0.774   |   cosine τ=0.585(±0.111) pairwise=0.793
meter     sign_split       probe τ=0.411(±0.152) pairwise=0.709   |   cosine τ=0.462(±0.134) pairwise=0.733
kilogram  sign_split       probe τ=0.372(±0.153) pairwise=0.690   |   cosine τ=0.450(±0.181) pairwise=0.727
liter     sign_split       probe τ=0.387(±0.138) pairwise=0.697   |   cosine τ=0.473(±0.195) pairwise=0.739
second    sign_split       probe τ=0.499(±0.158) pairwise=0.753   |   cosine τ=0.624(±0.074) pairwise=0.815
meter     scientific       probe τ=0.333(±0.212) pairwise=0.667   |   cosine τ=0.306(±0.087) pairwise=0.653
kilogram  scientific       probe τ=0.310(±0.159) pairwise=0.655   |   cosine τ=0.310(±0.086) pairwise=0.655
liter     scientific       probe τ=0.308(±0.182) pairwise=0.654   |   cosine τ=0.290(±0.104) pairwise=0.645
second    scientific       probe τ=0.229(±0.149) pairwise=0.614   |   cosine τ=0.271(±0.129) pairwise=0.636

                         model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
multilingual_e5_large_instruct         0.514       0.759209      0.15967         0.081             0.447328               0.72541            0.108498             0.055376
================================================================================
BAAI/bge-m3
================================================================================

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.729(±0.055) pairwise=0.869   |   cosine τ=0.328(±0.179) pairwise=0.666
kilogram  local_0_10       probe τ=0.747(±0.078) pairwise=0.878   |   cosine τ=0.444(±0.136) pairwise=0.725
liter     local_0_10       probe τ=0.679(±0.153) pairwise=0.844   |   cosine τ=0.398(±0.196) pairwise=0.702
second    local_0_10       probe τ=0.639(±0.132) pairwise=0.823   |   cosine τ=0.281(±0.172) pairwise=0.642
meter     medium_0_1000    probe τ=0.483(±0.147) pairwise=0.745   |   cosine τ=0.370(±0.085) pairwise=0.687
kilogram  medium_0_1000    probe τ=0.499(±0.117) pairwise=0.754   |   cosine τ=0.510(±0.098) pairwise=0.759
liter     medium_0_1000    probe τ=0.526(±0.149) pairwise=0.767   |   cosine τ=0.509(±0.150) pairwise=0.758
second    medium_0_1000    probe τ=0.438(±0.142) pairwise=0.723   |   cosine τ=0.444(±0.114) pairwise=0.725
meter     log_1_100k       probe τ=0.299(±0.085) pairwise=0.649   |   cosine τ=0.551(±0.100) pairwise=0.776
kilogram  log_1_100k       probe τ=0.303(±0.084) pairwise=0.652   |   cosine τ=0.424(±0.131) pairwise=0.712
liter     log_1_100k       probe τ=0.256(±0.124) pairwise=0.628   |   cosine τ=0.445(±0.134) pairwise=0.723
second    log_1_100k       probe τ=0.310(±0.036) pairwise=0.655   |   cosine τ=0.478(±0.133) pairwise=0.739
meter     sign_split       probe τ=0.170(±0.098) pairwise=0.586   |   cosine τ=0.403(±0.086) pairwise=0.705
kilogram  sign_split       probe τ=0.239(±0.094) pairwise=0.621   |   cosine τ=0.286(±0.105) pairwise=0.645
liter     sign_split       probe τ=0.196(±0.091) pairwise=0.599   |   cosine τ=0.228(±0.224) pairwise=0.616
second    sign_split       probe τ=0.270(±0.052) pairwise=0.636   |   cosine τ=0.501(±0.166) pairwise=0.754
meter     scientific       probe τ=0.303(±0.193) pairwise=0.652   |   cosine τ=0.203(±0.084) pairwise=0.602
kilogram  scientific       probe τ=0.286(±0.152) pairwise=0.643   |   cosine τ=0.203(±0.071) pairwise=0.602
liter     scientific       probe τ=0.317(±0.201) pairwise=0.659   |   cosine τ=0.213(±0.095) pairwise=0.606
second    scientific       probe τ=0.241(±0.205) pairwise=0.621   |   cosine τ=0.244(±0.080) pairwise=0.622

 model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
bge_m3      0.396484       0.700123     0.183214      0.093213               0.3732               0.68825            0.115822             0.058541
================================================================================
google/embeddinggemma-300m
================================================================================

Loading weights:   0%|          | 0/314 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.292(±0.130) pairwise=0.647   |   cosine τ=0.316(±0.176) pairwise=0.660
kilogram  local_0_10       probe τ=0.215(±0.227) pairwise=0.609   |   cosine τ=0.286(±0.132) pairwise=0.645
liter     local_0_10       probe τ=0.257(±0.178) pairwise=0.630   |   cosine τ=0.320(±0.123) pairwise=0.662
second    local_0_10       probe τ=0.272(±0.153) pairwise=0.637   |   cosine τ=0.359(±0.165) pairwise=0.682
meter     medium_0_1000    probe τ=0.484(±0.078) pairwise=0.746   |   cosine τ=0.415(±0.120) pairwise=0.711
kilogram  medium_0_1000    probe τ=0.424(±0.222) pairwise=0.715   |   cosine τ=0.464(±0.077) pairwise=0.736
liter     medium_0_1000    probe τ=0.312(±0.208) pairwise=0.658   |   cosine τ=0.406(±0.105) pairwise=0.707
second    medium_0_1000    probe τ=0.456(±0.172) pairwise=0.731   |   cosine τ=0.434(±0.115) pairwise=0.721
meter     log_1_100k       probe τ=0.124(±0.192) pairwise=0.562   |   cosine τ=0.330(±0.105) pairwise=0.665
kilogram  log_1_100k       probe τ=0.183(±0.086) pairwise=0.591   |   cosine τ=0.238(±0.112) pairwise=0.619
liter     log_1_100k       probe τ=0.140(±0.140) pairwise=0.570   |   cosine τ=0.260(±0.109) pairwise=0.630
second    log_1_100k       probe τ=0.173(±0.154) pairwise=0.587   |   cosine τ=0.238(±0.064) pairwise=0.619
meter     sign_split       probe τ=0.027(±0.257) pairwise=0.514   |   cosine τ=0.262(±0.219) pairwise=0.633
kilogram  sign_split       probe τ=0.074(±0.211) pairwise=0.538   |   cosine τ=0.150(±0.123) pairwise=0.575
liter     sign_split       probe τ=-0.050(±0.292) pairwise=0.475   |   cosine τ=0.100(±0.179) pairwise=0.550
second    sign_split       probe τ=0.055(±0.242) pairwise=0.528   |   cosine τ=0.201(±0.313) pairwise=0.602
meter     scientific       probe τ=0.194(±0.088) pairwise=0.597   |   cosine τ=0.271(±0.080) pairwise=0.636
kilogram  scientific       probe τ=0.205(±0.057) pairwise=0.602   |   cosine τ=0.224(±0.055) pairwise=0.612
liter     scientific       probe τ=0.184(±0.105) pairwise=0.592   |   cosine τ=0.190(±0.070) pairwise=0.595
second    scientific       probe τ=0.179(±0.090) pairwise=0.590   |   cosine τ=0.189(±0.070) pairwise=0.594

              model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
embeddinggemma_300m      0.210069        0.60596     0.138453      0.070208             0.282725              0.642717            0.098112             0.050245

,model,unit,range,kendall,pairwise,kendall_cosine,pairwise_cosine,kendall_sd_splits,kendall_cosine_sd_splits,alpha_median,n_splits,n_train_pairs,n_train_items,n_test_items
0,LaBSE,meter,local_0_10,0.713135,0.860931,0.331608,0.667860,0.123785,0.049857,0.01,5,364,14,7
1,LaBSE,kilogram,local_0_10,0.694489,0.851816,0.405088,0.705181,0.132896,0.053585,0.01,5,364,14,7
2,LaBSE,liter,local_0_10,0.694622,0.851952,0.392827,0.698608,0.079150,0.096925,0.01,5,364,14,7
3,LaBSE,second,local_0_10,0.622093,0.815604,0.301548,0.653051,0.122864,0.121460,0.01,5,364,14,7
4,LaBSE,meter,medium_0_1000,0.733520,0.871816,0.582347,0.794861,0.054950,0.091981,0.01,5,364,14,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,embeddinggemma_300m,second,sign_split,0.054812,0.528174,0.200865,0.601852,0.241904,0.313309,0.01,5,364,14,7
136,embeddinggemma_300m,meter,scientific,0.193651,0.596825,0.271429,0.635714,0.087949,0.080429,0.01,5,480,16,9
137,embeddinggemma_300m,kilogram,scientific,0.204762,0.602381,0.223810,0.611905,0.056511,0.054526,0.01,5,480,16,9
138,embeddinggemma_300m,liter,scientific,0.184127,0.592063,0.190476,0.595238,0.105499,0.069868,0.01,5,480,16,9
139,embeddinggemma_300m,second,scientific,0.179365,0.589683,0.188889,0.594444,0.090246,0.069507,0.01,5,480,16,9

#### PT2

In [ ]:
NEW_MODELS_2 = [
    # "Alibaba-NLP/gte-multilingual-base",
    # "Alibaba-NLP/gte-large-en-v1.5",
    "ibm-granite/granite-embedding-107m-multilingual",
    "ibm-granite/granite-embedding-278m-multilingual",
    "ibm-granite/granite-embedding-english-r2",
    "ibm-granite/granite-embedding-97m-multilingual-r2",
    "ibm-granite/granite-embedding-311m-multilingual-r2",
]

run_regression(NEW_MODELS_2)

================================================================================
ibm-granite/granite-embedding-107m-multilingual
================================================================================

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.110(±0.251) pairwise=0.555   |   cosine τ=0.331(±0.164) pairwise=0.667
kilogram  local_0_10       probe τ=0.176(±0.142) pairwise=0.588   |   cosine τ=0.409(±0.175) pairwise=0.707
liter     local_0_10       probe τ=0.171(±0.228) pairwise=0.586   |   cosine τ=0.417(±0.113) pairwise=0.711
second    local_0_10       probe τ=0.156(±0.223) pairwise=0.578   |   cosine τ=0.361(±0.154) pairwise=0.682
meter     medium_0_1000    probe τ=0.339(±0.250) pairwise=0.672   |   cosine τ=0.374(±0.246) pairwise=0.689
kilogram  medium_0_1000    probe τ=0.254(±0.293) pairwise=0.628   |   cosine τ=0.366(±0.244) pairwise=0.685
liter     medium_0_1000    probe τ=0.304(±0.262) pairwise=0.653   |   cosine τ=0.404(±0.183) pairwise=0.704
second    medium_0_1000    probe τ=0.323(±0.282) pairwise=0.663   |   cosine τ=0.369(±0.234) pairwise=0.686
meter     log_1_100k       probe τ=0.251(±0.057) pairwise=0.626   |   cosine τ=0.387(±0.081) pairwise=0.694
kilogram  log_1_100k       probe τ=0.224(±0.073) pairwise=0.612   |   cosine τ=0.344(±0.058) pairwise=0.672
liter     log_1_100k       probe τ=0.240(±0.085) pairwise=0.620   |   cosine τ=0.395(±0.067) pairwise=0.698
second    log_1_100k       probe τ=0.294(±0.078) pairwise=0.647   |   cosine τ=0.384(±0.074) pairwise=0.692
meter     sign_split       probe τ=0.114(±0.165) pairwise=0.559   |   cosine τ=0.159(±0.189) pairwise=0.581
kilogram  sign_split       probe τ=0.045(±0.226) pairwise=0.524   |   cosine τ=0.136(±0.189) pairwise=0.569
liter     sign_split       probe τ=0.068(±0.309) pairwise=0.536   |   cosine τ=0.102(±0.211) pairwise=0.552
second    sign_split       probe τ=0.064(±0.209) pairwise=0.533   |   cosine τ=0.155(±0.180) pairwise=0.579
meter     scientific       probe τ=0.246(±0.174) pairwise=0.623   |   cosine τ=0.205(±0.134) pairwise=0.602
kilogram  scientific       probe τ=0.252(±0.177) pairwise=0.626   |   cosine τ=0.198(±0.107) pairwise=0.599
liter     scientific       probe τ=0.194(±0.137) pairwise=0.597   |   cosine τ=0.203(±0.118) pairwise=0.602
second    scientific       probe τ=0.252(±0.141) pairwise=0.626   |   cosine τ=0.163(±0.115) pairwise=0.582

                              model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
granite_embedding_107m_multilingual      0.203846       0.602583     0.088269       0.04408             0.293116               0.64765            0.111177             0.055898
================================================================================
ibm-granite/granite-embedding-278m-multilingual
================================================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.531(±0.171) pairwise=0.768   |   cosine τ=0.328(±0.093) pairwise=0.666
kilogram  local_0_10       probe τ=0.504(±0.166) pairwise=0.754   |   cosine τ=0.297(±0.088) pairwise=0.650
liter     local_0_10       probe τ=0.500(±0.143) pairwise=0.752   |   cosine τ=0.332(±0.091) pairwise=0.668
second    local_0_10       probe τ=0.477(±0.160) pairwise=0.741   |   cosine τ=0.290(±0.141) pairwise=0.647
meter     medium_0_1000    probe τ=0.547(±0.135) pairwise=0.777   |   cosine τ=0.470(±0.222) pairwise=0.738
kilogram  medium_0_1000    probe τ=0.578(±0.098) pairwise=0.792   |   cosine τ=0.397(±0.219) pairwise=0.701
liter     medium_0_1000    probe τ=0.585(±0.086) pairwise=0.796   |   cosine τ=0.420(±0.217) pairwise=0.713
second    medium_0_1000    probe τ=0.605(±0.074) pairwise=0.806   |   cosine τ=0.455(±0.198) pairwise=0.730
meter     log_1_100k       probe τ=0.184(±0.204) pairwise=0.592   |   cosine τ=0.375(±0.068) pairwise=0.687
kilogram  log_1_100k       probe τ=0.224(±0.117) pairwise=0.612   |   cosine τ=0.384(±0.065) pairwise=0.692
liter     log_1_100k       probe τ=0.205(±0.158) pairwise=0.602   |   cosine τ=0.365(±0.086) pairwise=0.683
second    log_1_100k       probe τ=0.209(±0.119) pairwise=0.605   |   cosine τ=0.410(±0.071) pairwise=0.705
meter     sign_split       probe τ=0.100(±0.159) pairwise=0.551   |   cosine τ=0.185(±0.221) pairwise=0.593
kilogram  sign_split       probe τ=0.051(±0.157) pairwise=0.526   |   cosine τ=0.139(±0.164) pairwise=0.570
liter     sign_split       probe τ=0.085(±0.153) pairwise=0.544   |   cosine τ=0.166(±0.160) pairwise=0.584
second    sign_split       probe τ=0.162(±0.123) pairwise=0.582   |   cosine τ=0.162(±0.190) pairwise=0.582
meter     scientific       probe τ=0.249(±0.108) pairwise=0.625   |   cosine τ=0.203(±0.096) pairwise=0.602
kilogram  scientific       probe τ=0.286(±0.134) pairwise=0.643   |   cosine τ=0.195(±0.070) pairwise=0.598
liter     scientific       probe τ=0.279(±0.134) pairwise=0.640   |   cosine τ=0.225(±0.085) pairwise=0.613
second    scientific       probe τ=0.278(±0.095) pairwise=0.639   |   cosine τ=0.198(±0.115) pairwise=0.599

                              model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
granite_embedding_278m_multilingual       0.33199       0.667318     0.187148      0.094781             0.299829              0.651071            0.107626             0.054318
================================================================================
ibm-granite/granite-embedding-english-r2
================================================================================

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.569(±0.149) pairwise=0.789   |   cosine τ=0.365(±0.054) pairwise=0.686
kilogram  local_0_10       probe τ=0.510(±0.194) pairwise=0.759   |   cosine τ=0.372(±0.106) pairwise=0.689
liter     local_0_10       probe τ=0.545(±0.124) pairwise=0.776   |   cosine τ=0.386(±0.082) pairwise=0.696
second    local_0_10       probe τ=0.475(±0.213) pairwise=0.741   |   cosine τ=0.364(±0.123) pairwise=0.685
meter     medium_0_1000    probe τ=0.393(±0.138) pairwise=0.698   |   cosine τ=0.329(±0.161) pairwise=0.667
kilogram  medium_0_1000    probe τ=0.416(±0.147) pairwise=0.711   |   cosine τ=0.383(±0.156) pairwise=0.695
liter     medium_0_1000    probe τ=0.319(±0.219) pairwise=0.661   |   cosine τ=0.330(±0.167) pairwise=0.668
second    medium_0_1000    probe τ=0.273(±0.196) pairwise=0.638   |   cosine τ=0.340(±0.162) pairwise=0.672
meter     log_1_100k       probe τ=0.086(±0.155) pairwise=0.543   |   cosine τ=0.135(±0.086) pairwise=0.567
kilogram  log_1_100k       probe τ=0.151(±0.073) pairwise=0.576   |   cosine τ=0.195(±0.089) pairwise=0.598
liter     log_1_100k       probe τ=0.057(±0.125) pairwise=0.529   |   cosine τ=0.197(±0.094) pairwise=0.598
second    log_1_100k       probe τ=0.086(±0.127) pairwise=0.543   |   cosine τ=0.126(±0.110) pairwise=0.563
meter     sign_split       probe τ=0.072(±0.184) pairwise=0.538   |   cosine τ=0.206(±0.120) pairwise=0.605
kilogram  sign_split       probe τ=0.052(±0.226) pairwise=0.528   |   cosine τ=0.210(±0.085) pairwise=0.607
liter     sign_split       probe τ=0.078(±0.152) pairwise=0.540   |   cosine τ=0.115(±0.206) pairwise=0.558
second    sign_split       probe τ=0.129(±0.200) pairwise=0.566   |   cosine τ=0.212(±0.135) pairwise=0.608
meter     scientific       probe τ=0.298(±0.076) pairwise=0.649   |   cosine τ=0.254(±0.106) pairwise=0.627
kilogram  scientific       probe τ=0.281(±0.070) pairwise=0.640   |   cosine τ=0.181(±0.115) pairwise=0.590
liter     scientific       probe τ=0.297(±0.067) pairwise=0.648   |   cosine τ=0.184(±0.101) pairwise=0.592
second    scientific       probe τ=0.257(±0.071) pairwise=0.629   |   cosine τ=0.214(±0.113) pairwise=0.607

                       model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
granite_embedding_english_r2      0.267299       0.635157      0.17399      0.088091             0.254835              0.628889            0.093339             0.047877
================================================================================
ibm-granite/granite-embedding-97m-multilingual-r2
================================================================================

Loading weights:   0%|          | 0/74 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.546(±0.195) pairwise=0.776   |   cosine τ=0.278(±0.093) pairwise=0.641
kilogram  local_0_10       probe τ=0.558(±0.206) pairwise=0.782   |   cosine τ=0.216(±0.189) pairwise=0.610
liter     local_0_10       probe τ=0.531(±0.148) pairwise=0.768   |   cosine τ=0.202(±0.183) pairwise=0.603
second    local_0_10       probe τ=0.524(±0.138) pairwise=0.765   |   cosine τ=0.278(±0.169) pairwise=0.641
meter     medium_0_1000    probe τ=0.250(±0.170) pairwise=0.627   |   cosine τ=0.417(±0.216) pairwise=0.711
kilogram  medium_0_1000    probe τ=0.186(±0.199) pairwise=0.594   |   cosine τ=0.383(±0.167) pairwise=0.695
liter     medium_0_1000    probe τ=0.149(±0.137) pairwise=0.575   |   cosine τ=0.321(±0.161) pairwise=0.663
second    medium_0_1000    probe τ=0.139(±0.172) pairwise=0.570   |   cosine τ=0.309(±0.171) pairwise=0.657
meter     log_1_100k       probe τ=0.006(±0.097) pairwise=0.503   |   cosine τ=0.083(±0.084) pairwise=0.541
kilogram  log_1_100k       probe τ=0.100(±0.137) pairwise=0.550   |   cosine τ=0.105(±0.149) pairwise=0.552
liter     log_1_100k       probe τ=0.025(±0.121) pairwise=0.513   |   cosine τ=0.187(±0.132) pairwise=0.594
second    log_1_100k       probe τ=0.100(±0.129) pairwise=0.550   |   cosine τ=0.108(±0.086) pairwise=0.554
meter     sign_split       probe τ=0.422(±0.160) pairwise=0.715   |   cosine τ=0.333(±0.214) pairwise=0.669
kilogram  sign_split       probe τ=0.430(±0.143) pairwise=0.719   |   cosine τ=0.483(±0.237) pairwise=0.745
liter     sign_split       probe τ=0.380(±0.121) pairwise=0.693   |   cosine τ=0.406(±0.201) pairwise=0.706
second    sign_split       probe τ=0.410(±0.226) pairwise=0.708   |   cosine τ=0.328(±0.244) pairwise=0.666
meter     scientific       probe τ=0.202(±0.151) pairwise=0.601   |   cosine τ=0.227(±0.107) pairwise=0.613
kilogram  scientific       probe τ=0.267(±0.120) pairwise=0.633   |   cosine τ=0.227(±0.120) pairwise=0.613
liter     scientific       probe τ=0.235(±0.145) pairwise=0.617   |   cosine τ=0.238(±0.107) pairwise=0.619
second    scientific       probe τ=0.268(±0.039) pairwise=0.634   |   cosine τ=0.225(±0.164) pairwise=0.613

                                model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
granite_embedding_97m_multilingual_r2      0.286494        0.64476     0.177636      0.090107             0.267701              0.635324            0.107518             0.054926
================================================================================
ibm-granite/granite-embedding-311m-multilingual-r2
================================================================================

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.540(±0.145) pairwise=0.774   |   cosine τ=0.386(±0.095) pairwise=0.695
kilogram  local_0_10       probe τ=0.571(±0.173) pairwise=0.790   |   cosine τ=0.378(±0.061) pairwise=0.692
liter     local_0_10       probe τ=0.582(±0.191) pairwise=0.795   |   cosine τ=0.420(±0.093) pairwise=0.713
second    local_0_10       probe τ=0.467(±0.184) pairwise=0.737   |   cosine τ=0.359(±0.127) pairwise=0.682
meter     medium_0_1000    probe τ=0.405(±0.171) pairwise=0.705   |   cosine τ=0.337(±0.117) pairwise=0.671
kilogram  medium_0_1000    probe τ=0.386(±0.169) pairwise=0.696   |   cosine τ=0.325(±0.145) pairwise=0.665
liter     medium_0_1000    probe τ=0.398(±0.132) pairwise=0.702   |   cosine τ=0.343(±0.132) pairwise=0.674
second    medium_0_1000    probe τ=0.332(±0.106) pairwise=0.668   |   cosine τ=0.244(±0.179) pairwise=0.624
meter     log_1_100k       probe τ=0.210(±0.085) pairwise=0.605   |   cosine τ=0.165(±0.181) pairwise=0.583
kilogram  log_1_100k       probe τ=0.196(±0.083) pairwise=0.598   |   cosine τ=0.070(±0.149) pairwise=0.535
liter     log_1_100k       probe τ=0.251(±0.059) pairwise=0.626   |   cosine τ=0.135(±0.140) pairwise=0.568
second    log_1_100k       probe τ=0.207(±0.059) pairwise=0.604   |   cosine τ=0.098(±0.137) pairwise=0.549
meter     sign_split       probe τ=0.116(±0.287) pairwise=0.559   |   cosine τ=0.374(±0.175) pairwise=0.690
kilogram  sign_split       probe τ=0.297(±0.260) pairwise=0.651   |   cosine τ=0.420(±0.197) pairwise=0.713
liter     sign_split       probe τ=0.270(±0.266) pairwise=0.637   |   cosine τ=0.397(±0.185) pairwise=0.701
second    sign_split       probe τ=0.240(±0.197) pairwise=0.622   |   cosine τ=0.454(±0.210) pairwise=0.729
meter     scientific       probe τ=0.240(±0.072) pairwise=0.620   |   cosine τ=0.214(±0.079) pairwise=0.607
kilogram  scientific       probe τ=0.211(±0.076) pairwise=0.606   |   cosine τ=0.213(±0.090) pairwise=0.606
liter     scientific       probe τ=0.268(±0.092) pairwise=0.634   |   cosine τ=0.225(±0.100) pairwise=0.613
second    scientific       probe τ=0.243(±0.079) pairwise=0.621   |   cosine τ=0.219(±0.090) pairwise=0.610

                                 model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
granite_embedding_311m_multilingual_r2      0.321581       0.662423     0.134356      0.068457             0.288923              0.645961            0.115922             0.059082

,model,unit,range,kendall,pairwise,kendall_cosine,pairwise_cosine,kendall_sd_splits,kendall_cosine_sd_splits,alpha_median,n_splits,n_train_pairs,n_train_items,n_test_items
0,granite_embedding_107m_multilingual,meter,local_0_10,0.110007,0.554736,0.330672,0.666907,0.250519,0.164039,0.01,5,364,14,7
1,granite_embedding_107m_multilingual,kilogram,local_0_10,0.175914,0.588310,0.409032,0.707221,0.142370,0.174560,0.01,5,364,14,7
2,granite_embedding_107m_multilingual,liter,local_0_10,0.171391,0.585662,0.416502,0.710874,0.227871,0.113434,0.01,5,364,14,7
3,granite_embedding_107m_multilingual,second,local_0_10,0.155900,0.577792,0.361029,0.682030,0.223247,0.153867,0.01,5,364,14,7
4,granite_embedding_107m_multilingual,meter,medium_0_1000,0.339035,0.671502,0.373512,0.688812,0.249823,0.246236,0.01,5,364,14,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,granite_embedding_311m_multilingual_r2,second,sign_split,0.240282,0.622240,0.454120,0.729409,0.197165,0.210320,0.01,5,364,14,7
96,granite_embedding_311m_multilingual_r2,meter,scientific,0.239683,0.619841,0.214286,0.607143,0.072174,0.078967,0.01,5,480,16,9
97,granite_embedding_311m_multilingual_r2,kilogram,scientific,0.211111,0.605556,0.212698,0.606349,0.075834,0.089861,0.01,5,480,16,9
98,granite_embedding_311m_multilingual_r2,liter,scientific,0.268254,0.634127,0.225397,0.612698,0.091940,0.099539,0.01,5,480,16,9
99,granite_embedding_311m_multilingual_r2,second,scientific,0.242857,0.621429,0.219048,0.609524,0.079087,0.090246,0.01,5,480,16,9

#### PT3

In [ ]:
NEW_MODELS_3 = [
    "mixedbread-ai/mxbai-embed-large-v1",
    "microsoft/harrier-oss-v1-270m",
    "microsoft/harrier-oss-v1-0.6b",
    "lightonai/DenseOn",
]

run_regression(NEW_MODELS_3)

================================================================================
mixedbread-ai/mxbai-embed-large-v1
================================================================================

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.578(±0.240) pairwise=0.793   |   cosine τ=0.377(±0.130) pairwise=0.691
kilogram  local_0_10       probe τ=0.610(±0.269) pairwise=0.809   |   cosine τ=0.354(±0.149) pairwise=0.679
liter     local_0_10       probe τ=0.598(±0.236) pairwise=0.803   |   cosine τ=0.412(±0.123) pairwise=0.709
second    local_0_10       probe τ=0.595(±0.162) pairwise=0.801   |   cosine τ=0.351(±0.074) pairwise=0.678
meter     medium_0_1000    probe τ=0.328(±0.086) pairwise=0.666   |   cosine τ=0.474(±0.179) pairwise=0.740
kilogram  medium_0_1000    probe τ=0.317(±0.099) pairwise=0.661   |   cosine τ=0.386(±0.260) pairwise=0.696
liter     medium_0_1000    probe τ=0.397(±0.089) pairwise=0.701   |   cosine τ=0.486(±0.213) pairwise=0.746
second    medium_0_1000    probe τ=0.525(±0.162) pairwise=0.766   |   cosine τ=0.571(±0.166) pairwise=0.789
meter     log_1_100k       probe τ=0.217(±0.111) pairwise=0.609   |   cosine τ=0.407(±0.204) pairwise=0.704
kilogram  log_1_100k       probe τ=0.176(±0.133) pairwise=0.588   |   cosine τ=0.251(±0.196) pairwise=0.626
liter     log_1_100k       probe τ=0.256(±0.132) pairwise=0.628   |   cosine τ=0.256(±0.175) pairwise=0.628
second    log_1_100k       probe τ=0.241(±0.052) pairwise=0.621   |   cosine τ=0.273(±0.163) pairwise=0.637
meter     sign_split       probe τ=0.075(±0.287) pairwise=0.539   |   cosine τ=0.133(±0.170) pairwise=0.568
kilogram  sign_split       probe τ=0.021(±0.289) pairwise=0.512   |   cosine τ=0.097(±0.137) pairwise=0.549
liter     sign_split       probe τ=0.072(±0.314) pairwise=0.538   |   cosine τ=0.093(±0.202) pairwise=0.547
second    sign_split       probe τ=0.429(±0.184) pairwise=0.718   |   cosine τ=0.433(±0.149) pairwise=0.720
meter     scientific       probe τ=0.227(±0.076) pairwise=0.613   |   cosine τ=0.163(±0.112) pairwise=0.582
kilogram  scientific       probe τ=0.232(±0.076) pairwise=0.616   |   cosine τ=0.187(±0.052) pairwise=0.594
liter     scientific       probe τ=0.270(±0.139) pairwise=0.635   |   cosine τ=0.170(±0.075) pairwise=0.585
second    scientific       probe τ=0.344(±0.108) pairwise=0.672   |   cosine τ=0.314(±0.086) pairwise=0.657

               model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
mxbai_embed_large_v1       0.32542       0.664401      0.18273      0.092601             0.309504              0.656183            0.138192             0.070072
================================================================================
microsoft/harrier-oss-v1-270m
================================================================================

[transformers] Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'sliding_attention', 'full_attention'}

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

[transformers] Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'sliding_attention', 'full_attention'}
[transformers] Unrecognized keys in `rope_parameters` for 'rope_type'='default': {'sliding_attention', 'full_attention'}

meter     local_0_10       probe τ=0.579(±0.169) pairwise=0.793   |   cosine τ=0.342(±0.097) pairwise=0.672
kilogram  local_0_10       probe τ=0.499(±0.209) pairwise=0.753   |   cosine τ=0.316(±0.106) pairwise=0.660
liter     local_0_10       probe τ=0.491(±0.167) pairwise=0.749   |   cosine τ=0.257(±0.112) pairwise=0.630
second    local_0_10       probe τ=0.606(±0.150) pairwise=0.807   |   cosine τ=0.257(±0.093) pairwise=0.629
meter     medium_0_1000    probe τ=0.598(±0.061) pairwise=0.802   |   cosine τ=0.501(±0.058) pairwise=0.753
kilogram  medium_0_1000    probe τ=0.549(±0.123) pairwise=0.779   |   cosine τ=0.394(±0.086) pairwise=0.700
liter     medium_0_1000    probe τ=0.564(±0.099) pairwise=0.786   |   cosine τ=0.428(±0.106) pairwise=0.717
second    medium_0_1000    probe τ=0.603(±0.121) pairwise=0.806   |   cosine τ=0.490(±0.089) pairwise=0.748
meter     log_1_100k       probe τ=0.405(±0.105) pairwise=0.703   |   cosine τ=0.489(±0.103) pairwise=0.745
kilogram  log_1_100k       probe τ=0.458(±0.053) pairwise=0.729   |   cosine τ=0.507(±0.060) pairwise=0.754
liter     log_1_100k       probe τ=0.419(±0.136) pairwise=0.710   |   cosine τ=0.470(±0.081) pairwise=0.735
second    log_1_100k       probe τ=0.499(±0.073) pairwise=0.749   |   cosine τ=0.534(±0.089) pairwise=0.767
meter     sign_split       probe τ=0.441(±0.068) pairwise=0.724   |   cosine τ=0.575(±0.084) pairwise=0.792
kilogram  sign_split       probe τ=0.449(±0.101) pairwise=0.728   |   cosine τ=0.486(±0.091) pairwise=0.746
liter     sign_split       probe τ=0.464(±0.044) pairwise=0.736   |   cosine τ=0.532(±0.114) pairwise=0.769
second    sign_split       probe τ=0.476(±0.113) pairwise=0.742   |   cosine τ=0.563(±0.072) pairwise=0.785
meter     scientific       probe τ=0.340(±0.115) pairwise=0.670   |   cosine τ=0.165(±0.157) pairwise=0.583
kilogram  scientific       probe τ=0.340(±0.060) pairwise=0.670   |   cosine τ=0.186(±0.142) pairwise=0.593
liter     scientific       probe τ=0.354(±0.079) pairwise=0.677   |   cosine τ=0.187(±0.170) pairwise=0.594
second    scientific       probe τ=0.325(±0.096) pairwise=0.663   |   cosine τ=0.217(±0.140) pairwise=0.609

              model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
harrier_oss_v1_270m      0.472909       0.738832      0.09121      0.047155             0.394777              0.698928            0.140257             0.071014
================================================================================
microsoft/harrier-oss-v1-0.6b
================================================================================

Loading weights:   0%|          | 0/310 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.372(±0.235) pairwise=0.689   |   cosine τ=0.296(±0.097) pairwise=0.650
kilogram  local_0_10       probe τ=0.399(±0.103) pairwise=0.703   |   cosine τ=0.300(±0.091) pairwise=0.652
liter     local_0_10       probe τ=0.377(±0.209) pairwise=0.692   |   cosine τ=0.287(±0.090) pairwise=0.646
second    local_0_10       probe τ=0.398(±0.128) pairwise=0.702   |   cosine τ=0.288(±0.124) pairwise=0.646
meter     medium_0_1000    probe τ=0.470(±0.258) pairwise=0.738   |   cosine τ=0.440(±0.057) pairwise=0.723
kilogram  medium_0_1000    probe τ=0.471(±0.181) pairwise=0.738   |   cosine τ=0.410(±0.070) pairwise=0.708
liter     medium_0_1000    probe τ=0.483(±0.206) pairwise=0.745   |   cosine τ=0.395(±0.063) pairwise=0.701
second    medium_0_1000    probe τ=0.401(±0.141) pairwise=0.703   |   cosine τ=0.318(±0.062) pairwise=0.662
meter     log_1_100k       probe τ=0.431(±0.037) pairwise=0.715   |   cosine τ=0.499(±0.045) pairwise=0.750
kilogram  log_1_100k       probe τ=0.475(±0.090) pairwise=0.738   |   cosine τ=0.453(±0.097) pairwise=0.727
liter     log_1_100k       probe τ=0.532(±0.057) pairwise=0.766   |   cosine τ=0.470(±0.050) pairwise=0.735
second    log_1_100k       probe τ=0.475(±0.086) pairwise=0.738   |   cosine τ=0.511(±0.055) pairwise=0.756
meter     sign_split       probe τ=0.295(±0.139) pairwise=0.650   |   cosine τ=0.250(±0.137) pairwise=0.626
kilogram  sign_split       probe τ=0.355(±0.107) pairwise=0.680   |   cosine τ=0.281(±0.225) pairwise=0.642
liter     sign_split       probe τ=0.302(±0.112) pairwise=0.654   |   cosine τ=0.231(±0.167) pairwise=0.617
second    sign_split       probe τ=0.398(±0.111) pairwise=0.702   |   cosine τ=0.404(±0.114) pairwise=0.704
meter     scientific       probe τ=0.363(±0.082) pairwise=0.682   |   cosine τ=0.251(±0.161) pairwise=0.625
kilogram  scientific       probe τ=0.341(±0.085) pairwise=0.671   |   cosine τ=0.262(±0.158) pairwise=0.631
liter     scientific       probe τ=0.354(±0.070) pairwise=0.677   |   cosine τ=0.287(±0.156) pairwise=0.644
second    scientific       probe τ=0.316(±0.111) pairwise=0.658   |   cosine τ=0.254(±0.146) pairwise=0.627

              model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
harrier_oss_v1_0.6b      0.400473       0.702115     0.066599       0.03324             0.344346              0.673459             0.09265             0.046399
================================================================================
lightonai/DenseOn
================================================================================

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

meter     local_0_10       probe τ=0.452(±0.199) pairwise=0.729   |   cosine τ=0.433(±0.107) pairwise=0.720
kilogram  local_0_10       probe τ=0.478(±0.174) pairwise=0.742   |   cosine τ=0.511(±0.050) pairwise=0.760
liter     local_0_10       probe τ=0.482(±0.268) pairwise=0.744   |   cosine τ=0.431(±0.126) pairwise=0.718
second    local_0_10       probe τ=0.421(±0.160) pairwise=0.713   |   cosine τ=0.374(±0.128) pairwise=0.689
meter     medium_0_1000    probe τ=0.257(±0.127) pairwise=0.629   |   cosine τ=0.405(±0.144) pairwise=0.705
kilogram  medium_0_1000    probe τ=0.254(±0.090) pairwise=0.628   |   cosine τ=0.415(±0.140) pairwise=0.711
liter     medium_0_1000    probe τ=0.307(±0.098) pairwise=0.655   |   cosine τ=0.442(±0.073) pairwise=0.725
second    medium_0_1000    probe τ=0.354(±0.090) pairwise=0.679   |   cosine τ=0.394(±0.148) pairwise=0.700
meter     log_1_100k       probe τ=0.386(±0.089) pairwise=0.693   |   cosine τ=0.424(±0.077) pairwise=0.712
kilogram  log_1_100k       probe τ=0.311(±0.131) pairwise=0.656   |   cosine τ=0.388(±0.124) pairwise=0.694
liter     log_1_100k       probe τ=0.372(±0.090) pairwise=0.686   |   cosine τ=0.446(±0.068) pairwise=0.723
second    log_1_100k       probe τ=0.234(±0.091) pairwise=0.617   |   cosine τ=0.372(±0.094) pairwise=0.686
meter     sign_split       probe τ=0.495(±0.102) pairwise=0.751   |   cosine τ=0.386(±0.124) pairwise=0.696
kilogram  sign_split       probe τ=0.579(±0.104) pairwise=0.793   |   cosine τ=0.474(±0.094) pairwise=0.740
liter     sign_split       probe τ=0.436(±0.057) pairwise=0.721   |   cosine τ=0.421(±0.148) pairwise=0.713
second    sign_split       probe τ=0.498(±0.113) pairwise=0.753   |   cosine τ=0.393(±0.093) pairwise=0.699
meter     scientific       probe τ=0.195(±0.192) pairwise=0.598   |   cosine τ=0.244(±0.140) pairwise=0.622
kilogram  scientific       probe τ=0.267(±0.173) pairwise=0.633   |   cosine τ=0.200(±0.100) pairwise=0.600
liter     scientific       probe τ=0.086(±0.143) pairwise=0.543   |   cosine τ=0.262(±0.135) pairwise=0.631
second    scientific       probe τ=0.263(±0.136) pairwise=0.632   |   cosine τ=0.367(±0.171) pairwise=0.683

  model  kendall_mean  pairwise_mean  kendall_std  pairwise_std  kendall_cosine_mean  pairwise_cosine_mean  kendall_cosine_std  pairwise_cosine_std
DenseOn      0.356374       0.679805     0.124869      0.063755             0.389061              0.696349             0.07572             0.038874

,model,unit,range,kendall,pairwise,kendall_cosine,pairwise_cosine,kendall_sd_splits,kendall_cosine_sd_splits,alpha_median,n_splits,n_train_pairs,n_train_items,n_test_items
0,mxbai_embed_large_v1,meter,local_0_10,0.578167,0.792590,0.377115,0.690529,0.240317,0.130259,0.01,5,364,14,7
1,mxbai_embed_large_v1,kilogram,local_0_10,0.610159,0.809388,0.354392,0.679236,0.268788,0.149424,0.01,5,364,14,7
2,mxbai_embed_large_v1,liter,local_0_10,0.598032,0.802951,0.412337,0.708624,0.235626,0.123226,0.01,5,364,14,7
3,mxbai_embed_large_v1,second,local_0_10,0.594624,0.801455,0.350968,0.677718,0.162249,0.074222,0.01,5,364,14,7
4,mxbai_embed_large_v1,meter,medium_0_1000,0.327591,0.665767,0.474477,0.740304,0.085841,0.178920,0.01,5,364,14,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,DenseOn,second,sign_split,0.498389,0.752800,0.392931,0.698702,0.113252,0.092654,0.01,5,364,14,7
76,DenseOn,meter,scientific,0.195238,0.597619,0.244444,0.622222,0.191597,0.140119,0.01,5,480,16,9
77,DenseOn,kilogram,scientific,0.266667,0.633333,0.200000,0.600000,0.172571,0.100138,0.01,5,480,16,9
78,DenseOn,liter,scientific,0.085714,0.542857,0.261905,0.630952,0.142681,0.135270,0.01,5,480,16,9
79,DenseOn,second,scientific,0.263492,0.631746,0.366667,0.683333,0.136360,0.170718,0.01,5,480,16,9

# Tables

Regenerates the LaTeX tables from the CSVs on disk, so they stay in sync with
whatever has been run. Requires the Exam 1 definitions cell (for `CSV_DIR`,
`TEX_DIR`).

* `table1_model_ranking.tex` - paper Table 1
* `table2_unit_range.tex` - paper Table 2
* `table3_lexical.tex` - paper Table 3
* `table4_regression_probe.tex` - new, Exam 3

In [ ]:
"""
LaTeX tables, regenerated from the CSVs in produced_results/csv, so they stay in
sync with whatever has been run.

  table1_model_ranking.tex      -- aggregate model ranking (paper Table 1)
  table2_unit_range.tex         -- per unit/range tau across models (Table 2)
  table3_lexical.tex            -- lexical vs. numerical association (Table 3)
  table4_regression_probe.tex   -- calibration probe vs. cosine (new)

Each function takes a `models` list, so the same code produces the main-paper
table and an appendix table over everything on disk (`models=None`).

Requires the Exam 1 definitions cell for CSV_DIR / TEX_DIR.
"""

import glob

KEY = ["model", "unit", "range"]
LEX_KEY = ["model", "group_type", "group", "reference"]

# models shown in the main paper; None = every model found on disk
MAIN_MODELS = [
    "all_MiniLM_L6_v2",
    "all_mpnet_base_v2",
    "e5_large_v2",
    "bge_large_en_v1.5",
    "nomic_embed_text_v1.5",
    "Qwen3_Embedding_0.6B",
    "Qwen3_Embedding_4B",
    "Qwen3_Embedding_8B",
]


def _load(pattern, key, models):
    files = sorted(glob.glob(os.path.join(CSV_DIR, pattern)))
    if not files:
        raise FileNotFoundError(f"no files matching {pattern} in {CSV_DIR}")

    df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)
    df = df.drop_duplicates(subset=key, keep="last")

    if models is not None:
        df = df[df["model"].isin(models)]

    return df.reset_index(drop=True)


def load_results(pattern="*_benchmark_full.csv", models=None):
    """Per-model benchmark CSVs, with the cumulative duplicates dropped."""
    return _load(pattern, KEY, models)


def load_lexical(models=None):
    """Per-model lexical CSVs (long format)."""
    return _load("*_lexical.csv", LEX_KEY, models)


def _num(v, width=5, decimals=2):
    """00.00 / -07.33 style, matching the paper."""
    if pd.isna(v):
        return "--"
    return f"-{abs(v):0{width}.{decimals}f}" if v < 0 else f"{v:0{width}.{decimals}f}"


def _num1(v):
    return _num(v, width=4, decimals=1)


def _name(m):
    return m.replace("_", r"\_")


def _order(df, models):
    """Keep the caller's model order; fall back to alphabetical."""
    if models is None:
        return sorted(df["model"].unique())
    return [m for m in models if m in set(df["model"])]


def _write(lines, filename):
    path = os.path.join(TEX_DIR, filename)
    text = "\n".join(lines) + "\n"
    with open(path, "w") as f:
        f.write(text)
    print(text)
    print(f"-> {path}\n")
    return path


# --------------------------------------------------------------------
# Table 1 -- aggregate model ranking
# --------------------------------------------------------------------

def table_model_ranking(models=MAIN_MODELS, filename="table1_model_ranking.tex"):

    df = load_results(models=models)

    agg = (df.groupby("model")[["kendall", "pairwise"]].mean() * 100)
    agg["avg"] = (agg["kendall"] + agg["pairwise"]) / 2
    agg = agg.sort_values("avg", ascending=False)

    lines = [
        r"\begin{tabular}{lcc|c}",
        r"\toprule",
        r"model & K's $\tau$ & PACC & AVG \\",
        r"\midrule",
    ]

    for model, r in agg.iterrows():
        lines.append(
            f"{_name(model)} & {_num(r['kendall'])} & {_num(r['pairwise'])} & {_num(r['avg'])} \\\\"
        )

    all_tau = df["kendall"].mean() * 100
    all_pacc = df["pairwise"].mean() * 100

    lines += [
        r"\midrule",
        f"all & {_num(all_tau)} & {_num(all_pacc)} & {_num((all_tau + all_pacc) / 2)} \\\\",
        r"random-baseline & 00.00 & 50.00 & 25.00 \\",
        r"\bottomrule",
        r"\end{tabular}",
    ]

    return _write(lines, filename)


# --------------------------------------------------------------------
# Table 2 -- average / min / max tau per unit and range
# --------------------------------------------------------------------

def table_unit_range(models=MAIN_MODELS, filename="table2_unit_range.tex"):

    df = load_results(models=models)

    agg = (df.groupby(["unit", "range"])["kendall"].agg(["mean", "min", "max"]) * 100)

    lines = [
        r"\begin{tabular}{llccc}",
        r"\toprule",
        r"Unit & Range & Avg & Min & Max \\",
        r"\midrule",
    ]

    for unit in sorted(agg.index.get_level_values("unit").unique()):
        sub = agg.loc[unit].sort_index()

        for range_name, r in sub.iterrows():
            lines.append(
                f"{unit} & {_name(range_name)} & "
                f"{_num(r['mean'])} & {_num(r['min'])} & {_num(r['max'])} \\\\"
            )

        lines.append(
            f"{unit} & AVG & "
            f"{_num(sub['mean'].mean())} & {_num(sub['min'].mean())} & {_num(sub['max'].mean())} \\\\"
        )
        lines.append(r"\midrule")

    lines[-1] = r"\bottomrule"
    lines.append(r"\end{tabular}")

    return _write(lines, filename)


# --------------------------------------------------------------------
# Table 3 -- lexical vs. numerical association
# --------------------------------------------------------------------

LEX_COLUMNS = [
    ("overall", "all", "Overall"),
    ("type_pair", "float-float", "FF"),
    ("type_pair", "float-int", "FI"),
    ("type_pair", "int-int", "II"),
]

LEX_REFERENCES = [
    ("char_lev", "Character"),
    ("token_lev", "Tokenizer"),
    ("num_dist", "Numeric"),
]


def table_lexical(models=MAIN_MODELS, filename="table3_lexical.tex"):

    df = load_lexical(models=models)

    lookup = {
        (r.model, r.group_type, r.group, r.reference): r.tau
        for r in df.itertuples()
    }

    lines = [
        r"\begin{tabular}{lcccc|cccc|cccc}",
        r"\toprule",
        r"& \multicolumn{4}{c}{Character}"
        r"& \multicolumn{4}{c}{Tokenizer}"
        r"& \multicolumn{4}{c}{Numeric} \\",
        r"\cmidrule(lr){2-5}\cmidrule(lr){6-9}\cmidrule(lr){10-13}",
        r"Model"
        r" & Overall & FF & FI & II"
        r" & Overall & FF & FI & II"
        r" & Overall & FF & FI & II \\",
        r"\midrule",
    ]

    for model in _order(df, models):
        row = [_name(model)]
        for reference, _ in LEX_REFERENCES:
            for group_type, group, _ in LEX_COLUMNS:
                tau = lookup.get((model, group_type, group, reference))
                row.append(_num1(100 * tau) if tau is not None else "--")
        lines.append(" & ".join(row) + r" \\")

    lines += [r"\bottomrule", r"\end{tabular}"]

    return _write(lines, filename)


# --------------------------------------------------------------------
# Table 4 -- calibration probe vs. cosine
# --------------------------------------------------------------------

def table_regression_probe(models=MAIN_MODELS, filename="table4_regression_probe.tex"):

    df = load_results(
        pattern="*_benchmark_full_regression_experiment.csv",
        models=models,
    )

    cols = ["kendall_cosine", "pairwise_cosine", "kendall", "pairwise"]
    agg = (df.groupby("model")[cols].mean() * 100)
    agg["delta"] = agg["kendall"] - agg["kendall_cosine"]
    agg = agg.sort_values("kendall", ascending=False)

    lines = [
        r"\begin{tabular}{lcc|cc|c}",
        r"\toprule",
        r"& \multicolumn{2}{c}{Cosine} & \multicolumn{2}{c}{Linear probe} & \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
        r"model & K's $\tau$ & PACC & K's $\tau$ & PACC & $\Delta\tau$ \\",
        r"\midrule",
    ]

    for model, r in agg.iterrows():
        lines.append(
            f"{_name(model)} & "
            f"{_num(r['kendall_cosine'])} & {_num(r['pairwise_cosine'])} & "
            f"{_num(r['kendall'])} & {_num(r['pairwise'])} & {_num(r['delta'])} \\\\"
        )

    m = agg.mean()
    lines += [
        r"\midrule",
        f"all & {_num(m['kendall_cosine'])} & {_num(m['pairwise_cosine'])} & "
        f"{_num(m['kendall'])} & {_num(m['pairwise'])} & {_num(m['delta'])} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
    ]

    return _write(lines, filename)

### Main paper tables

In [ ]:
table_model_ranking()
table_unit_range()
table_lexical()
table_regression_probe()

\begin{tabular}{lcc|c}
\toprule
model & K's $\tau$ & PACC & AVG \\
\midrule
all\_mpnet\_base\_v2 & 43.24 & 71.83 & 57.53 \\
e5\_large\_v2 & 40.45 & 70.40 & 55.43 \\
Qwen3\_Embedding\_4B & 39.51 & 69.94 & 54.72 \\
all\_MiniLM\_L6\_v2 & 39.03 & 69.72 & 54.38 \\
Qwen3\_Embedding\_0.6B & 38.44 & 69.39 & 53.91 \\
Qwen3\_Embedding\_8B & 37.23 & 68.80 & 53.01 \\
bge\_large\_en\_v1.5 & 35.17 & 67.77 & 51.47 \\
nomic\_embed\_text\_v1.5 & 26.98 & 63.64 & 45.31 \\
\midrule
all & 37.51 & 68.94 & 53.22 \\
random-baseline & 00.00 & 50.00 & 25.00 \\
\bottomrule
\end{tabular}

-> produced_results/tex/table1_model_ranking.tex

\begin{tabular}{llccc}
\toprule
Unit & Range & Avg & Min & Max \\
\midrule
kilogram & local\_0\_10 & 29.48 & 19.04 & 39.75 \\
kilogram & log\_1\_100k & 35.32 & 20.64 & 55.26 \\
kilogram & medium\_0\_1000 & 35.29 & 20.06 & 50.59 \\
kilogram & scientific & 33.01 & 12.10 & 51.15 \\
kilogram & sign\_split & 38.39 & 20.28 & 58.35 \\
kilogram & AVG & 34.30 & 18.42 & 51.02 \\
\midrule
liter & local\_0\_10 & 33.05 & 09.81 & 45.38 \\
liter & log\_1\_100k & 41.12 & 22.72 & 55.55 \\
liter & medium\_0\_1000 & 38.29 & 17.11 & 50.52 \\
liter & scientific & 34.18 & 13.09 & 53.44 \\
liter & sign\_split & 37.26 & 16.89 & 55.26 \\
liter & AVG & 36.78 & 15.92 & 52.03 \\
\midrule
meter & local\_0\_10 & 34.87 & 26.04 & 43.56 \\
meter & log\_1\_100k & 46.66 & 26.73 & 62.91 \\
meter & medium\_0\_1000 & 35.90 & 19.00 & 47.42 \\
meter & scientific & 33.04 & 13.45 & 51.96 \\
meter & sign\_split & 40.13 & 16.23 & 56.85 \\
meter & AVG & 38.12 & 20.29 & 52.54 \\
\midrule
second & local\_0\_10 & 30.28 & 16.95 & 40.00 \\
second & log\_1\_100k & 52.21 & 24.35 & 67.81 \\
second & medium\_0\_1000 & 42.72 & 31.32 & 50.45 \\
second & scientific & 39.10 & 16.27 & 58.90 \\
second & sign\_split & 39.83 & 11.53 & 50.20 \\
second & AVG & 40.83 & 20.08 & 53.47 \\
\bottomrule
\end{tabular}

-> produced_results/tex/table2_unit_range.tex

\begin{tabular}{lcccc|cccc|cccc}
\toprule
& \multicolumn{4}{c}{Character}& \multicolumn{4}{c}{Tokenizer}& \multicolumn{4}{c}{Numeric} \\
\cmidrule(lr){2-5}\cmidrule(lr){6-9}\cmidrule(lr){10-13}
Model & Overall & FF & FI & II & Overall & FF & FI & II & Overall & FF & FI & II \\
\midrule
all\_MiniLM\_L6\_v2 & 21.0 & 22.0 & 17.1 & 44.2 & 15.1 & 10.4 & 10.2 & 37.1 & 28.1 & 23.0 & 28.7 & 39.0 \\
all\_mpnet\_base\_v2 & 27.7 & 31.7 & 21.0 & 41.9 & 20.4 & 19.9 & 08.7 & 34.0 & 26.1 & 40.9 & 26.0 & 36.2 \\
e5\_large\_v2 & 29.0 & 23.9 & 27.2 & 45.1 & 22.0 & 15.2 & 14.5 & 38.7 & 16.9 & 18.2 & 15.3 & 32.8 \\
bge\_large\_en\_v1.5 & 10.9 & 25.2 & 29.1 & 35.2 & 07.7 & 22.9 & 31.1 & 18.5 & 08.0 & 26.5 & 06.9 & 18.6 \\
nomic\_embed\_text\_v1.5 & -05.6 & 16.9 & 28.9 & 32.8 & -16.9 & -03.7 & 05.7 & 17.5 & 06.5 & 05.8 & 05.9 & 15.2 \\
Qwen3\_Embedding\_0.6B & 47.6 & 23.6 & 30.7 & 50.8 & 47.6 & 23.6 & 30.7 & 50.8 & 11.7 & 13.7 & 13.7 & 25.2 \\
Qwen3\_Embedding\_4B & 30.1 & 26.3 & 38.8 & 53.8 & 30.1 & 26.3 & 38.8 & 53.8 & 13.1 & 12.6 & 08.4 & 27.3 \\
Qwen3\_Embedding\_8B & 36.7 & 33.9 & 39.2 & 49.5 & 36.7 & 33.9 & 39.2 & 49.5 & 18.3 & 24.2 & 15.8 & 25.1 \\
\bottomrule
\end{tabular}

-> produced_results/tex/table3_lexical.tex

\begin{tabular}{lcc|cc|c}
\toprule
& \multicolumn{2}{c}{Cosine} & \multicolumn{2}{c}{Linear probe} & \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}
model & K's $\tau$ & PACC & K's $\tau$ & PACC & $\Delta\tau$ \\
\midrule
e5\_large\_v2 & 35.73 & 68.00 & 48.06 & 74.26 & 12.33 \\
all\_mpnet\_base\_v2 & 40.40 & 70.38 & 42.96 & 71.70 & 02.56 \\
Qwen3\_Embedding\_4B & 35.66 & 67.97 & 41.90 & 71.14 & 06.24 \\
Qwen3\_Embedding\_8B & 33.70 & 67.02 & 41.50 & 70.94 & 07.80 \\
all\_MiniLM\_L6\_v2 & 37.10 & 68.72 & 37.04 & 68.70 & -00.06 \\
bge\_large\_en\_v1.5 & 31.89 & 66.09 & 32.27 & 66.29 & 00.38 \\
Qwen3\_Embedding\_0.6B & 33.70 & 66.98 & 31.93 & 66.11 & -01.77 \\
nomic\_embed\_text\_v1.5 & 25.80 & 63.08 & 29.05 & 64.65 & 03.25 \\
\midrule
all & 34.25 & 67.28 & 38.09 & 69.22 & 03.84 \\
\bottomrule
\end{tabular}

-> produced_results/tex/table4_regression_probe.tex

'produced_results/tex/table4_regression_probe.tex'

### Appendix tables (every model found in `produced_results/csv`)

In [ ]:
table_model_ranking(models=None, filename="appendix_table1_model_ranking.tex")
table_unit_range(models=None, filename="appendix_table2_unit_range.tex")
table_lexical(models=None, filename="appendix_table3_lexical.tex")
table_regression_probe(models=None, filename="appendix_table4_regression_probe.tex")

\begin{tabular}{lcc|c}
\toprule
model & K's $\tau$ & PACC & AVG \\
\midrule
multilingual\_e5\_large\_instruct & 50.29 & 75.37 & 62.83 \\
LaBSE & 44.62 & 72.53 & 58.57 \\
all\_mpnet\_base\_v2 & 43.24 & 71.83 & 57.53 \\
harrier\_oss\_v1\_270m & 41.97 & 71.16 & 56.56 \\
harrier\_oss\_v1\_0.6b & 40.86 & 70.61 & 55.74 \\
e5\_large\_v2 & 40.45 & 70.40 & 55.43 \\
Qwen3\_Embedding\_4B & 39.51 & 69.94 & 54.72 \\
bge\_m3 & 39.42 & 69.90 & 54.66 \\
DenseOn & 39.25 & 69.82 & 54.53 \\
multilingual\_e5\_large & 39.21 & 69.80 & 54.50 \\
all\_MiniLM\_L6\_v2 & 39.03 & 69.72 & 54.38 \\
Qwen3\_Embedding\_0.6B & 38.44 & 69.39 & 53.91 \\
Qwen3\_Embedding\_8B & 37.23 & 68.80 & 53.01 \\
multilingual\_e5\_base & 35.42 & 67.89 & 51.65 \\
bge\_large\_en\_v1.5 & 35.17 & 67.77 & 51.47 \\
mxbai\_embed\_large\_v1 & 34.96 & 67.66 & 51.31 \\
granite\_embedding\_311m\_multilingual\_r2 & 31.14 & 65.75 & 48.45 \\
granite\_embedding\_278m\_multilingual & 30.36 & 65.34 & 47.85 \\
granite\_embedding\_english\_r2 & 27.53 & 63.92 & 45.73 \\
granite\_embedding\_107m\_multilingual & 27.13 & 63.71 & 45.42 \\
nomic\_embed\_text\_v1.5 & 26.98 & 63.64 & 45.31 \\
granite\_embedding\_97m\_multilingual\_r2 & 26.38 & 63.35 & 44.86 \\
paraphrase\_multilingual\_mpnet\_base\_v2 & 25.76 & 63.01 & 44.38 \\
embeddinggemma\_300m & 25.41 & 62.86 & 44.13 \\
\midrule
all & 35.82 & 68.09 & 51.96 \\
random-baseline & 00.00 & 50.00 & 25.00 \\
\bottomrule
\end{tabular}

-> produced_results/tex/appendix_table1_model_ranking.tex

\begin{tabular}{llccc}
\toprule
Unit & Range & Avg & Min & Max \\
\midrule
kilogram & local\_0\_10 & 31.00 & 19.04 & 46.95 \\
kilogram & log\_1\_100k & 36.38 & 14.82 & 66.53 \\
kilogram & medium\_0\_1000 & 38.59 & 20.06 & 53.39 \\
kilogram & scientific & 31.20 & 11.44 & 51.15 \\
kilogram & sign\_split & 34.56 & 03.69 & 58.35 \\
kilogram & AVG & 34.35 & 13.81 & 55.28 \\
\midrule
liter & local\_0\_10 & 31.78 & 09.81 & 48.91 \\
liter & log\_1\_100k & 39.63 & 15.34 & 65.34 \\
liter & medium\_0\_1000 & 40.30 & 17.11 & 57.08 \\
liter & scientific & 31.64 & 13.09 & 53.44 \\
liter & sign\_split & 33.40 & 03.12 & 55.26 \\
liter & AVG & 35.35 & 11.69 & 56.01 \\
\midrule
meter & local\_0\_10 & 32.99 & 25.03 & 47.99 \\
meter & log\_1\_100k & 43.60 & 14.47 & 73.55 \\
meter & medium\_0\_1000 & 38.56 & 19.00 & 56.22 \\
meter & scientific & 31.64 & 12.94 & 51.96 \\
meter & sign\_split & 36.22 & 04.16 & 56.85 \\
meter & AVG & 36.60 & 15.12 & 57.31 \\
\midrule
second & local\_0\_10 & 27.63 & 16.95 & 40.00 \\
second & log\_1\_100k & 44.62 & 13.05 & 75.69 \\
second & medium\_0\_1000 & 41.08 & 19.66 & 58.23 \\
second & scientific & 34.58 & 13.03 & 58.90 \\
second & sign\_split & 37.06 & 06.72 & 55.75 \\
second & AVG & 37.00 & 13.88 & 57.71 \\
\bottomrule
\end{tabular}

-> produced_results/tex/appendix_table2_unit_range.tex

\begin{tabular}{lcccc|cccc|cccc}
\toprule
& \multicolumn{4}{c}{Character}& \multicolumn{4}{c}{Tokenizer}& \multicolumn{4}{c}{Numeric} \\
\cmidrule(lr){2-5}\cmidrule(lr){6-9}\cmidrule(lr){10-13}
Model & Overall & FF & FI & II & Overall & FF & FI & II & Overall & FF & FI & II \\
\midrule
DenseOn & 23.5 & 18.1 & 21.0 & 36.9 & 27.4 & 17.0 & 25.1 & 31.6 & 20.2 & 20.2 & 18.9 & 33.3 \\
LaBSE & 39.6 & 32.7 & 28.5 & 48.7 & 42.7 & 42.0 & 13.0 & 35.7 & 18.1 & 29.7 & 18.8 & 24.4 \\
Qwen3\_Embedding\_0.6B & 47.6 & 23.6 & 30.7 & 50.8 & 47.6 & 23.6 & 30.7 & 50.8 & 11.7 & 13.7 & 13.7 & 25.2 \\
Qwen3\_Embedding\_4B & 30.1 & 26.3 & 38.8 & 53.8 & 30.1 & 26.3 & 38.8 & 53.8 & 13.1 & 12.6 & 08.4 & 27.3 \\
Qwen3\_Embedding\_8B & 36.7 & 33.9 & 39.2 & 49.5 & 36.7 & 33.9 & 39.2 & 49.5 & 18.3 & 24.2 & 15.8 & 25.1 \\
all\_MiniLM\_L6\_v2 & 21.0 & 22.0 & 17.1 & 44.2 & 15.1 & 10.4 & 10.2 & 37.1 & 28.1 & 23.0 & 28.7 & 39.0 \\
all\_mpnet\_base\_v2 & 27.7 & 31.7 & 21.0 & 41.9 & 20.4 & 19.9 & 08.7 & 34.0 & 26.1 & 40.9 & 26.0 & 36.2 \\
bge\_large\_en\_v1.5 & 10.9 & 25.2 & 29.1 & 35.2 & 07.7 & 22.9 & 31.1 & 18.5 & 08.0 & 26.5 & 06.9 & 18.6 \\
bge\_m3 & 18.1 & 31.3 & 36.8 & 49.2 & 03.6 & 25.0 & 25.7 & 31.9 & 19.5 & 34.3 & 22.7 & 29.7 \\
e5\_large\_v2 & 29.0 & 23.9 & 27.2 & 45.1 & 22.0 & 15.2 & 14.5 & 38.7 & 16.9 & 18.2 & 15.3 & 32.8 \\
embeddinggemma\_300m & 51.6 & 36.3 & 39.6 & 44.6 & 51.6 & 36.3 & 39.6 & 44.6 & 03.3 & 08.3 & 02.1 & 08.8 \\
granite\_embedding\_107m\_multilingual & 27.0 & 25.9 & 32.4 & 43.1 & 16.7 & 10.9 & 14.1 & 31.0 & 16.7 & 14.9 & 16.4 & 20.6 \\
granite\_embedding\_278m\_multilingual & 29.4 & 25.1 & 33.2 & 46.3 & 16.3 & 11.8 & 14.5 & 25.2 & 14.8 & 11.7 & 14.6 & 21.1 \\
granite\_embedding\_311m\_multilingual\_r2 & 14.2 & 32.5 & 33.3 & 53.6 & 14.2 & 32.5 & 33.3 & 53.6 & 09.1 & 17.0 & 10.4 & 11.8 \\
granite\_embedding\_97m\_multilingual\_r2 & 04.9 & 17.5 & 11.9 & 27.9 & 08.5 & 18.9 & 02.5 & 29.3 & 12.5 & 12.5 & 12.7 & 21.2 \\
granite\_embedding\_english\_r2 & 16.7 & 29.9 & 29.6 & 44.6 & 09.1 & 14.7 & 04.6 & 21.1 & 14.4 & 20.5 & 10.8 & 22.6 \\
harrier\_oss\_v1\_0.6b & 27.0 & 42.1 & 32.0 & 43.0 & 27.0 & 42.1 & 32.0 & 43.0 & 21.7 & 46.1 & 29.7 & 32.6 \\
harrier\_oss\_v1\_270m & 28.4 & 42.5 & 30.5 & 43.1 & 28.4 & 42.5 & 30.5 & 43.1 & 23.3 & 48.5 & 32.8 & 38.0 \\
multilingual\_e5\_base & 23.5 & 32.6 & 34.3 & 50.3 & 06.8 & 27.3 & 13.6 & 27.7 & 17.2 & 24.1 & 23.3 & 25.4 \\
multilingual\_e5\_large & 25.5 & 32.4 & 29.4 & 50.1 & 06.8 & 24.9 & 00.9 & 31.2 & 18.4 & 37.4 & 26.9 & 24.9 \\
multilingual\_e5\_large\_instruct & 39.7 & 28.1 & 29.4 & 40.4 & 27.5 & 25.3 & 15.9 & 22.4 & 26.9 & 49.1 & 29.9 & 30.7 \\
mxbai\_embed\_large\_v1 & 10.0 & 24.2 & 28.7 & 33.9 & 05.4 & 16.0 & 26.6 & 17.1 & 06.9 & 18.0 & 06.1 & 16.5 \\
nomic\_embed\_text\_v1.5 & -05.6 & 16.9 & 28.9 & 32.8 & -16.9 & -03.7 & 05.7 & 17.5 & 06.5 & 05.8 & 05.9 & 15.2 \\
paraphrase\_multilingual\_mpnet\_base\_v2 & 05.0 & 17.8 & 19.8 & 29.7 & -11.5 & -05.0 & 03.7 & 06.4 & 08.1 & 14.4 & 07.0 & 08.2 \\
\bottomrule
\end{tabular}

-> produced_results/tex/appendix_table3_lexical.tex

\begin{tabular}{lcc|cc|c}
\toprule
& \multicolumn{2}{c}{Cosine} & \multicolumn{2}{c}{Linear probe} & \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}
model & K's $\tau$ & PACC & K's $\tau$ & PACC & $\Delta\tau$ \\
\midrule
multilingual\_e5\_large\_instruct & 44.73 & 72.54 & 51.40 & 75.92 & 06.67 \\
LaBSE & 43.55 & 71.97 & 50.07 & 75.27 & 06.51 \\
e5\_large\_v2 & 35.73 & 68.00 & 48.06 & 74.26 & 12.33 \\
harrier\_oss\_v1\_270m & 39.48 & 69.89 & 47.29 & 73.88 & 07.81 \\
multilingual\_e5\_large & 38.04 & 69.17 & 43.53 & 71.95 & 05.49 \\
all\_mpnet\_base\_v2 & 40.40 & 70.38 & 42.96 & 71.70 & 02.56 \\
Qwen3\_Embedding\_4B & 35.66 & 67.97 & 41.90 & 71.14 & 06.24 \\
Qwen3\_Embedding\_8B & 33.70 & 67.02 & 41.50 & 70.94 & 07.80 \\
harrier\_oss\_v1\_0.6b & 34.43 & 67.35 & 40.05 & 70.21 & 05.61 \\
bge\_m3 & 37.32 & 68.83 & 39.65 & 70.01 & 02.33 \\
multilingual\_e5\_base & 31.91 & 66.10 & 39.32 & 69.84 & 07.41 \\
all\_MiniLM\_L6\_v2 & 37.10 & 68.72 & 37.04 & 68.70 & -00.06 \\
DenseOn & 38.91 & 69.63 & 35.64 & 67.98 & -03.27 \\
granite\_embedding\_278m\_multilingual & 29.98 & 65.11 & 33.20 & 66.73 & 03.22 \\
mxbai\_embed\_large\_v1 & 30.95 & 65.62 & 32.54 & 66.44 & 01.59 \\
bge\_large\_en\_v1.5 & 31.89 & 66.09 & 32.27 & 66.29 & 00.38 \\
granite\_embedding\_311m\_multilingual\_r2 & 28.89 & 64.60 & 32.16 & 66.24 & 03.27 \\
Qwen3\_Embedding\_0.6B & 33.70 & 66.98 & 31.93 & 66.11 & -01.77 \\
nomic\_embed\_text\_v1.5 & 25.80 & 63.08 & 29.05 & 64.65 & 03.25 \\
granite\_embedding\_97m\_multilingual\_r2 & 26.77 & 63.53 & 28.65 & 64.48 & 01.88 \\
paraphrase\_multilingual\_mpnet\_base\_v2 & 20.42 & 60.34 & 26.85 & 63.55 & 06.43 \\
granite\_embedding\_english\_r2 & 25.48 & 62.89 & 26.73 & 63.52 & 01.25 \\
embeddinggemma\_300m & 28.27 & 64.27 & 21.01 & 60.60 & -07.27 \\
granite\_embedding\_107m\_multilingual & 29.31 & 64.76 & 20.38 & 60.26 & -08.93 \\
\midrule
all & 33.44 & 66.87 & 36.38 & 68.36 & 02.95 \\
\bottomrule
\end{tabular}

-> produced_results/tex/appendix_table4_regression_probe.tex

'produced_results/tex/appendix_table4_regression_probe.tex'

---
# Tokenizer scratch cells

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(
        "Qwen/Qwen3-Embedding-0.6B",
        trust_remote_code=True,
    )

In [ ]:
print(tokenizer.encode(["hello"], add_special_tokens=False))
print(tokenizer.encode(["0.123"], add_special_tokens=False))
print(tokenizer.encode(["11"], add_special_tokens=False))

[[14990]]
[[15, 13, 16, 17, 18]]
[[16, 16]]

# Export

Zips `produced_results/` (pdf + csv + tex) and downloads it. The inventory
printed first is there so you can see at a glance whether a model is missing
before you export.

In [ ]:
import os
import shutil

folder_path = "produced_results"
zip_base = "produced_results_current"

# --- inventory: confirm everything you expect is actually on disk ---
for sub in ["pdf", "csv", "tex"]:
    p = os.path.join(folder_path, sub)
    files_ = sorted(os.listdir(p)) if os.path.isdir(p) else []
    print(f"{sub:4s} {len(files_):5d} files")

n_models = len({
    f.split("_benchmark_full.csv")[0]
    for f in os.listdir(os.path.join(folder_path, "csv"))
    if f.endswith("_benchmark_full.csv")
})
print(f"\nmodels with Exam 1 results: {n_models}")

# --- zip ---
zip_path = shutil.make_archive(zip_base, "zip", folder_path)
print(f"{zip_path}  ({os.path.getsize(zip_path) / 1e6:.1f} MB)")

from google.colab import files
files.download(zip_path)

pdf    624 files
csv    120 files
tex      8 files

models with Exam 1 results: 24
/content/produced_results_current.zip  (8.0 MB)

### Fallback: copy the zip to Drive instead

In [ ]:
# Fallback: browser downloads of large zips sometimes stall in Colab.
# This copies the same zip to Google Drive instead.
from google.colab import drive

drive.mount("/content/drive")
shutil.copy(zip_path, "/content/drive/MyDrive/")
print("copied to /content/drive/MyDrive/")

ValueError: mount failed